package jp.co.daitoku_sh.dfcm.common.db.mapper;

import java.util.List;
import jp.co.daitoku_sh.dfcm.common.db.model.MstCourseList;
import jp.co.daitoku_sh.dfcm.common.db.model.MstCourseListExample;
import jp.co.daitoku_sh.dfcm.common.db.model.MstCourseListKey;
import org.apache.ibatis.annotations.Param;

public interface MstCourseListMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_COURSE_LIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int countByExample(MstCourseListExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_COURSE_LIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByExample(MstCourseListExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_COURSE_LIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByPrimaryKey(MstCourseListKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_COURSE_LIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insert(MstCourseList record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_COURSE_LIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insertSelective(MstCourseList record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_COURSE_LIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  List<MstCourseList> selectByExample(MstCourseListExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_COURSE_LIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  MstCourseList selectByPrimaryKey(MstCourseListKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_COURSE_LIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExampleSelective(@Param("record") MstCourseList record,
      @Param("example") MstCourseListExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_COURSE_LIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExample(@Param("record") MstCourseList record,
      @Param("example") MstCourseListExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_COURSE_LIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKeySelective(MstCourseList record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_COURSE_LIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKey(MstCourseList record);
}