package jp.co.daitoku_sh.dfcm.common.db.mapper;

import java.util.List;
import jp.co.daitoku_sh.dfcm.common.db.model.MstCustTanka;
import jp.co.daitoku_sh.dfcm.common.db.model.MstCustTankaExample;
import jp.co.daitoku_sh.dfcm.common.db.model.MstCustTankaKey;
import org.apache.ibatis.annotations.Param;

public interface MstCustTankaMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_CUST_TANKA
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int countByExample(MstCustTankaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_CUST_TANKA
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByExample(MstCustTankaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_CUST_TANKA
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByPrimaryKey(MstCustTankaKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_CUST_TANKA
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insert(MstCustTanka record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_CUST_TANKA
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insertSelective(MstCustTanka record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_CUST_TANKA
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  List<MstCustTanka> selectByExample(MstCustTankaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_CUST_TANKA
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  MstCustTanka selectByPrimaryKey(MstCustTankaKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_CUST_TANKA
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExampleSelective(@Param("record") MstCustTanka record,
      @Param("example") MstCustTankaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_CUST_TANKA
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExample(@Param("record") MstCustTanka record,
      @Param("example") MstCustTankaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_CUST_TANKA
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKeySelective(MstCustTanka record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_CUST_TANKA
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKey(MstCustTanka record);
}