package jp.co.daitoku_sh.dfcm.common.db.mapper;

import java.util.List;
import jp.co.daitoku_sh.dfcm.common.db.model.MstGeneral;
import jp.co.daitoku_sh.dfcm.common.db.model.MstGeneralExample;
import jp.co.daitoku_sh.dfcm.common.db.model.MstGeneralKey;
import org.apache.ibatis.annotations.Param;

public interface MstGeneralMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_GENERAL
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int countByExample(MstGeneralExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_GENERAL
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByExample(MstGeneralExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_GENERAL
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByPrimaryKey(MstGeneralKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_GENERAL
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insert(MstGeneral record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_GENERAL
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insertSelective(MstGeneral record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_GENERAL
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  List<MstGeneral> selectByExample(MstGeneralExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_GENERAL
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  MstGeneral selectByPrimaryKey(MstGeneralKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_GENERAL
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExampleSelective(@Param("record") MstGeneral record,
      @Param("example") MstGeneralExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_GENERAL
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExample(@Param("record") MstGeneral record,
      @Param("example") MstGeneralExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_GENERAL
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKeySelective(MstGeneral record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_GENERAL
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKey(MstGeneral record);
}