package jp.co.daitoku_sh.dfcm.common.db.mapper;

import java.util.List;
import jp.co.daitoku_sh.dfcm.common.db.model.MstJobexec;
import jp.co.daitoku_sh.dfcm.common.db.model.MstJobexecExample;
import org.apache.ibatis.annotations.Param;

public interface MstJobexecMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_JOBEXEC
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int countByExample(MstJobexecExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_JOBEXEC
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByExample(MstJobexecExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_JOBEXEC
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByPrimaryKey(String hulftId);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_JOBEXEC
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insert(MstJobexec record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_JOBEXEC
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insertSelective(MstJobexec record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_JOBEXEC
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  List<MstJobexec> selectByExample(MstJobexecExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_JOBEXEC
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  MstJobexec selectByPrimaryKey(String hulftId);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_JOBEXEC
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExampleSelective(@Param("record") MstJobexec record,
      @Param("example") MstJobexecExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_JOBEXEC
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExample(@Param("record") MstJobexec record,
      @Param("example") MstJobexecExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_JOBEXEC
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKeySelective(MstJobexec record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_JOBEXEC
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKey(MstJobexec record);
}