package jp.co.daitoku_sh.dfcm.common.db.mapper;

import java.util.List;
import jp.co.daitoku_sh.dfcm.common.db.model.MstListForm;
import jp.co.daitoku_sh.dfcm.common.db.model.MstListFormExample;
import org.apache.ibatis.annotations.Param;

public interface MstListFormMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_LIST_FORM
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int countByExample(MstListFormExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_LIST_FORM
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByExample(MstListFormExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_LIST_FORM
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByPrimaryKey(String listId);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_LIST_FORM
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insert(MstListForm record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_LIST_FORM
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insertSelective(MstListForm record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_LIST_FORM
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  List<MstListForm> selectByExample(MstListFormExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_LIST_FORM
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  MstListForm selectByPrimaryKey(String listId);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_LIST_FORM
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExampleSelective(@Param("record") MstListForm record,
      @Param("example") MstListFormExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_LIST_FORM
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExample(@Param("record") MstListForm record,
      @Param("example") MstListFormExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_LIST_FORM
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKeySelective(MstListForm record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_LIST_FORM
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKey(MstListForm record);
}