package jp.co.daitoku_sh.dfcm.common.db.mapper;

import java.util.List;
import jp.co.daitoku_sh.dfcm.common.db.model.MstSubjectCd;
import jp.co.daitoku_sh.dfcm.common.db.model.MstSubjectCdExample;
import jp.co.daitoku_sh.dfcm.common.db.model.MstSubjectCdKey;
import org.apache.ibatis.annotations.Param;

public interface MstSubjectCdMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_SUBJECT_CD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int countByExample(MstSubjectCdExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_SUBJECT_CD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByExample(MstSubjectCdExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_SUBJECT_CD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByPrimaryKey(MstSubjectCdKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_SUBJECT_CD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insert(MstSubjectCd record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_SUBJECT_CD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insertSelective(MstSubjectCd record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_SUBJECT_CD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  List<MstSubjectCd> selectByExample(MstSubjectCdExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_SUBJECT_CD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  MstSubjectCd selectByPrimaryKey(MstSubjectCdKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_SUBJECT_CD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExampleSelective(@Param("record") MstSubjectCd record,
      @Param("example") MstSubjectCdExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_SUBJECT_CD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExample(@Param("record") MstSubjectCd record,
      @Param("example") MstSubjectCdExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_SUBJECT_CD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKeySelective(MstSubjectCd record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_SUBJECT_CD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKey(MstSubjectCd record);
}