package jp.co.daitoku_sh.dfcm.common.db.mapper;

import java.util.List;
import jp.co.daitoku_sh.dfcm.common.db.model.MstSNohin;
import jp.co.daitoku_sh.dfcm.common.db.model.MstSNohinExample;
import jp.co.daitoku_sh.dfcm.common.db.model.MstSNohinKey;
import org.apache.ibatis.annotations.Param;

public interface MstSNohinMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_S_NOHIN
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int countByExample(MstSNohinExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_S_NOHIN
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByExample(MstSNohinExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_S_NOHIN
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByPrimaryKey(MstSNohinKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_S_NOHIN
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insert(MstSNohin record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_S_NOHIN
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insertSelective(MstSNohin record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_S_NOHIN
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  List<MstSNohin> selectByExample(MstSNohinExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_S_NOHIN
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  MstSNohin selectByPrimaryKey(MstSNohinKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_S_NOHIN
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExampleSelective(@Param("record") MstSNohin record,
      @Param("example") MstSNohinExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_S_NOHIN
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExample(@Param("record") MstSNohin record,
      @Param("example") MstSNohinExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_S_NOHIN
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKeySelective(MstSNohin record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_S_NOHIN
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKey(MstSNohin record);
}