package jp.co.daitoku_sh.dfcm.common.db.mapper;

import java.util.List;
import jp.co.daitoku_sh.dfcm.common.db.model.MstSSeijgyo;
import jp.co.daitoku_sh.dfcm.common.db.model.MstSSeijgyoExample;
import jp.co.daitoku_sh.dfcm.common.db.model.MstSSeijgyoKey;
import org.apache.ibatis.annotations.Param;

public interface MstSSeijgyoMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_S_SEIJGYO
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int countByExample(MstSSeijgyoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_S_SEIJGYO
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByExample(MstSSeijgyoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_S_SEIJGYO
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByPrimaryKey(MstSSeijgyoKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_S_SEIJGYO
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insert(MstSSeijgyo record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_S_SEIJGYO
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insertSelective(MstSSeijgyo record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_S_SEIJGYO
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  List<MstSSeijgyo> selectByExample(MstSSeijgyoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_S_SEIJGYO
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  MstSSeijgyo selectByPrimaryKey(MstSSeijgyoKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_S_SEIJGYO
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExampleSelective(@Param("record") MstSSeijgyo record,
      @Param("example") MstSSeijgyoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_S_SEIJGYO
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExample(@Param("record") MstSSeijgyo record,
      @Param("example") MstSSeijgyoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_S_SEIJGYO
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKeySelective(MstSSeijgyo record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_S_SEIJGYO
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKey(MstSSeijgyo record);
}