package jp.co.daitoku_sh.dfcm.common.db.mapper;

import java.util.List;
import jp.co.daitoku_sh.dfcm.common.db.model.MstShop;
import jp.co.daitoku_sh.dfcm.common.db.model.MstShopExample;
import jp.co.daitoku_sh.dfcm.common.db.model.MstShopKey;
import org.apache.ibatis.annotations.Param;

public interface MstShopMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_SHOP
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int countByExample(MstShopExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_SHOP
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByExample(MstShopExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_SHOP
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByPrimaryKey(MstShopKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_SHOP
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insert(MstShop record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_SHOP
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insertSelective(MstShop record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_SHOP
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  List<MstShop> selectByExample(MstShopExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_SHOP
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  MstShop selectByPrimaryKey(MstShopKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_SHOP
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExampleSelective(@Param("record") MstShop record,
      @Param("example") MstShopExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_SHOP
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExample(@Param("record") MstShop record,
      @Param("example") MstShopExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_SHOP
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKeySelective(MstShop record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_SHOP
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKey(MstShop record);
}