package jp.co.daitoku_sh.dfcm.common.db.mapper;

import java.util.List;
import jp.co.daitoku_sh.dfcm.common.db.model.MstSubjectFc;
import jp.co.daitoku_sh.dfcm.common.db.model.MstSubjectFcExample;
import jp.co.daitoku_sh.dfcm.common.db.model.MstSubjectFcKey;
import org.apache.ibatis.annotations.Param;

public interface MstSubjectFcMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_SUBJECT_FC
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int countByExample(MstSubjectFcExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_SUBJECT_FC
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByExample(MstSubjectFcExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_SUBJECT_FC
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByPrimaryKey(MstSubjectFcKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_SUBJECT_FC
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insert(MstSubjectFc record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_SUBJECT_FC
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insertSelective(MstSubjectFc record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_SUBJECT_FC
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  List<MstSubjectFc> selectByExample(MstSubjectFcExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_SUBJECT_FC
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  MstSubjectFc selectByPrimaryKey(MstSubjectFcKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_SUBJECT_FC
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExampleSelective(@Param("record") MstSubjectFc record,
      @Param("example") MstSubjectFcExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_SUBJECT_FC
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExample(@Param("record") MstSubjectFc record,
      @Param("example") MstSubjectFcExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_SUBJECT_FC
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKeySelective(MstSubjectFc record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_SUBJECT_FC
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKey(MstSubjectFc record);
}