package jp.co.daitoku_sh.dfcm.common.db.mapper;

import java.util.List;
import jp.co.daitoku_sh.dfcm.common.db.model.MstTransbox;
import jp.co.daitoku_sh.dfcm.common.db.model.MstTransboxExample;
import jp.co.daitoku_sh.dfcm.common.db.model.MstTransboxKey;
import org.apache.ibatis.annotations.Param;

public interface MstTransboxMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_TRANSBOX
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int countByExample(MstTransboxExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_TRANSBOX
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByExample(MstTransboxExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_TRANSBOX
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByPrimaryKey(MstTransboxKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_TRANSBOX
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insert(MstTransbox record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_TRANSBOX
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insertSelective(MstTransbox record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_TRANSBOX
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  List<MstTransbox> selectByExample(MstTransboxExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_TRANSBOX
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  MstTransbox selectByPrimaryKey(MstTransboxKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_TRANSBOX
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExampleSelective(@Param("record") MstTransbox record,
      @Param("example") MstTransboxExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_TRANSBOX
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExample(@Param("record") MstTransbox record,
      @Param("example") MstTransboxExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_TRANSBOX
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKeySelective(MstTransbox record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_TRANSBOX
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKey(MstTransbox record);
}