package jp.co.daitoku_sh.dfcm.common.db.mapper;

import java.util.List;
import jp.co.daitoku_sh.dfcm.common.db.model.TblGet01JigConfirm;
import jp.co.daitoku_sh.dfcm.common.db.model.TblGet01JigConfirmExample;
import org.apache.ibatis.annotations.Param;

public interface TblGet01JigConfirmMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_GET01_JIG_CONFIRM
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int countByExample(TblGet01JigConfirmExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_GET01_JIG_CONFIRM
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByExample(TblGet01JigConfirmExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_GET01_JIG_CONFIRM
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByPrimaryKey(String jigyoCode);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_GET01_JIG_CONFIRM
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insert(TblGet01JigConfirm record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_GET01_JIG_CONFIRM
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insertSelective(TblGet01JigConfirm record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_GET01_JIG_CONFIRM
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  List<TblGet01JigConfirm> selectByExample(TblGet01JigConfirmExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_GET01_JIG_CONFIRM
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  TblGet01JigConfirm selectByPrimaryKey(String jigyoCode);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_GET01_JIG_CONFIRM
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExampleSelective(@Param("record") TblGet01JigConfirm record,
      @Param("example") TblGet01JigConfirmExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_GET01_JIG_CONFIRM
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExample(@Param("record") TblGet01JigConfirm record,
      @Param("example") TblGet01JigConfirmExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_GET01_JIG_CONFIRM
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKeySelective(TblGet01JigConfirm record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_GET01_JIG_CONFIRM
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKey(TblGet01JigConfirm record);
}