package jp.co.daitoku_sh.dfcm.common.db.mapper;

import java.util.List;
import jp.co.daitoku_sh.dfcm.common.db.model.TblJuc01Head;
import jp.co.daitoku_sh.dfcm.common.db.model.TblJuc01HeadExample;
import jp.co.daitoku_sh.dfcm.common.db.model.TblJuc01HeadKey;
import org.apache.ibatis.annotations.Param;

public interface TblJuc01HeadMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_JUC01_HEAD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int countByExample(TblJuc01HeadExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_JUC01_HEAD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByExample(TblJuc01HeadExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_JUC01_HEAD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByPrimaryKey(TblJuc01HeadKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_JUC01_HEAD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insert(TblJuc01Head record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_JUC01_HEAD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insertSelective(TblJuc01Head record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_JUC01_HEAD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  List<TblJuc01Head> selectByExample(TblJuc01HeadExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_JUC01_HEAD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  TblJuc01Head selectByPrimaryKey(TblJuc01HeadKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_JUC01_HEAD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExampleSelective(@Param("record") TblJuc01Head record,
      @Param("example") TblJuc01HeadExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_JUC01_HEAD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExample(@Param("record") TblJuc01Head record,
      @Param("example") TblJuc01HeadExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_JUC01_HEAD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKeySelective(TblJuc01Head record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_JUC01_HEAD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKey(TblJuc01Head record);
}