package jp.co.daitoku_sh.dfcm.common.db.mapper;

import java.util.List;
import jp.co.daitoku_sh.dfcm.common.db.model.TblJuc01Body;
import jp.co.daitoku_sh.dfcm.common.db.model.TblJuc01BodyExample;
import jp.co.daitoku_sh.dfcm.common.db.model.TblJuc01BodyKey;
import org.apache.ibatis.annotations.Param;

public interface TblJuc01BodyMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_JUC01_BODY
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int countByExample(TblJuc01BodyExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_JUC01_BODY
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByExample(TblJuc01BodyExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_JUC01_BODY
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByPrimaryKey(TblJuc01BodyKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_JUC01_BODY
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insert(TblJuc01Body record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_JUC01_BODY
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insertSelective(TblJuc01Body record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_JUC01_BODY
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  List<TblJuc01Body> selectByExample(TblJuc01BodyExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_JUC01_BODY
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  TblJuc01Body selectByPrimaryKey(TblJuc01BodyKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_JUC01_BODY
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExampleSelective(@Param("record") TblJuc01Body record,
      @Param("example") TblJuc01BodyExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_JUC01_BODY
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExample(@Param("record") TblJuc01Body record,
      @Param("example") TblJuc01BodyExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_JUC01_BODY
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKeySelective(TblJuc01Body record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_JUC01_BODY
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKey(TblJuc01Body record);
}