package jp.co.daitoku_sh.dfcm.common.db.mapper;

import java.util.List;
import jp.co.daitoku_sh.dfcm.common.db.model.TblJuc01ProductMgrIf;
import jp.co.daitoku_sh.dfcm.common.db.model.TblJuc01ProductMgrIfExample;
import org.apache.ibatis.annotations.Param;

public interface TblJuc01ProductMgrIfMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_JUC01_PRODUCT_MGR_IF
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int countByExample(TblJuc01ProductMgrIfExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_JUC01_PRODUCT_MGR_IF
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByExample(TblJuc01ProductMgrIfExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_JUC01_PRODUCT_MGR_IF
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insert(TblJuc01ProductMgrIf record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_JUC01_PRODUCT_MGR_IF
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insertSelective(TblJuc01ProductMgrIf record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_JUC01_PRODUCT_MGR_IF
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  List<TblJuc01ProductMgrIf> selectByExample(
      TblJuc01ProductMgrIfExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_JUC01_PRODUCT_MGR_IF
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExampleSelective(@Param("record") TblJuc01ProductMgrIf record,
      @Param("example") TblJuc01ProductMgrIfExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_JUC01_PRODUCT_MGR_IF
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExample(@Param("record") TblJuc01ProductMgrIf record,
      @Param("example") TblJuc01ProductMgrIfExample example);
}