package jp.co.daitoku_sh.dfcm.common.db.mapper;

import java.util.List;
import jp.co.daitoku_sh.dfcm.common.db.model.TblNyu01Head;
import jp.co.daitoku_sh.dfcm.common.db.model.TblNyu01HeadExample;
import org.apache.ibatis.annotations.Param;

public interface TblNyu01HeadMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_HEAD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int countByExample(TblNyu01HeadExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_HEAD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByExample(TblNyu01HeadExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_HEAD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByPrimaryKey(Long nyuDenNo);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_HEAD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insert(TblNyu01Head record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_HEAD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insertSelective(TblNyu01Head record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_HEAD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  List<TblNyu01Head> selectByExample(TblNyu01HeadExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_HEAD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  TblNyu01Head selectByPrimaryKey(Long nyuDenNo);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_HEAD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExampleSelective(@Param("record") TblNyu01Head record,
      @Param("example") TblNyu01HeadExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_HEAD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExample(@Param("record") TblNyu01Head record,
      @Param("example") TblNyu01HeadExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_HEAD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKeySelective(TblNyu01Head record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_HEAD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKey(TblNyu01Head record);
}