package jp.co.daitoku_sh.dfcm.common.db.mapper;

import java.util.List;
import jp.co.daitoku_sh.dfcm.common.db.model.TblNyu01KaikeiRenkeiRireki;
import jp.co.daitoku_sh.dfcm.common.db.model.TblNyu01KaikeiRenkeiRirekiExample;
import org.apache.ibatis.annotations.Param;

public interface TblNyu01KaikeiRenkeiRirekiMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_KAIKEI_RENKEI_RIREKI
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int countByExample(TblNyu01KaikeiRenkeiRirekiExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_KAIKEI_RENKEI_RIREKI
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByExample(TblNyu01KaikeiRenkeiRirekiExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_KAIKEI_RENKEI_RIREKI
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByPrimaryKey(Long kaikeiRenkeiId);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_KAIKEI_RENKEI_RIREKI
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insert(TblNyu01KaikeiRenkeiRireki record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_KAIKEI_RENKEI_RIREKI
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insertSelective(TblNyu01KaikeiRenkeiRireki record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_KAIKEI_RENKEI_RIREKI
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  List<TblNyu01KaikeiRenkeiRireki> selectByExample(
      TblNyu01KaikeiRenkeiRirekiExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_KAIKEI_RENKEI_RIREKI
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  TblNyu01KaikeiRenkeiRireki selectByPrimaryKey(Long kaikeiRenkeiId);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_KAIKEI_RENKEI_RIREKI
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExampleSelective(
      @Param("record") TblNyu01KaikeiRenkeiRireki record,
      @Param("example") TblNyu01KaikeiRenkeiRirekiExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_KAIKEI_RENKEI_RIREKI
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExample(@Param("record") TblNyu01KaikeiRenkeiRireki record,
      @Param("example") TblNyu01KaikeiRenkeiRirekiExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_KAIKEI_RENKEI_RIREKI
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKeySelective(TblNyu01KaikeiRenkeiRireki record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_KAIKEI_RENKEI_RIREKI
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKey(TblNyu01KaikeiRenkeiRireki record);
}