package jp.co.daitoku_sh.dfcm.common.db.mapper;

import java.util.List;
import jp.co.daitoku_sh.dfcm.common.db.model.TblNyu01RcvPaynote;
import jp.co.daitoku_sh.dfcm.common.db.model.TblNyu01RcvPaynoteExample;
import org.apache.ibatis.annotations.Param;

public interface TblNyu01RcvPaynoteMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_RCV_PAYNOTE
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int countByExample(TblNyu01RcvPaynoteExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_RCV_PAYNOTE
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByExample(TblNyu01RcvPaynoteExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_RCV_PAYNOTE
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByPrimaryKey(String aplYmd);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_RCV_PAYNOTE
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insert(TblNyu01RcvPaynote record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_RCV_PAYNOTE
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insertSelective(TblNyu01RcvPaynote record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_RCV_PAYNOTE
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  List<TblNyu01RcvPaynote> selectByExample(TblNyu01RcvPaynoteExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_RCV_PAYNOTE
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  TblNyu01RcvPaynote selectByPrimaryKey(String aplYmd);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_RCV_PAYNOTE
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExampleSelective(@Param("record") TblNyu01RcvPaynote record,
      @Param("example") TblNyu01RcvPaynoteExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_RCV_PAYNOTE
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExample(@Param("record") TblNyu01RcvPaynote record,
      @Param("example") TblNyu01RcvPaynoteExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_RCV_PAYNOTE
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKeySelective(TblNyu01RcvPaynote record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_RCV_PAYNOTE
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKey(TblNyu01RcvPaynote record);
}