package jp.co.daitoku_sh.dfcm.common.db.mapper;

import java.util.List;
import jp.co.daitoku_sh.dfcm.common.db.model.TblNyu01Bill;
import jp.co.daitoku_sh.dfcm.common.db.model.TblNyu01BillExample;
import org.apache.ibatis.annotations.Param;

public interface TblNyu01BillMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_BILL
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int countByExample(TblNyu01BillExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_BILL
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByExample(TblNyu01BillExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_BILL
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByPrimaryKey(Long tegataId);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_BILL
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insert(TblNyu01Bill record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_BILL
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insertSelective(TblNyu01Bill record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_BILL
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  List<TblNyu01Bill> selectByExample(TblNyu01BillExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_BILL
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  TblNyu01Bill selectByPrimaryKey(Long tegataId);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_BILL
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExampleSelective(@Param("record") TblNyu01Bill record,
      @Param("example") TblNyu01BillExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_BILL
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExample(@Param("record") TblNyu01Bill record,
      @Param("example") TblNyu01BillExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_BILL
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKeySelective(TblNyu01Bill record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_NYU01_BILL
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKey(TblNyu01Bill record);
}