package jp.co.daitoku_sh.dfcm.common.db.mapper;

import java.util.List;
import jp.co.daitoku_sh.dfcm.common.db.model.TblSei01SeiBody;
import jp.co.daitoku_sh.dfcm.common.db.model.TblSei01SeiBodyExample;
import jp.co.daitoku_sh.dfcm.common.db.model.TblSei01SeiBodyKey;
import org.apache.ibatis.annotations.Param;

public interface TblSei01SeiBodyMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_SEI_BODY
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int countByExample(TblSei01SeiBodyExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_SEI_BODY
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByExample(TblSei01SeiBodyExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_SEI_BODY
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByPrimaryKey(TblSei01SeiBodyKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_SEI_BODY
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insert(TblSei01SeiBody record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_SEI_BODY
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insertSelective(TblSei01SeiBody record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_SEI_BODY
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  List<TblSei01SeiBody> selectByExample(TblSei01SeiBodyExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_SEI_BODY
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  TblSei01SeiBody selectByPrimaryKey(TblSei01SeiBodyKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_SEI_BODY
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExampleSelective(@Param("record") TblSei01SeiBody record,
      @Param("example") TblSei01SeiBodyExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_SEI_BODY
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExample(@Param("record") TblSei01SeiBody record,
      @Param("example") TblSei01SeiBodyExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_SEI_BODY
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKeySelective(TblSei01SeiBody record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_SEI_BODY
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKey(TblSei01SeiBody record);
}