package jp.co.daitoku_sh.dfcm.common.db.mapper;

import java.util.List;
import jp.co.daitoku_sh.dfcm.common.db.model.TblSei01Head;
import jp.co.daitoku_sh.dfcm.common.db.model.TblSei01HeadExample;
import org.apache.ibatis.annotations.Param;

public interface TblSei01HeadMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_HEAD
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  int countByExample(TblSei01HeadExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_HEAD
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  int deleteByExample(TblSei01HeadExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_HEAD
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  int deleteByPrimaryKey(Long bildId);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_HEAD
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  int insert(TblSei01Head record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_HEAD
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  int insertSelective(TblSei01Head record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_HEAD
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  List<TblSei01Head> selectByExample(TblSei01HeadExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_HEAD
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  TblSei01Head selectByPrimaryKey(Long bildId);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_HEAD
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  int updateByExampleSelective(@Param("record") TblSei01Head record,
      @Param("example") TblSei01HeadExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_HEAD
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  int updateByExample(@Param("record") TblSei01Head record,
      @Param("example") TblSei01HeadExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_HEAD
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  int updateByPrimaryKeySelective(TblSei01Head record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_HEAD
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  int updateByPrimaryKey(TblSei01Head record);
}