package jp.co.daitoku_sh.dfcm.common.db.mapper;

import java.util.List;
import jp.co.daitoku_sh.dfcm.common.db.model.TblSei01MshBody;
import jp.co.daitoku_sh.dfcm.common.db.model.TblSei01MshBodyExample;
import org.apache.ibatis.annotations.Param;

public interface TblSei01MshBodyMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_MSH_BODY
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int countByExample(TblSei01MshBodyExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_MSH_BODY
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByExample(TblSei01MshBodyExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_MSH_BODY
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByPrimaryKey(Long mishuNo);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_MSH_BODY
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insert(TblSei01MshBody record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_MSH_BODY
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insertSelective(TblSei01MshBody record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_MSH_BODY
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  List<TblSei01MshBody> selectByExample(TblSei01MshBodyExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_MSH_BODY
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  TblSei01MshBody selectByPrimaryKey(Long mishuNo);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_MSH_BODY
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExampleSelective(@Param("record") TblSei01MshBody record,
      @Param("example") TblSei01MshBodyExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_MSH_BODY
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExample(@Param("record") TblSei01MshBody record,
      @Param("example") TblSei01MshBodyExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_MSH_BODY
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKeySelective(TblSei01MshBody record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_MSH_BODY
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKey(TblSei01MshBody record);
}