package jp.co.daitoku_sh.dfcm.common.db.mapper;

import java.util.List;
import jp.co.daitoku_sh.dfcm.common.db.model.TblSei01UrkMshMonth;
import jp.co.daitoku_sh.dfcm.common.db.model.TblSei01UrkMshMonthExample;
import jp.co.daitoku_sh.dfcm.common.db.model.TblSei01UrkMshMonthKey;
import org.apache.ibatis.annotations.Param;

public interface TblSei01UrkMshMonthMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_URK_MSH_MONTH
   * @mbggenerated  Thu Oct 08 16:04:14 ICT 2015
   */
  int countByExample(TblSei01UrkMshMonthExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_URK_MSH_MONTH
   * @mbggenerated  Thu Oct 08 16:04:14 ICT 2015
   */
  int deleteByExample(TblSei01UrkMshMonthExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_URK_MSH_MONTH
   * @mbggenerated  Thu Oct 08 16:04:14 ICT 2015
   */
  int deleteByPrimaryKey(TblSei01UrkMshMonthKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_URK_MSH_MONTH
   * @mbggenerated  Thu Oct 08 16:04:14 ICT 2015
   */
  int insert(TblSei01UrkMshMonth record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_URK_MSH_MONTH
   * @mbggenerated  Thu Oct 08 16:04:14 ICT 2015
   */
  int insertSelective(TblSei01UrkMshMonth record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_URK_MSH_MONTH
   * @mbggenerated  Thu Oct 08 16:04:14 ICT 2015
   */
  List<TblSei01UrkMshMonth> selectByExample(TblSei01UrkMshMonthExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_URK_MSH_MONTH
   * @mbggenerated  Thu Oct 08 16:04:14 ICT 2015
   */
  TblSei01UrkMshMonth selectByPrimaryKey(TblSei01UrkMshMonthKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_URK_MSH_MONTH
   * @mbggenerated  Thu Oct 08 16:04:14 ICT 2015
   */
  int updateByExampleSelective(@Param("record") TblSei01UrkMshMonth record,
      @Param("example") TblSei01UrkMshMonthExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_URK_MSH_MONTH
   * @mbggenerated  Thu Oct 08 16:04:14 ICT 2015
   */
  int updateByExample(@Param("record") TblSei01UrkMshMonth record,
      @Param("example") TblSei01UrkMshMonthExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_URK_MSH_MONTH
   * @mbggenerated  Thu Oct 08 16:04:14 ICT 2015
   */
  int updateByPrimaryKeySelective(TblSei01UrkMshMonth record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_SEI01_URK_MSH_MONTH
   * @mbggenerated  Thu Oct 08 16:04:14 ICT 2015
   */
  int updateByPrimaryKey(TblSei01UrkMshMonth record);
}