package jp.co.daitoku_sh.dfcm.common.db.mapper;

import java.util.List;
import jp.co.daitoku_sh.dfcm.common.db.model.TblUri01Head;
import jp.co.daitoku_sh.dfcm.common.db.model.TblUri01HeadExample;
import jp.co.daitoku_sh.dfcm.common.db.model.TblUri01HeadKey;
import org.apache.ibatis.annotations.Param;

public interface TblUri01HeadMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_URI01_HEAD
   * @mbggenerated  Fri Nov 20 18:18:24 ICT 2015
   */
  int countByExample(TblUri01HeadExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_URI01_HEAD
   * @mbggenerated  Fri Nov 20 18:18:24 ICT 2015
   */
  int deleteByExample(TblUri01HeadExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_URI01_HEAD
   * @mbggenerated  Fri Nov 20 18:18:24 ICT 2015
   */
  int deleteByPrimaryKey(TblUri01HeadKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_URI01_HEAD
   * @mbggenerated  Fri Nov 20 18:18:24 ICT 2015
   */
  int insert(TblUri01Head record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_URI01_HEAD
   * @mbggenerated  Fri Nov 20 18:18:24 ICT 2015
   */
  int insertSelective(TblUri01Head record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_URI01_HEAD
   * @mbggenerated  Fri Nov 20 18:18:24 ICT 2015
   */
  List<TblUri01Head> selectByExample(TblUri01HeadExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_URI01_HEAD
   * @mbggenerated  Fri Nov 20 18:18:24 ICT 2015
   */
  TblUri01Head selectByPrimaryKey(TblUri01HeadKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_URI01_HEAD
   * @mbggenerated  Fri Nov 20 18:18:24 ICT 2015
   */
  int updateByExampleSelective(@Param("record") TblUri01Head record,
      @Param("example") TblUri01HeadExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_URI01_HEAD
   * @mbggenerated  Fri Nov 20 18:18:24 ICT 2015
   */
  int updateByExample(@Param("record") TblUri01Head record,
      @Param("example") TblUri01HeadExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_URI01_HEAD
   * @mbggenerated  Fri Nov 20 18:18:24 ICT 2015
   */
  int updateByPrimaryKeySelective(TblUri01Head record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_URI01_HEAD
   * @mbggenerated  Fri Nov 20 18:18:24 ICT 2015
   */
  int updateByPrimaryKey(TblUri01Head record);
}