package jp.co.daitoku_sh.dfcm.common.db.mapper;

import java.util.List;
import jp.co.daitoku_sh.dfcm.common.db.model.TblUri01Body;
import jp.co.daitoku_sh.dfcm.common.db.model.TblUri01BodyExample;
import jp.co.daitoku_sh.dfcm.common.db.model.TblUri01BodyKey;
import org.apache.ibatis.annotations.Param;

public interface TblUri01BodyMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_URI01_BODY
   * @mbggenerated  Fri Nov 20 18:31:17 ICT 2015
   */
  int countByExample(TblUri01BodyExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_URI01_BODY
   * @mbggenerated  Fri Nov 20 18:31:17 ICT 2015
   */
  int deleteByExample(TblUri01BodyExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_URI01_BODY
   * @mbggenerated  Fri Nov 20 18:31:17 ICT 2015
   */
  int deleteByPrimaryKey(TblUri01BodyKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_URI01_BODY
   * @mbggenerated  Fri Nov 20 18:31:17 ICT 2015
   */
  int insert(TblUri01Body record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_URI01_BODY
   * @mbggenerated  Fri Nov 20 18:31:17 ICT 2015
   */
  int insertSelective(TblUri01Body record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_URI01_BODY
   * @mbggenerated  Fri Nov 20 18:31:17 ICT 2015
   */
  List<TblUri01Body> selectByExample(TblUri01BodyExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_URI01_BODY
   * @mbggenerated  Fri Nov 20 18:31:17 ICT 2015
   */
  TblUri01Body selectByPrimaryKey(TblUri01BodyKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_URI01_BODY
   * @mbggenerated  Fri Nov 20 18:31:17 ICT 2015
   */
  int updateByExampleSelective(@Param("record") TblUri01Body record,
      @Param("example") TblUri01BodyExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_URI01_BODY
   * @mbggenerated  Fri Nov 20 18:31:17 ICT 2015
   */
  int updateByExample(@Param("record") TblUri01Body record,
      @Param("example") TblUri01BodyExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_URI01_BODY
   * @mbggenerated  Fri Nov 20 18:31:17 ICT 2015
   */
  int updateByPrimaryKeySelective(TblUri01Body record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_URI01_BODY
   * @mbggenerated  Fri Nov 20 18:31:17 ICT 2015
   */
  int updateByPrimaryKey(TblUri01Body record);
}