package jp.co.daitoku_sh.dfcm.common.db.mapper;

import java.util.List;
import jp.co.daitoku_sh.dfcm.common.db.model.TblUri01Tsyusi;
import jp.co.daitoku_sh.dfcm.common.db.model.TblUri01TsyusiExample;
import jp.co.daitoku_sh.dfcm.common.db.model.TblUri01TsyusiKey;
import org.apache.ibatis.annotations.Param;

public interface TblUri01TsyusiMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_URI01_TSYUSI
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int countByExample(TblUri01TsyusiExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_URI01_TSYUSI
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByExample(TblUri01TsyusiExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_URI01_TSYUSI
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByPrimaryKey(TblUri01TsyusiKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_URI01_TSYUSI
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insert(TblUri01Tsyusi record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_URI01_TSYUSI
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insertSelective(TblUri01Tsyusi record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_URI01_TSYUSI
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  List<TblUri01Tsyusi> selectByExample(TblUri01TsyusiExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_URI01_TSYUSI
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  TblUri01Tsyusi selectByPrimaryKey(TblUri01TsyusiKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_URI01_TSYUSI
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExampleSelective(@Param("record") TblUri01Tsyusi record,
      @Param("example") TblUri01TsyusiExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_URI01_TSYUSI
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExample(@Param("record") TblUri01Tsyusi record,
      @Param("example") TblUri01TsyusiExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_URI01_TSYUSI
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKeySelective(TblUri01Tsyusi record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table TBL_URI01_TSYUSI
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKey(TblUri01Tsyusi record);
}