package jp.co.daitoku_sh.dfcm.common.db.mapper;

import java.util.List;
import jp.co.daitoku_sh.dfcm.common.db.model.WrkJuc01Olrcv;
import jp.co.daitoku_sh.dfcm.common.db.model.WrkJuc01OlrcvExample;
import jp.co.daitoku_sh.dfcm.common.db.model.WrkJuc01OlrcvKey;
import org.apache.ibatis.annotations.Param;

public interface WrkJuc01OlrcvMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table WRK_JUC01_OLRCV
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int countByExample(WrkJuc01OlrcvExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table WRK_JUC01_OLRCV
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByExample(WrkJuc01OlrcvExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table WRK_JUC01_OLRCV
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int deleteByPrimaryKey(WrkJuc01OlrcvKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table WRK_JUC01_OLRCV
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insert(WrkJuc01Olrcv record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table WRK_JUC01_OLRCV
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int insertSelective(WrkJuc01Olrcv record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table WRK_JUC01_OLRCV
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  List<WrkJuc01Olrcv> selectByExample(WrkJuc01OlrcvExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table WRK_JUC01_OLRCV
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  WrkJuc01Olrcv selectByPrimaryKey(WrkJuc01OlrcvKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table WRK_JUC01_OLRCV
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExampleSelective(@Param("record") WrkJuc01Olrcv record,
      @Param("example") WrkJuc01OlrcvExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table WRK_JUC01_OLRCV
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByExample(@Param("record") WrkJuc01Olrcv record,
      @Param("example") WrkJuc01OlrcvExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table WRK_JUC01_OLRCV
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKeySelective(WrkJuc01Olrcv record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table WRK_JUC01_OLRCV
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  int updateByPrimaryKey(WrkJuc01Olrcv record);
}