package jp.co.daitoku_sh.dfcm.common.db.model;

public class MstCustjgyo extends MstCustjgyoKey {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_CUSTJGYO.Eg_Tan_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String egTanCode;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_CUSTJGYO.Jm_Tan_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String jmTanCode;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_CUSTJGYO.Snd_Flg
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String sndFlg;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_CUSTJGYO.INS_USERID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String insUserid;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_CUSTJGYO.INS_PGID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String insPgid;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_CUSTJGYO.INS_YMD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String insYmd;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_CUSTJGYO.INS_TIME
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String insTime;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_CUSTJGYO.UPD_USERID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String updUserid;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_CUSTJGYO.UPD_PGID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String updPgid;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_CUSTJGYO.UPD_YMD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String updYmd;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_CUSTJGYO.UPD_TIME
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String updTime;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_CUSTJGYO.Eg_Tan_Code
   * @return  the value of MST_CUSTJGYO.Eg_Tan_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getEgTanCode() {
    return egTanCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_CUSTJGYO.Eg_Tan_Code
   * @param egTanCode  the value for MST_CUSTJGYO.Eg_Tan_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setEgTanCode(String egTanCode) {
    this.egTanCode = egTanCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_CUSTJGYO.Jm_Tan_Code
   * @return  the value of MST_CUSTJGYO.Jm_Tan_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getJmTanCode() {
    return jmTanCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_CUSTJGYO.Jm_Tan_Code
   * @param jmTanCode  the value for MST_CUSTJGYO.Jm_Tan_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setJmTanCode(String jmTanCode) {
    this.jmTanCode = jmTanCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_CUSTJGYO.Snd_Flg
   * @return  the value of MST_CUSTJGYO.Snd_Flg
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getSndFlg() {
    return sndFlg;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_CUSTJGYO.Snd_Flg
   * @param sndFlg  the value for MST_CUSTJGYO.Snd_Flg
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setSndFlg(String sndFlg) {
    this.sndFlg = sndFlg;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_CUSTJGYO.INS_USERID
   * @return  the value of MST_CUSTJGYO.INS_USERID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getInsUserid() {
    return insUserid;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_CUSTJGYO.INS_USERID
   * @param insUserid  the value for MST_CUSTJGYO.INS_USERID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setInsUserid(String insUserid) {
    this.insUserid = insUserid;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_CUSTJGYO.INS_PGID
   * @return  the value of MST_CUSTJGYO.INS_PGID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getInsPgid() {
    return insPgid;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_CUSTJGYO.INS_PGID
   * @param insPgid  the value for MST_CUSTJGYO.INS_PGID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setInsPgid(String insPgid) {
    this.insPgid = insPgid;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_CUSTJGYO.INS_YMD
   * @return  the value of MST_CUSTJGYO.INS_YMD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getInsYmd() {
    return insYmd;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_CUSTJGYO.INS_YMD
   * @param insYmd  the value for MST_CUSTJGYO.INS_YMD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setInsYmd(String insYmd) {
    this.insYmd = insYmd;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_CUSTJGYO.INS_TIME
   * @return  the value of MST_CUSTJGYO.INS_TIME
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getInsTime() {
    return insTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_CUSTJGYO.INS_TIME
   * @param insTime  the value for MST_CUSTJGYO.INS_TIME
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setInsTime(String insTime) {
    this.insTime = insTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_CUSTJGYO.UPD_USERID
   * @return  the value of MST_CUSTJGYO.UPD_USERID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getUpdUserid() {
    return updUserid;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_CUSTJGYO.UPD_USERID
   * @param updUserid  the value for MST_CUSTJGYO.UPD_USERID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setUpdUserid(String updUserid) {
    this.updUserid = updUserid;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_CUSTJGYO.UPD_PGID
   * @return  the value of MST_CUSTJGYO.UPD_PGID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getUpdPgid() {
    return updPgid;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_CUSTJGYO.UPD_PGID
   * @param updPgid  the value for MST_CUSTJGYO.UPD_PGID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setUpdPgid(String updPgid) {
    this.updPgid = updPgid;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_CUSTJGYO.UPD_YMD
   * @return  the value of MST_CUSTJGYO.UPD_YMD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getUpdYmd() {
    return updYmd;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_CUSTJGYO.UPD_YMD
   * @param updYmd  the value for MST_CUSTJGYO.UPD_YMD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setUpdYmd(String updYmd) {
    this.updYmd = updYmd;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_CUSTJGYO.UPD_TIME
   * @return  the value of MST_CUSTJGYO.UPD_TIME
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getUpdTime() {
    return updTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_CUSTJGYO.UPD_TIME
   * @param updTime  the value for MST_CUSTJGYO.UPD_TIME
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setUpdTime(String updTime) {
    this.updTime = updTime;
  }
}