package jp.co.daitoku_sh.dfcm.common.db.model;

import java.util.ArrayList;
import java.util.List;

public class MstCourseListExample {
    /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table MST_COURSE_LIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  protected String orderByClause;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table MST_COURSE_LIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  protected boolean distinct;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table MST_COURSE_LIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_COURSE_LIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public MstCourseListExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_COURSE_LIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_COURSE_LIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_COURSE_LIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_COURSE_LIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_COURSE_LIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_COURSE_LIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_COURSE_LIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_COURSE_LIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_COURSE_LIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_COURSE_LIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table MST_COURSE_LIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  protected abstract static class GeneratedCriteria {

    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value,
        String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2,
        String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property
            + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andJigyoCodeIsNull() {
      addCriterion("Jigyo_Code is null");
      return (Criteria) this;
    }

    public Criteria andJigyoCodeIsNotNull() {
      addCriterion("Jigyo_Code is not null");
      return (Criteria) this;
    }

    public Criteria andJigyoCodeEqualTo(String value) {
      addCriterion("Jigyo_Code =", value, "jigyoCode");
      return (Criteria) this;
    }

    public Criteria andJigyoCodeNotEqualTo(String value) {
      addCriterion("Jigyo_Code <>", value, "jigyoCode");
      return (Criteria) this;
    }

    public Criteria andJigyoCodeGreaterThan(String value) {
      addCriterion("Jigyo_Code >", value, "jigyoCode");
      return (Criteria) this;
    }

    public Criteria andJigyoCodeGreaterThanOrEqualTo(String value) {
      addCriterion("Jigyo_Code >=", value, "jigyoCode");
      return (Criteria) this;
    }

    public Criteria andJigyoCodeLessThan(String value) {
      addCriterion("Jigyo_Code <", value, "jigyoCode");
      return (Criteria) this;
    }

    public Criteria andJigyoCodeLessThanOrEqualTo(String value) {
      addCriterion("Jigyo_Code <=", value, "jigyoCode");
      return (Criteria) this;
    }

    public Criteria andJigyoCodeLike(String value) {
      addCriterion("Jigyo_Code like", value, "jigyoCode");
      return (Criteria) this;
    }

    public Criteria andJigyoCodeNotLike(String value) {
      addCriterion("Jigyo_Code not like", value, "jigyoCode");
      return (Criteria) this;
    }

    public Criteria andJigyoCodeIn(List<String> values) {
      addCriterion("Jigyo_Code in", values, "jigyoCode");
      return (Criteria) this;
    }

    public Criteria andJigyoCodeNotIn(List<String> values) {
      addCriterion("Jigyo_Code not in", values, "jigyoCode");
      return (Criteria) this;
    }

    public Criteria andJigyoCodeBetween(String value1, String value2) {
      addCriterion("Jigyo_Code between", value1, value2, "jigyoCode");
      return (Criteria) this;
    }

    public Criteria andJigyoCodeNotBetween(String value1, String value2) {
      addCriterion("Jigyo_Code not between", value1, value2, "jigyoCode");
      return (Criteria) this;
    }

    public Criteria andCosCodeIsNull() {
      addCriterion("Cos_Code is null");
      return (Criteria) this;
    }

    public Criteria andCosCodeIsNotNull() {
      addCriterion("Cos_Code is not null");
      return (Criteria) this;
    }

    public Criteria andCosCodeEqualTo(String value) {
      addCriterion("Cos_Code =", value, "cosCode");
      return (Criteria) this;
    }

    public Criteria andCosCodeNotEqualTo(String value) {
      addCriterion("Cos_Code <>", value, "cosCode");
      return (Criteria) this;
    }

    public Criteria andCosCodeGreaterThan(String value) {
      addCriterion("Cos_Code >", value, "cosCode");
      return (Criteria) this;
    }

    public Criteria andCosCodeGreaterThanOrEqualTo(String value) {
      addCriterion("Cos_Code >=", value, "cosCode");
      return (Criteria) this;
    }

    public Criteria andCosCodeLessThan(String value) {
      addCriterion("Cos_Code <", value, "cosCode");
      return (Criteria) this;
    }

    public Criteria andCosCodeLessThanOrEqualTo(String value) {
      addCriterion("Cos_Code <=", value, "cosCode");
      return (Criteria) this;
    }

    public Criteria andCosCodeLike(String value) {
      addCriterion("Cos_Code like", value, "cosCode");
      return (Criteria) this;
    }

    public Criteria andCosCodeNotLike(String value) {
      addCriterion("Cos_Code not like", value, "cosCode");
      return (Criteria) this;
    }

    public Criteria andCosCodeIn(List<String> values) {
      addCriterion("Cos_Code in", values, "cosCode");
      return (Criteria) this;
    }

    public Criteria andCosCodeNotIn(List<String> values) {
      addCriterion("Cos_Code not in", values, "cosCode");
      return (Criteria) this;
    }

    public Criteria andCosCodeBetween(String value1, String value2) {
      addCriterion("Cos_Code between", value1, value2, "cosCode");
      return (Criteria) this;
    }

    public Criteria andCosCodeNotBetween(String value1, String value2) {
      addCriterion("Cos_Code not between", value1, value2, "cosCode");
      return (Criteria) this;
    }

    public Criteria andCustCodeIsNull() {
      addCriterion("Cust_Code is null");
      return (Criteria) this;
    }

    public Criteria andCustCodeIsNotNull() {
      addCriterion("Cust_Code is not null");
      return (Criteria) this;
    }

    public Criteria andCustCodeEqualTo(String value) {
      addCriterion("Cust_Code =", value, "custCode");
      return (Criteria) this;
    }

    public Criteria andCustCodeNotEqualTo(String value) {
      addCriterion("Cust_Code <>", value, "custCode");
      return (Criteria) this;
    }

    public Criteria andCustCodeGreaterThan(String value) {
      addCriterion("Cust_Code >", value, "custCode");
      return (Criteria) this;
    }

    public Criteria andCustCodeGreaterThanOrEqualTo(String value) {
      addCriterion("Cust_Code >=", value, "custCode");
      return (Criteria) this;
    }

    public Criteria andCustCodeLessThan(String value) {
      addCriterion("Cust_Code <", value, "custCode");
      return (Criteria) this;
    }

    public Criteria andCustCodeLessThanOrEqualTo(String value) {
      addCriterion("Cust_Code <=", value, "custCode");
      return (Criteria) this;
    }

    public Criteria andCustCodeLike(String value) {
      addCriterion("Cust_Code like", value, "custCode");
      return (Criteria) this;
    }

    public Criteria andCustCodeNotLike(String value) {
      addCriterion("Cust_Code not like", value, "custCode");
      return (Criteria) this;
    }

    public Criteria andCustCodeIn(List<String> values) {
      addCriterion("Cust_Code in", values, "custCode");
      return (Criteria) this;
    }

    public Criteria andCustCodeNotIn(List<String> values) {
      addCriterion("Cust_Code not in", values, "custCode");
      return (Criteria) this;
    }

    public Criteria andCustCodeBetween(String value1, String value2) {
      addCriterion("Cust_Code between", value1, value2, "custCode");
      return (Criteria) this;
    }

    public Criteria andCustCodeNotBetween(String value1, String value2) {
      addCriterion("Cust_Code not between", value1, value2, "custCode");
      return (Criteria) this;
    }

    public Criteria andShopCodeIsNull() {
      addCriterion("Shop_Code is null");
      return (Criteria) this;
    }

    public Criteria andShopCodeIsNotNull() {
      addCriterion("Shop_Code is not null");
      return (Criteria) this;
    }

    public Criteria andShopCodeEqualTo(String value) {
      addCriterion("Shop_Code =", value, "shopCode");
      return (Criteria) this;
    }

    public Criteria andShopCodeNotEqualTo(String value) {
      addCriterion("Shop_Code <>", value, "shopCode");
      return (Criteria) this;
    }

    public Criteria andShopCodeGreaterThan(String value) {
      addCriterion("Shop_Code >", value, "shopCode");
      return (Criteria) this;
    }

    public Criteria andShopCodeGreaterThanOrEqualTo(String value) {
      addCriterion("Shop_Code >=", value, "shopCode");
      return (Criteria) this;
    }

    public Criteria andShopCodeLessThan(String value) {
      addCriterion("Shop_Code <", value, "shopCode");
      return (Criteria) this;
    }

    public Criteria andShopCodeLessThanOrEqualTo(String value) {
      addCriterion("Shop_Code <=", value, "shopCode");
      return (Criteria) this;
    }

    public Criteria andShopCodeLike(String value) {
      addCriterion("Shop_Code like", value, "shopCode");
      return (Criteria) this;
    }

    public Criteria andShopCodeNotLike(String value) {
      addCriterion("Shop_Code not like", value, "shopCode");
      return (Criteria) this;
    }

    public Criteria andShopCodeIn(List<String> values) {
      addCriterion("Shop_Code in", values, "shopCode");
      return (Criteria) this;
    }

    public Criteria andShopCodeNotIn(List<String> values) {
      addCriterion("Shop_Code not in", values, "shopCode");
      return (Criteria) this;
    }

    public Criteria andShopCodeBetween(String value1, String value2) {
      addCriterion("Shop_Code between", value1, value2, "shopCode");
      return (Criteria) this;
    }

    public Criteria andShopCodeNotBetween(String value1, String value2) {
      addCriterion("Shop_Code not between", value1, value2, "shopCode");
      return (Criteria) this;
    }

    public Criteria andBinKbIsNull() {
      addCriterion("Bin_Kb is null");
      return (Criteria) this;
    }

    public Criteria andBinKbIsNotNull() {
      addCriterion("Bin_Kb is not null");
      return (Criteria) this;
    }

    public Criteria andBinKbEqualTo(String value) {
      addCriterion("Bin_Kb =", value, "binKb");
      return (Criteria) this;
    }

    public Criteria andBinKbNotEqualTo(String value) {
      addCriterion("Bin_Kb <>", value, "binKb");
      return (Criteria) this;
    }

    public Criteria andBinKbGreaterThan(String value) {
      addCriterion("Bin_Kb >", value, "binKb");
      return (Criteria) this;
    }

    public Criteria andBinKbGreaterThanOrEqualTo(String value) {
      addCriterion("Bin_Kb >=", value, "binKb");
      return (Criteria) this;
    }

    public Criteria andBinKbLessThan(String value) {
      addCriterion("Bin_Kb <", value, "binKb");
      return (Criteria) this;
    }

    public Criteria andBinKbLessThanOrEqualTo(String value) {
      addCriterion("Bin_Kb <=", value, "binKb");
      return (Criteria) this;
    }

    public Criteria andBinKbLike(String value) {
      addCriterion("Bin_Kb like", value, "binKb");
      return (Criteria) this;
    }

    public Criteria andBinKbNotLike(String value) {
      addCriterion("Bin_Kb not like", value, "binKb");
      return (Criteria) this;
    }

    public Criteria andBinKbIn(List<String> values) {
      addCriterion("Bin_Kb in", values, "binKb");
      return (Criteria) this;
    }

    public Criteria andBinKbNotIn(List<String> values) {
      addCriterion("Bin_Kb not in", values, "binKb");
      return (Criteria) this;
    }

    public Criteria andBinKbBetween(String value1, String value2) {
      addCriterion("Bin_Kb between", value1, value2, "binKb");
      return (Criteria) this;
    }

    public Criteria andBinKbNotBetween(String value1, String value2) {
      addCriterion("Bin_Kb not between", value1, value2, "binKb");
      return (Criteria) this;
    }

    public Criteria andDeliKbIsNull() {
      addCriterion("Deli_Kb is null");
      return (Criteria) this;
    }

    public Criteria andDeliKbIsNotNull() {
      addCriterion("Deli_Kb is not null");
      return (Criteria) this;
    }

    public Criteria andDeliKbEqualTo(String value) {
      addCriterion("Deli_Kb =", value, "deliKb");
      return (Criteria) this;
    }

    public Criteria andDeliKbNotEqualTo(String value) {
      addCriterion("Deli_Kb <>", value, "deliKb");
      return (Criteria) this;
    }

    public Criteria andDeliKbGreaterThan(String value) {
      addCriterion("Deli_Kb >", value, "deliKb");
      return (Criteria) this;
    }

    public Criteria andDeliKbGreaterThanOrEqualTo(String value) {
      addCriterion("Deli_Kb >=", value, "deliKb");
      return (Criteria) this;
    }

    public Criteria andDeliKbLessThan(String value) {
      addCriterion("Deli_Kb <", value, "deliKb");
      return (Criteria) this;
    }

    public Criteria andDeliKbLessThanOrEqualTo(String value) {
      addCriterion("Deli_Kb <=", value, "deliKb");
      return (Criteria) this;
    }

    public Criteria andDeliKbLike(String value) {
      addCriterion("Deli_Kb like", value, "deliKb");
      return (Criteria) this;
    }

    public Criteria andDeliKbNotLike(String value) {
      addCriterion("Deli_Kb not like", value, "deliKb");
      return (Criteria) this;
    }

    public Criteria andDeliKbIn(List<String> values) {
      addCriterion("Deli_Kb in", values, "deliKb");
      return (Criteria) this;
    }

    public Criteria andDeliKbNotIn(List<String> values) {
      addCriterion("Deli_Kb not in", values, "deliKb");
      return (Criteria) this;
    }

    public Criteria andDeliKbBetween(String value1, String value2) {
      addCriterion("Deli_Kb between", value1, value2, "deliKb");
      return (Criteria) this;
    }

    public Criteria andDeliKbNotBetween(String value1, String value2) {
      addCriterion("Deli_Kb not between", value1, value2, "deliKb");
      return (Criteria) this;
    }

    public Criteria andStsCodeIsNull() {
      addCriterion("STS_Code is null");
      return (Criteria) this;
    }

    public Criteria andStsCodeIsNotNull() {
      addCriterion("STS_Code is not null");
      return (Criteria) this;
    }

    public Criteria andStsCodeEqualTo(String value) {
      addCriterion("STS_Code =", value, "stsCode");
      return (Criteria) this;
    }

    public Criteria andStsCodeNotEqualTo(String value) {
      addCriterion("STS_Code <>", value, "stsCode");
      return (Criteria) this;
    }

    public Criteria andStsCodeGreaterThan(String value) {
      addCriterion("STS_Code >", value, "stsCode");
      return (Criteria) this;
    }

    public Criteria andStsCodeGreaterThanOrEqualTo(String value) {
      addCriterion("STS_Code >=", value, "stsCode");
      return (Criteria) this;
    }

    public Criteria andStsCodeLessThan(String value) {
      addCriterion("STS_Code <", value, "stsCode");
      return (Criteria) this;
    }

    public Criteria andStsCodeLessThanOrEqualTo(String value) {
      addCriterion("STS_Code <=", value, "stsCode");
      return (Criteria) this;
    }

    public Criteria andStsCodeLike(String value) {
      addCriterion("STS_Code like", value, "stsCode");
      return (Criteria) this;
    }

    public Criteria andStsCodeNotLike(String value) {
      addCriterion("STS_Code not like", value, "stsCode");
      return (Criteria) this;
    }

    public Criteria andStsCodeIn(List<String> values) {
      addCriterion("STS_Code in", values, "stsCode");
      return (Criteria) this;
    }

    public Criteria andStsCodeNotIn(List<String> values) {
      addCriterion("STS_Code not in", values, "stsCode");
      return (Criteria) this;
    }

    public Criteria andStsCodeBetween(String value1, String value2) {
      addCriterion("STS_Code between", value1, value2, "stsCode");
      return (Criteria) this;
    }

    public Criteria andStsCodeNotBetween(String value1, String value2) {
      addCriterion("STS_Code not between", value1, value2, "stsCode");
      return (Criteria) this;
    }

    public Criteria andInsUseridIsNull() {
      addCriterion("INS_USERID is null");
      return (Criteria) this;
    }

    public Criteria andInsUseridIsNotNull() {
      addCriterion("INS_USERID is not null");
      return (Criteria) this;
    }

    public Criteria andInsUseridEqualTo(String value) {
      addCriterion("INS_USERID =", value, "insUserid");
      return (Criteria) this;
    }

    public Criteria andInsUseridNotEqualTo(String value) {
      addCriterion("INS_USERID <>", value, "insUserid");
      return (Criteria) this;
    }

    public Criteria andInsUseridGreaterThan(String value) {
      addCriterion("INS_USERID >", value, "insUserid");
      return (Criteria) this;
    }

    public Criteria andInsUseridGreaterThanOrEqualTo(String value) {
      addCriterion("INS_USERID >=", value, "insUserid");
      return (Criteria) this;
    }

    public Criteria andInsUseridLessThan(String value) {
      addCriterion("INS_USERID <", value, "insUserid");
      return (Criteria) this;
    }

    public Criteria andInsUseridLessThanOrEqualTo(String value) {
      addCriterion("INS_USERID <=", value, "insUserid");
      return (Criteria) this;
    }

    public Criteria andInsUseridLike(String value) {
      addCriterion("INS_USERID like", value, "insUserid");
      return (Criteria) this;
    }

    public Criteria andInsUseridNotLike(String value) {
      addCriterion("INS_USERID not like", value, "insUserid");
      return (Criteria) this;
    }

    public Criteria andInsUseridIn(List<String> values) {
      addCriterion("INS_USERID in", values, "insUserid");
      return (Criteria) this;
    }

    public Criteria andInsUseridNotIn(List<String> values) {
      addCriterion("INS_USERID not in", values, "insUserid");
      return (Criteria) this;
    }

    public Criteria andInsUseridBetween(String value1, String value2) {
      addCriterion("INS_USERID between", value1, value2, "insUserid");
      return (Criteria) this;
    }

    public Criteria andInsUseridNotBetween(String value1, String value2) {
      addCriterion("INS_USERID not between", value1, value2, "insUserid");
      return (Criteria) this;
    }

    public Criteria andInsPgidIsNull() {
      addCriterion("INS_PGID is null");
      return (Criteria) this;
    }

    public Criteria andInsPgidIsNotNull() {
      addCriterion("INS_PGID is not null");
      return (Criteria) this;
    }

    public Criteria andInsPgidEqualTo(String value) {
      addCriterion("INS_PGID =", value, "insPgid");
      return (Criteria) this;
    }

    public Criteria andInsPgidNotEqualTo(String value) {
      addCriterion("INS_PGID <>", value, "insPgid");
      return (Criteria) this;
    }

    public Criteria andInsPgidGreaterThan(String value) {
      addCriterion("INS_PGID >", value, "insPgid");
      return (Criteria) this;
    }

    public Criteria andInsPgidGreaterThanOrEqualTo(String value) {
      addCriterion("INS_PGID >=", value, "insPgid");
      return (Criteria) this;
    }

    public Criteria andInsPgidLessThan(String value) {
      addCriterion("INS_PGID <", value, "insPgid");
      return (Criteria) this;
    }

    public Criteria andInsPgidLessThanOrEqualTo(String value) {
      addCriterion("INS_PGID <=", value, "insPgid");
      return (Criteria) this;
    }

    public Criteria andInsPgidLike(String value) {
      addCriterion("INS_PGID like", value, "insPgid");
      return (Criteria) this;
    }

    public Criteria andInsPgidNotLike(String value) {
      addCriterion("INS_PGID not like", value, "insPgid");
      return (Criteria) this;
    }

    public Criteria andInsPgidIn(List<String> values) {
      addCriterion("INS_PGID in", values, "insPgid");
      return (Criteria) this;
    }

    public Criteria andInsPgidNotIn(List<String> values) {
      addCriterion("INS_PGID not in", values, "insPgid");
      return (Criteria) this;
    }

    public Criteria andInsPgidBetween(String value1, String value2) {
      addCriterion("INS_PGID between", value1, value2, "insPgid");
      return (Criteria) this;
    }

    public Criteria andInsPgidNotBetween(String value1, String value2) {
      addCriterion("INS_PGID not between", value1, value2, "insPgid");
      return (Criteria) this;
    }

    public Criteria andInsYmdIsNull() {
      addCriterion("INS_YMD is null");
      return (Criteria) this;
    }

    public Criteria andInsYmdIsNotNull() {
      addCriterion("INS_YMD is not null");
      return (Criteria) this;
    }

    public Criteria andInsYmdEqualTo(String value) {
      addCriterion("INS_YMD =", value, "insYmd");
      return (Criteria) this;
    }

    public Criteria andInsYmdNotEqualTo(String value) {
      addCriterion("INS_YMD <>", value, "insYmd");
      return (Criteria) this;
    }

    public Criteria andInsYmdGreaterThan(String value) {
      addCriterion("INS_YMD >", value, "insYmd");
      return (Criteria) this;
    }

    public Criteria andInsYmdGreaterThanOrEqualTo(String value) {
      addCriterion("INS_YMD >=", value, "insYmd");
      return (Criteria) this;
    }

    public Criteria andInsYmdLessThan(String value) {
      addCriterion("INS_YMD <", value, "insYmd");
      return (Criteria) this;
    }

    public Criteria andInsYmdLessThanOrEqualTo(String value) {
      addCriterion("INS_YMD <=", value, "insYmd");
      return (Criteria) this;
    }

    public Criteria andInsYmdLike(String value) {
      addCriterion("INS_YMD like", value, "insYmd");
      return (Criteria) this;
    }

    public Criteria andInsYmdNotLike(String value) {
      addCriterion("INS_YMD not like", value, "insYmd");
      return (Criteria) this;
    }

    public Criteria andInsYmdIn(List<String> values) {
      addCriterion("INS_YMD in", values, "insYmd");
      return (Criteria) this;
    }

    public Criteria andInsYmdNotIn(List<String> values) {
      addCriterion("INS_YMD not in", values, "insYmd");
      return (Criteria) this;
    }

    public Criteria andInsYmdBetween(String value1, String value2) {
      addCriterion("INS_YMD between", value1, value2, "insYmd");
      return (Criteria) this;
    }

    public Criteria andInsYmdNotBetween(String value1, String value2) {
      addCriterion("INS_YMD not between", value1, value2, "insYmd");
      return (Criteria) this;
    }

    public Criteria andInsTimeIsNull() {
      addCriterion("INS_TIME is null");
      return (Criteria) this;
    }

    public Criteria andInsTimeIsNotNull() {
      addCriterion("INS_TIME is not null");
      return (Criteria) this;
    }

    public Criteria andInsTimeEqualTo(String value) {
      addCriterion("INS_TIME =", value, "insTime");
      return (Criteria) this;
    }

    public Criteria andInsTimeNotEqualTo(String value) {
      addCriterion("INS_TIME <>", value, "insTime");
      return (Criteria) this;
    }

    public Criteria andInsTimeGreaterThan(String value) {
      addCriterion("INS_TIME >", value, "insTime");
      return (Criteria) this;
    }

    public Criteria andInsTimeGreaterThanOrEqualTo(String value) {
      addCriterion("INS_TIME >=", value, "insTime");
      return (Criteria) this;
    }

    public Criteria andInsTimeLessThan(String value) {
      addCriterion("INS_TIME <", value, "insTime");
      return (Criteria) this;
    }

    public Criteria andInsTimeLessThanOrEqualTo(String value) {
      addCriterion("INS_TIME <=", value, "insTime");
      return (Criteria) this;
    }

    public Criteria andInsTimeLike(String value) {
      addCriterion("INS_TIME like", value, "insTime");
      return (Criteria) this;
    }

    public Criteria andInsTimeNotLike(String value) {
      addCriterion("INS_TIME not like", value, "insTime");
      return (Criteria) this;
    }

    public Criteria andInsTimeIn(List<String> values) {
      addCriterion("INS_TIME in", values, "insTime");
      return (Criteria) this;
    }

    public Criteria andInsTimeNotIn(List<String> values) {
      addCriterion("INS_TIME not in", values, "insTime");
      return (Criteria) this;
    }

    public Criteria andInsTimeBetween(String value1, String value2) {
      addCriterion("INS_TIME between", value1, value2, "insTime");
      return (Criteria) this;
    }

    public Criteria andInsTimeNotBetween(String value1, String value2) {
      addCriterion("INS_TIME not between", value1, value2, "insTime");
      return (Criteria) this;
    }

    public Criteria andUpdUseridIsNull() {
      addCriterion("UPD_USERID is null");
      return (Criteria) this;
    }

    public Criteria andUpdUseridIsNotNull() {
      addCriterion("UPD_USERID is not null");
      return (Criteria) this;
    }

    public Criteria andUpdUseridEqualTo(String value) {
      addCriterion("UPD_USERID =", value, "updUserid");
      return (Criteria) this;
    }

    public Criteria andUpdUseridNotEqualTo(String value) {
      addCriterion("UPD_USERID <>", value, "updUserid");
      return (Criteria) this;
    }

    public Criteria andUpdUseridGreaterThan(String value) {
      addCriterion("UPD_USERID >", value, "updUserid");
      return (Criteria) this;
    }

    public Criteria andUpdUseridGreaterThanOrEqualTo(String value) {
      addCriterion("UPD_USERID >=", value, "updUserid");
      return (Criteria) this;
    }

    public Criteria andUpdUseridLessThan(String value) {
      addCriterion("UPD_USERID <", value, "updUserid");
      return (Criteria) this;
    }

    public Criteria andUpdUseridLessThanOrEqualTo(String value) {
      addCriterion("UPD_USERID <=", value, "updUserid");
      return (Criteria) this;
    }

    public Criteria andUpdUseridLike(String value) {
      addCriterion("UPD_USERID like", value, "updUserid");
      return (Criteria) this;
    }

    public Criteria andUpdUseridNotLike(String value) {
      addCriterion("UPD_USERID not like", value, "updUserid");
      return (Criteria) this;
    }

    public Criteria andUpdUseridIn(List<String> values) {
      addCriterion("UPD_USERID in", values, "updUserid");
      return (Criteria) this;
    }

    public Criteria andUpdUseridNotIn(List<String> values) {
      addCriterion("UPD_USERID not in", values, "updUserid");
      return (Criteria) this;
    }

    public Criteria andUpdUseridBetween(String value1, String value2) {
      addCriterion("UPD_USERID between", value1, value2, "updUserid");
      return (Criteria) this;
    }

    public Criteria andUpdUseridNotBetween(String value1, String value2) {
      addCriterion("UPD_USERID not between", value1, value2, "updUserid");
      return (Criteria) this;
    }

    public Criteria andUpdPgidIsNull() {
      addCriterion("UPD_PGID is null");
      return (Criteria) this;
    }

    public Criteria andUpdPgidIsNotNull() {
      addCriterion("UPD_PGID is not null");
      return (Criteria) this;
    }

    public Criteria andUpdPgidEqualTo(String value) {
      addCriterion("UPD_PGID =", value, "updPgid");
      return (Criteria) this;
    }

    public Criteria andUpdPgidNotEqualTo(String value) {
      addCriterion("UPD_PGID <>", value, "updPgid");
      return (Criteria) this;
    }

    public Criteria andUpdPgidGreaterThan(String value) {
      addCriterion("UPD_PGID >", value, "updPgid");
      return (Criteria) this;
    }

    public Criteria andUpdPgidGreaterThanOrEqualTo(String value) {
      addCriterion("UPD_PGID >=", value, "updPgid");
      return (Criteria) this;
    }

    public Criteria andUpdPgidLessThan(String value) {
      addCriterion("UPD_PGID <", value, "updPgid");
      return (Criteria) this;
    }

    public Criteria andUpdPgidLessThanOrEqualTo(String value) {
      addCriterion("UPD_PGID <=", value, "updPgid");
      return (Criteria) this;
    }

    public Criteria andUpdPgidLike(String value) {
      addCriterion("UPD_PGID like", value, "updPgid");
      return (Criteria) this;
    }

    public Criteria andUpdPgidNotLike(String value) {
      addCriterion("UPD_PGID not like", value, "updPgid");
      return (Criteria) this;
    }

    public Criteria andUpdPgidIn(List<String> values) {
      addCriterion("UPD_PGID in", values, "updPgid");
      return (Criteria) this;
    }

    public Criteria andUpdPgidNotIn(List<String> values) {
      addCriterion("UPD_PGID not in", values, "updPgid");
      return (Criteria) this;
    }

    public Criteria andUpdPgidBetween(String value1, String value2) {
      addCriterion("UPD_PGID between", value1, value2, "updPgid");
      return (Criteria) this;
    }

    public Criteria andUpdPgidNotBetween(String value1, String value2) {
      addCriterion("UPD_PGID not between", value1, value2, "updPgid");
      return (Criteria) this;
    }

    public Criteria andUpdYmdIsNull() {
      addCriterion("UPD_YMD is null");
      return (Criteria) this;
    }

    public Criteria andUpdYmdIsNotNull() {
      addCriterion("UPD_YMD is not null");
      return (Criteria) this;
    }

    public Criteria andUpdYmdEqualTo(String value) {
      addCriterion("UPD_YMD =", value, "updYmd");
      return (Criteria) this;
    }

    public Criteria andUpdYmdNotEqualTo(String value) {
      addCriterion("UPD_YMD <>", value, "updYmd");
      return (Criteria) this;
    }

    public Criteria andUpdYmdGreaterThan(String value) {
      addCriterion("UPD_YMD >", value, "updYmd");
      return (Criteria) this;
    }

    public Criteria andUpdYmdGreaterThanOrEqualTo(String value) {
      addCriterion("UPD_YMD >=", value, "updYmd");
      return (Criteria) this;
    }

    public Criteria andUpdYmdLessThan(String value) {
      addCriterion("UPD_YMD <", value, "updYmd");
      return (Criteria) this;
    }

    public Criteria andUpdYmdLessThanOrEqualTo(String value) {
      addCriterion("UPD_YMD <=", value, "updYmd");
      return (Criteria) this;
    }

    public Criteria andUpdYmdLike(String value) {
      addCriterion("UPD_YMD like", value, "updYmd");
      return (Criteria) this;
    }

    public Criteria andUpdYmdNotLike(String value) {
      addCriterion("UPD_YMD not like", value, "updYmd");
      return (Criteria) this;
    }

    public Criteria andUpdYmdIn(List<String> values) {
      addCriterion("UPD_YMD in", values, "updYmd");
      return (Criteria) this;
    }

    public Criteria andUpdYmdNotIn(List<String> values) {
      addCriterion("UPD_YMD not in", values, "updYmd");
      return (Criteria) this;
    }

    public Criteria andUpdYmdBetween(String value1, String value2) {
      addCriterion("UPD_YMD between", value1, value2, "updYmd");
      return (Criteria) this;
    }

    public Criteria andUpdYmdNotBetween(String value1, String value2) {
      addCriterion("UPD_YMD not between", value1, value2, "updYmd");
      return (Criteria) this;
    }

    public Criteria andUpdTimeIsNull() {
      addCriterion("UPD_TIME is null");
      return (Criteria) this;
    }

    public Criteria andUpdTimeIsNotNull() {
      addCriterion("UPD_TIME is not null");
      return (Criteria) this;
    }

    public Criteria andUpdTimeEqualTo(String value) {
      addCriterion("UPD_TIME =", value, "updTime");
      return (Criteria) this;
    }

    public Criteria andUpdTimeNotEqualTo(String value) {
      addCriterion("UPD_TIME <>", value, "updTime");
      return (Criteria) this;
    }

    public Criteria andUpdTimeGreaterThan(String value) {
      addCriterion("UPD_TIME >", value, "updTime");
      return (Criteria) this;
    }

    public Criteria andUpdTimeGreaterThanOrEqualTo(String value) {
      addCriterion("UPD_TIME >=", value, "updTime");
      return (Criteria) this;
    }

    public Criteria andUpdTimeLessThan(String value) {
      addCriterion("UPD_TIME <", value, "updTime");
      return (Criteria) this;
    }

    public Criteria andUpdTimeLessThanOrEqualTo(String value) {
      addCriterion("UPD_TIME <=", value, "updTime");
      return (Criteria) this;
    }

    public Criteria andUpdTimeLike(String value) {
      addCriterion("UPD_TIME like", value, "updTime");
      return (Criteria) this;
    }

    public Criteria andUpdTimeNotLike(String value) {
      addCriterion("UPD_TIME not like", value, "updTime");
      return (Criteria) this;
    }

    public Criteria andUpdTimeIn(List<String> values) {
      addCriterion("UPD_TIME in", values, "updTime");
      return (Criteria) this;
    }

    public Criteria andUpdTimeNotIn(List<String> values) {
      addCriterion("UPD_TIME not in", values, "updTime");
      return (Criteria) this;
    }

    public Criteria andUpdTimeBetween(String value1, String value2) {
      addCriterion("UPD_TIME between", value1, value2, "updTime");
      return (Criteria) this;
    }

    public Criteria andUpdTimeNotBetween(String value1, String value2) {
      addCriterion("UPD_TIME not between", value1, value2, "updTime");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table MST_COURSE_LIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public static class Criterion {

    private String condition;
    private Object value;
    private Object secondValue;
    private boolean noValue;
    private boolean singleValue;
    private boolean betweenValue;
    private boolean listValue;
    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue,
        String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MST_COURSE_LIST
     *
     * @mbggenerated do_not_delete_during_merge Thu Sep 17 21:03:29 JST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}