package jp.co.daitoku_sh.dfcm.common.db.model;

public class MstCorrectKb extends MstCorrectKbKey {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_CORRECT_KB.St_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String stKb;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_CORRECT_KB.Correct_Cause
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String correctCause;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_CORRECT_KB.Zero_Dlvdat_Flg
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String zeroDlvdatFlg;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_CORRECT_KB.Bikou
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String bikou;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_CORRECT_KB.STS_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String stsCode;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_CORRECT_KB.INS_USERID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String insUserid;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_CORRECT_KB.INS_PGID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String insPgid;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_CORRECT_KB.INS_YMD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String insYmd;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_CORRECT_KB.INS_TIME
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String insTime;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_CORRECT_KB.UPD_USERID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String updUserid;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_CORRECT_KB.UPD_PGID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String updPgid;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_CORRECT_KB.UPD_YMD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String updYmd;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_CORRECT_KB.UPD_TIME
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String updTime;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_CORRECT_KB.St_Kb
   * @return  the value of MST_CORRECT_KB.St_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getStKb() {
    return stKb;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_CORRECT_KB.St_Kb
   * @param stKb  the value for MST_CORRECT_KB.St_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setStKb(String stKb) {
    this.stKb = stKb;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_CORRECT_KB.Correct_Cause
   * @return  the value of MST_CORRECT_KB.Correct_Cause
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getCorrectCause() {
    return correctCause;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_CORRECT_KB.Correct_Cause
   * @param correctCause  the value for MST_CORRECT_KB.Correct_Cause
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setCorrectCause(String correctCause) {
    this.correctCause = correctCause;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_CORRECT_KB.Zero_Dlvdat_Flg
   * @return  the value of MST_CORRECT_KB.Zero_Dlvdat_Flg
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getZeroDlvdatFlg() {
    return zeroDlvdatFlg;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_CORRECT_KB.Zero_Dlvdat_Flg
   * @param zeroDlvdatFlg  the value for MST_CORRECT_KB.Zero_Dlvdat_Flg
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setZeroDlvdatFlg(String zeroDlvdatFlg) {
    this.zeroDlvdatFlg = zeroDlvdatFlg;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_CORRECT_KB.Bikou
   * @return  the value of MST_CORRECT_KB.Bikou
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getBikou() {
    return bikou;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_CORRECT_KB.Bikou
   * @param bikou  the value for MST_CORRECT_KB.Bikou
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setBikou(String bikou) {
    this.bikou = bikou;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_CORRECT_KB.STS_Code
   * @return  the value of MST_CORRECT_KB.STS_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getStsCode() {
    return stsCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_CORRECT_KB.STS_Code
   * @param stsCode  the value for MST_CORRECT_KB.STS_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setStsCode(String stsCode) {
    this.stsCode = stsCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_CORRECT_KB.INS_USERID
   * @return  the value of MST_CORRECT_KB.INS_USERID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getInsUserid() {
    return insUserid;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_CORRECT_KB.INS_USERID
   * @param insUserid  the value for MST_CORRECT_KB.INS_USERID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setInsUserid(String insUserid) {
    this.insUserid = insUserid;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_CORRECT_KB.INS_PGID
   * @return  the value of MST_CORRECT_KB.INS_PGID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getInsPgid() {
    return insPgid;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_CORRECT_KB.INS_PGID
   * @param insPgid  the value for MST_CORRECT_KB.INS_PGID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setInsPgid(String insPgid) {
    this.insPgid = insPgid;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_CORRECT_KB.INS_YMD
   * @return  the value of MST_CORRECT_KB.INS_YMD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getInsYmd() {
    return insYmd;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_CORRECT_KB.INS_YMD
   * @param insYmd  the value for MST_CORRECT_KB.INS_YMD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setInsYmd(String insYmd) {
    this.insYmd = insYmd;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_CORRECT_KB.INS_TIME
   * @return  the value of MST_CORRECT_KB.INS_TIME
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getInsTime() {
    return insTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_CORRECT_KB.INS_TIME
   * @param insTime  the value for MST_CORRECT_KB.INS_TIME
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setInsTime(String insTime) {
    this.insTime = insTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_CORRECT_KB.UPD_USERID
   * @return  the value of MST_CORRECT_KB.UPD_USERID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getUpdUserid() {
    return updUserid;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_CORRECT_KB.UPD_USERID
   * @param updUserid  the value for MST_CORRECT_KB.UPD_USERID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setUpdUserid(String updUserid) {
    this.updUserid = updUserid;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_CORRECT_KB.UPD_PGID
   * @return  the value of MST_CORRECT_KB.UPD_PGID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getUpdPgid() {
    return updPgid;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_CORRECT_KB.UPD_PGID
   * @param updPgid  the value for MST_CORRECT_KB.UPD_PGID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setUpdPgid(String updPgid) {
    this.updPgid = updPgid;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_CORRECT_KB.UPD_YMD
   * @return  the value of MST_CORRECT_KB.UPD_YMD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getUpdYmd() {
    return updYmd;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_CORRECT_KB.UPD_YMD
   * @param updYmd  the value for MST_CORRECT_KB.UPD_YMD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setUpdYmd(String updYmd) {
    this.updYmd = updYmd;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_CORRECT_KB.UPD_TIME
   * @return  the value of MST_CORRECT_KB.UPD_TIME
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getUpdTime() {
    return updTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_CORRECT_KB.UPD_TIME
   * @param updTime  the value for MST_CORRECT_KB.UPD_TIME
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setUpdTime(String updTime) {
    this.updTime = updTime;
  }
}