package jp.co.daitoku_sh.dfcm.common.db.model;

public class MstCustConvKey {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_CUST_CONV.OL_Center_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String olCenterCode;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_CUST_CONV.OL_Torihiki_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String olTorihikiCode;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_CUST_CONV.AT_Torihiki_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String atTorihikiCode;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_CUST_CONV.AT_Ten_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String atTenCode;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_CUST_CONV.OL_Center_Code
   * @return  the value of MST_CUST_CONV.OL_Center_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getOlCenterCode() {
    return olCenterCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_CUST_CONV.OL_Center_Code
   * @param olCenterCode  the value for MST_CUST_CONV.OL_Center_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setOlCenterCode(String olCenterCode) {
    this.olCenterCode = olCenterCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_CUST_CONV.OL_Torihiki_Code
   * @return  the value of MST_CUST_CONV.OL_Torihiki_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getOlTorihikiCode() {
    return olTorihikiCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_CUST_CONV.OL_Torihiki_Code
   * @param olTorihikiCode  the value for MST_CUST_CONV.OL_Torihiki_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setOlTorihikiCode(String olTorihikiCode) {
    this.olTorihikiCode = olTorihikiCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_CUST_CONV.AT_Torihiki_Code
   * @return  the value of MST_CUST_CONV.AT_Torihiki_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getAtTorihikiCode() {
    return atTorihikiCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_CUST_CONV.AT_Torihiki_Code
   * @param atTorihikiCode  the value for MST_CUST_CONV.AT_Torihiki_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setAtTorihikiCode(String atTorihikiCode) {
    this.atTorihikiCode = atTorihikiCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_CUST_CONV.AT_Ten_Code
   * @return  the value of MST_CUST_CONV.AT_Ten_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getAtTenCode() {
    return atTenCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_CUST_CONV.AT_Ten_Code
   * @param atTenCode  the value for MST_CUST_CONV.AT_Ten_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setAtTenCode(String atTenCode) {
    this.atTenCode = atTenCode;
  }
}