package jp.co.daitoku_sh.dfcm.common.db.model;

public class MstFunction extends MstFunctionKey {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_FUNCTION.Gy_Bunrui
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String gyBunrui;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_FUNCTION.Gy_Func_Nm
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String gyFuncNm;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_FUNCTION.Gy_Func_Menu_Nm
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String gyFuncMenuNm;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_FUNCTION.Pg_Id
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String pgId;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_FUNCTION.Path
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String path;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_FUNCTION.Menu_Order
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private Short menuOrder;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_FUNCTION.INS_USERID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String insUserid;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_FUNCTION.INS_PGID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String insPgid;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_FUNCTION.INS_YMD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String insYmd;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_FUNCTION.INS_TIME
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String insTime;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_FUNCTION.UPD_USERID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String updUserid;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_FUNCTION.UPD_PGID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String updPgid;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_FUNCTION.UPD_YMD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String updYmd;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_FUNCTION.UPD_TIME
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String updTime;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_FUNCTION.Gy_Bunrui
   * @return  the value of MST_FUNCTION.Gy_Bunrui
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getGyBunrui() {
    return gyBunrui;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_FUNCTION.Gy_Bunrui
   * @param gyBunrui  the value for MST_FUNCTION.Gy_Bunrui
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setGyBunrui(String gyBunrui) {
    this.gyBunrui = gyBunrui;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_FUNCTION.Gy_Func_Nm
   * @return  the value of MST_FUNCTION.Gy_Func_Nm
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getGyFuncNm() {
    return gyFuncNm;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_FUNCTION.Gy_Func_Nm
   * @param gyFuncNm  the value for MST_FUNCTION.Gy_Func_Nm
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setGyFuncNm(String gyFuncNm) {
    this.gyFuncNm = gyFuncNm;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_FUNCTION.Gy_Func_Menu_Nm
   * @return  the value of MST_FUNCTION.Gy_Func_Menu_Nm
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getGyFuncMenuNm() {
    return gyFuncMenuNm;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_FUNCTION.Gy_Func_Menu_Nm
   * @param gyFuncMenuNm  the value for MST_FUNCTION.Gy_Func_Menu_Nm
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setGyFuncMenuNm(String gyFuncMenuNm) {
    this.gyFuncMenuNm = gyFuncMenuNm;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_FUNCTION.Pg_Id
   * @return  the value of MST_FUNCTION.Pg_Id
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getPgId() {
    return pgId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_FUNCTION.Pg_Id
   * @param pgId  the value for MST_FUNCTION.Pg_Id
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setPgId(String pgId) {
    this.pgId = pgId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_FUNCTION.Path
   * @return  the value of MST_FUNCTION.Path
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getPath() {
    return path;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_FUNCTION.Path
   * @param path  the value for MST_FUNCTION.Path
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setPath(String path) {
    this.path = path;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_FUNCTION.Menu_Order
   * @return  the value of MST_FUNCTION.Menu_Order
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public Short getMenuOrder() {
    return menuOrder;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_FUNCTION.Menu_Order
   * @param menuOrder  the value for MST_FUNCTION.Menu_Order
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setMenuOrder(Short menuOrder) {
    this.menuOrder = menuOrder;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_FUNCTION.INS_USERID
   * @return  the value of MST_FUNCTION.INS_USERID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getInsUserid() {
    return insUserid;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_FUNCTION.INS_USERID
   * @param insUserid  the value for MST_FUNCTION.INS_USERID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setInsUserid(String insUserid) {
    this.insUserid = insUserid;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_FUNCTION.INS_PGID
   * @return  the value of MST_FUNCTION.INS_PGID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getInsPgid() {
    return insPgid;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_FUNCTION.INS_PGID
   * @param insPgid  the value for MST_FUNCTION.INS_PGID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setInsPgid(String insPgid) {
    this.insPgid = insPgid;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_FUNCTION.INS_YMD
   * @return  the value of MST_FUNCTION.INS_YMD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getInsYmd() {
    return insYmd;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_FUNCTION.INS_YMD
   * @param insYmd  the value for MST_FUNCTION.INS_YMD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setInsYmd(String insYmd) {
    this.insYmd = insYmd;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_FUNCTION.INS_TIME
   * @return  the value of MST_FUNCTION.INS_TIME
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getInsTime() {
    return insTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_FUNCTION.INS_TIME
   * @param insTime  the value for MST_FUNCTION.INS_TIME
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setInsTime(String insTime) {
    this.insTime = insTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_FUNCTION.UPD_USERID
   * @return  the value of MST_FUNCTION.UPD_USERID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getUpdUserid() {
    return updUserid;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_FUNCTION.UPD_USERID
   * @param updUserid  the value for MST_FUNCTION.UPD_USERID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setUpdUserid(String updUserid) {
    this.updUserid = updUserid;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_FUNCTION.UPD_PGID
   * @return  the value of MST_FUNCTION.UPD_PGID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getUpdPgid() {
    return updPgid;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_FUNCTION.UPD_PGID
   * @param updPgid  the value for MST_FUNCTION.UPD_PGID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setUpdPgid(String updPgid) {
    this.updPgid = updPgid;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_FUNCTION.UPD_YMD
   * @return  the value of MST_FUNCTION.UPD_YMD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getUpdYmd() {
    return updYmd;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_FUNCTION.UPD_YMD
   * @param updYmd  the value for MST_FUNCTION.UPD_YMD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setUpdYmd(String updYmd) {
    this.updYmd = updYmd;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_FUNCTION.UPD_TIME
   * @return  the value of MST_FUNCTION.UPD_TIME
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getUpdTime() {
    return updTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_FUNCTION.UPD_TIME
   * @param updTime  the value for MST_FUNCTION.UPD_TIME
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setUpdTime(String updTime) {
    this.updTime = updTime;
  }
}