package jp.co.daitoku_sh.dfcm.common.db.model;

import java.math.BigDecimal;

public class MstGeneral extends MstGeneralKey {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Code_Attr
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String codeAttr;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Code_Digit
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private BigDecimal codeDigit;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Kb_Nm
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String kbNm;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Code_Nm
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String codeNm;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_1
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String target1;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_Attr_1
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String targetAttr1;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_Digit_1
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private BigDecimal targetDigit1;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_Exp_1
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String targetExp1;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_2
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String target2;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_Attr_2
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String targetAttr2;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_Digit_2
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private BigDecimal targetDigit2;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_Exp_2
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String targetExp2;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_3
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String target3;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_Attr_3
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String targetAttr3;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_Digit_3
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private BigDecimal targetDigit3;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_Exp_3
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String targetExp3;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_4
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String target4;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_Attr_4
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String targetAttr4;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_Digit_4
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private BigDecimal targetDigit4;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_Exp_4
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String targetExp4;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_5
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String target5;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_Attr_5
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String targetAttr5;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_Digit_5
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private BigDecimal targetDigit5;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_Exp_5
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String targetExp5;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_6
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String target6;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_Attr_6
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String targetAttr6;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_Digit_6
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private BigDecimal targetDigit6;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_Exp_6
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String targetExp6;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_7
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String target7;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_Attr_7
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String targetAttr7;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_Digit_7
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private BigDecimal targetDigit7;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_Exp_7
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String targetExp7;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_8
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String target8;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_Attr_8
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String targetAttr8;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_Digit_8
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private BigDecimal targetDigit8;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_Exp_8
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String targetExp8;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_9
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String target9;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_Attr_9
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String targetAttr9;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_Digit_9
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private BigDecimal targetDigit9;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_Exp_9
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String targetExp9;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_10
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String target10;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_Attr_10
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String targetAttr10;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_Digit_10
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private BigDecimal targetDigit10;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Target_Exp_10
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String targetExp10;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Category
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String category;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Disp_Numeric
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private Integer dispNumeric;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Ins_Permit_Flg
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String insPermitFlg;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Upd_Permit_Flg
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String updPermitFlg;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.Del_Permit_Flg
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String delPermitFlg;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.INS_USERID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String insUserid;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.INS_PGID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String insPgid;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.INS_YMD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String insYmd;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.INS_TIME
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String insTime;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.UPD_USERID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String updUserid;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.UPD_PGID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String updPgid;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.UPD_YMD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String updYmd;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_GENERAL.UPD_TIME
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String updTime;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Code_Attr
   * @return  the value of MST_GENERAL.Code_Attr
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getCodeAttr() {
    return codeAttr;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Code_Attr
   * @param codeAttr  the value for MST_GENERAL.Code_Attr
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setCodeAttr(String codeAttr) {
    this.codeAttr = codeAttr;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Code_Digit
   * @return  the value of MST_GENERAL.Code_Digit
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public BigDecimal getCodeDigit() {
    return codeDigit;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Code_Digit
   * @param codeDigit  the value for MST_GENERAL.Code_Digit
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setCodeDigit(BigDecimal codeDigit) {
    this.codeDigit = codeDigit;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Kb_Nm
   * @return  the value of MST_GENERAL.Kb_Nm
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getKbNm() {
    return kbNm;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Kb_Nm
   * @param kbNm  the value for MST_GENERAL.Kb_Nm
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setKbNm(String kbNm) {
    this.kbNm = kbNm;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Code_Nm
   * @return  the value of MST_GENERAL.Code_Nm
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getCodeNm() {
    return codeNm;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Code_Nm
   * @param codeNm  the value for MST_GENERAL.Code_Nm
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setCodeNm(String codeNm) {
    this.codeNm = codeNm;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_1
   * @return  the value of MST_GENERAL.Target_1
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getTarget1() {
    return target1;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_1
   * @param target1  the value for MST_GENERAL.Target_1
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTarget1(String target1) {
    this.target1 = target1;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_Attr_1
   * @return  the value of MST_GENERAL.Target_Attr_1
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getTargetAttr1() {
    return targetAttr1;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_Attr_1
   * @param targetAttr1  the value for MST_GENERAL.Target_Attr_1
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTargetAttr1(String targetAttr1) {
    this.targetAttr1 = targetAttr1;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_Digit_1
   * @return  the value of MST_GENERAL.Target_Digit_1
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public BigDecimal getTargetDigit1() {
    return targetDigit1;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_Digit_1
   * @param targetDigit1  the value for MST_GENERAL.Target_Digit_1
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTargetDigit1(BigDecimal targetDigit1) {
    this.targetDigit1 = targetDigit1;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_Exp_1
   * @return  the value of MST_GENERAL.Target_Exp_1
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getTargetExp1() {
    return targetExp1;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_Exp_1
   * @param targetExp1  the value for MST_GENERAL.Target_Exp_1
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTargetExp1(String targetExp1) {
    this.targetExp1 = targetExp1;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_2
   * @return  the value of MST_GENERAL.Target_2
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getTarget2() {
    return target2;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_2
   * @param target2  the value for MST_GENERAL.Target_2
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTarget2(String target2) {
    this.target2 = target2;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_Attr_2
   * @return  the value of MST_GENERAL.Target_Attr_2
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getTargetAttr2() {
    return targetAttr2;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_Attr_2
   * @param targetAttr2  the value for MST_GENERAL.Target_Attr_2
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTargetAttr2(String targetAttr2) {
    this.targetAttr2 = targetAttr2;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_Digit_2
   * @return  the value of MST_GENERAL.Target_Digit_2
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public BigDecimal getTargetDigit2() {
    return targetDigit2;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_Digit_2
   * @param targetDigit2  the value for MST_GENERAL.Target_Digit_2
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTargetDigit2(BigDecimal targetDigit2) {
    this.targetDigit2 = targetDigit2;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_Exp_2
   * @return  the value of MST_GENERAL.Target_Exp_2
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getTargetExp2() {
    return targetExp2;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_Exp_2
   * @param targetExp2  the value for MST_GENERAL.Target_Exp_2
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTargetExp2(String targetExp2) {
    this.targetExp2 = targetExp2;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_3
   * @return  the value of MST_GENERAL.Target_3
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getTarget3() {
    return target3;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_3
   * @param target3  the value for MST_GENERAL.Target_3
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTarget3(String target3) {
    this.target3 = target3;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_Attr_3
   * @return  the value of MST_GENERAL.Target_Attr_3
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getTargetAttr3() {
    return targetAttr3;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_Attr_3
   * @param targetAttr3  the value for MST_GENERAL.Target_Attr_3
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTargetAttr3(String targetAttr3) {
    this.targetAttr3 = targetAttr3;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_Digit_3
   * @return  the value of MST_GENERAL.Target_Digit_3
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public BigDecimal getTargetDigit3() {
    return targetDigit3;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_Digit_3
   * @param targetDigit3  the value for MST_GENERAL.Target_Digit_3
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTargetDigit3(BigDecimal targetDigit3) {
    this.targetDigit3 = targetDigit3;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_Exp_3
   * @return  the value of MST_GENERAL.Target_Exp_3
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getTargetExp3() {
    return targetExp3;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_Exp_3
   * @param targetExp3  the value for MST_GENERAL.Target_Exp_3
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTargetExp3(String targetExp3) {
    this.targetExp3 = targetExp3;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_4
   * @return  the value of MST_GENERAL.Target_4
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getTarget4() {
    return target4;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_4
   * @param target4  the value for MST_GENERAL.Target_4
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTarget4(String target4) {
    this.target4 = target4;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_Attr_4
   * @return  the value of MST_GENERAL.Target_Attr_4
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getTargetAttr4() {
    return targetAttr4;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_Attr_4
   * @param targetAttr4  the value for MST_GENERAL.Target_Attr_4
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTargetAttr4(String targetAttr4) {
    this.targetAttr4 = targetAttr4;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_Digit_4
   * @return  the value of MST_GENERAL.Target_Digit_4
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public BigDecimal getTargetDigit4() {
    return targetDigit4;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_Digit_4
   * @param targetDigit4  the value for MST_GENERAL.Target_Digit_4
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTargetDigit4(BigDecimal targetDigit4) {
    this.targetDigit4 = targetDigit4;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_Exp_4
   * @return  the value of MST_GENERAL.Target_Exp_4
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getTargetExp4() {
    return targetExp4;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_Exp_4
   * @param targetExp4  the value for MST_GENERAL.Target_Exp_4
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTargetExp4(String targetExp4) {
    this.targetExp4 = targetExp4;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_5
   * @return  the value of MST_GENERAL.Target_5
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getTarget5() {
    return target5;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_5
   * @param target5  the value for MST_GENERAL.Target_5
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTarget5(String target5) {
    this.target5 = target5;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_Attr_5
   * @return  the value of MST_GENERAL.Target_Attr_5
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getTargetAttr5() {
    return targetAttr5;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_Attr_5
   * @param targetAttr5  the value for MST_GENERAL.Target_Attr_5
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTargetAttr5(String targetAttr5) {
    this.targetAttr5 = targetAttr5;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_Digit_5
   * @return  the value of MST_GENERAL.Target_Digit_5
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public BigDecimal getTargetDigit5() {
    return targetDigit5;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_Digit_5
   * @param targetDigit5  the value for MST_GENERAL.Target_Digit_5
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTargetDigit5(BigDecimal targetDigit5) {
    this.targetDigit5 = targetDigit5;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_Exp_5
   * @return  the value of MST_GENERAL.Target_Exp_5
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getTargetExp5() {
    return targetExp5;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_Exp_5
   * @param targetExp5  the value for MST_GENERAL.Target_Exp_5
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTargetExp5(String targetExp5) {
    this.targetExp5 = targetExp5;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_6
   * @return  the value of MST_GENERAL.Target_6
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getTarget6() {
    return target6;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_6
   * @param target6  the value for MST_GENERAL.Target_6
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTarget6(String target6) {
    this.target6 = target6;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_Attr_6
   * @return  the value of MST_GENERAL.Target_Attr_6
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getTargetAttr6() {
    return targetAttr6;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_Attr_6
   * @param targetAttr6  the value for MST_GENERAL.Target_Attr_6
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTargetAttr6(String targetAttr6) {
    this.targetAttr6 = targetAttr6;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_Digit_6
   * @return  the value of MST_GENERAL.Target_Digit_6
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public BigDecimal getTargetDigit6() {
    return targetDigit6;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_Digit_6
   * @param targetDigit6  the value for MST_GENERAL.Target_Digit_6
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTargetDigit6(BigDecimal targetDigit6) {
    this.targetDigit6 = targetDigit6;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_Exp_6
   * @return  the value of MST_GENERAL.Target_Exp_6
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getTargetExp6() {
    return targetExp6;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_Exp_6
   * @param targetExp6  the value for MST_GENERAL.Target_Exp_6
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTargetExp6(String targetExp6) {
    this.targetExp6 = targetExp6;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_7
   * @return  the value of MST_GENERAL.Target_7
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getTarget7() {
    return target7;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_7
   * @param target7  the value for MST_GENERAL.Target_7
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTarget7(String target7) {
    this.target7 = target7;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_Attr_7
   * @return  the value of MST_GENERAL.Target_Attr_7
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getTargetAttr7() {
    return targetAttr7;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_Attr_7
   * @param targetAttr7  the value for MST_GENERAL.Target_Attr_7
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTargetAttr7(String targetAttr7) {
    this.targetAttr7 = targetAttr7;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_Digit_7
   * @return  the value of MST_GENERAL.Target_Digit_7
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public BigDecimal getTargetDigit7() {
    return targetDigit7;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_Digit_7
   * @param targetDigit7  the value for MST_GENERAL.Target_Digit_7
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTargetDigit7(BigDecimal targetDigit7) {
    this.targetDigit7 = targetDigit7;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_Exp_7
   * @return  the value of MST_GENERAL.Target_Exp_7
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getTargetExp7() {
    return targetExp7;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_Exp_7
   * @param targetExp7  the value for MST_GENERAL.Target_Exp_7
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTargetExp7(String targetExp7) {
    this.targetExp7 = targetExp7;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_8
   * @return  the value of MST_GENERAL.Target_8
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getTarget8() {
    return target8;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_8
   * @param target8  the value for MST_GENERAL.Target_8
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTarget8(String target8) {
    this.target8 = target8;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_Attr_8
   * @return  the value of MST_GENERAL.Target_Attr_8
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getTargetAttr8() {
    return targetAttr8;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_Attr_8
   * @param targetAttr8  the value for MST_GENERAL.Target_Attr_8
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTargetAttr8(String targetAttr8) {
    this.targetAttr8 = targetAttr8;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_Digit_8
   * @return  the value of MST_GENERAL.Target_Digit_8
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public BigDecimal getTargetDigit8() {
    return targetDigit8;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_Digit_8
   * @param targetDigit8  the value for MST_GENERAL.Target_Digit_8
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTargetDigit8(BigDecimal targetDigit8) {
    this.targetDigit8 = targetDigit8;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_Exp_8
   * @return  the value of MST_GENERAL.Target_Exp_8
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getTargetExp8() {
    return targetExp8;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_Exp_8
   * @param targetExp8  the value for MST_GENERAL.Target_Exp_8
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTargetExp8(String targetExp8) {
    this.targetExp8 = targetExp8;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_9
   * @return  the value of MST_GENERAL.Target_9
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getTarget9() {
    return target9;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_9
   * @param target9  the value for MST_GENERAL.Target_9
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTarget9(String target9) {
    this.target9 = target9;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_Attr_9
   * @return  the value of MST_GENERAL.Target_Attr_9
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getTargetAttr9() {
    return targetAttr9;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_Attr_9
   * @param targetAttr9  the value for MST_GENERAL.Target_Attr_9
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTargetAttr9(String targetAttr9) {
    this.targetAttr9 = targetAttr9;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_Digit_9
   * @return  the value of MST_GENERAL.Target_Digit_9
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public BigDecimal getTargetDigit9() {
    return targetDigit9;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_Digit_9
   * @param targetDigit9  the value for MST_GENERAL.Target_Digit_9
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTargetDigit9(BigDecimal targetDigit9) {
    this.targetDigit9 = targetDigit9;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_Exp_9
   * @return  the value of MST_GENERAL.Target_Exp_9
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getTargetExp9() {
    return targetExp9;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_Exp_9
   * @param targetExp9  the value for MST_GENERAL.Target_Exp_9
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTargetExp9(String targetExp9) {
    this.targetExp9 = targetExp9;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_10
   * @return  the value of MST_GENERAL.Target_10
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getTarget10() {
    return target10;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_10
   * @param target10  the value for MST_GENERAL.Target_10
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTarget10(String target10) {
    this.target10 = target10;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_Attr_10
   * @return  the value of MST_GENERAL.Target_Attr_10
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getTargetAttr10() {
    return targetAttr10;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_Attr_10
   * @param targetAttr10  the value for MST_GENERAL.Target_Attr_10
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTargetAttr10(String targetAttr10) {
    this.targetAttr10 = targetAttr10;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_Digit_10
   * @return  the value of MST_GENERAL.Target_Digit_10
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public BigDecimal getTargetDigit10() {
    return targetDigit10;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_Digit_10
   * @param targetDigit10  the value for MST_GENERAL.Target_Digit_10
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTargetDigit10(BigDecimal targetDigit10) {
    this.targetDigit10 = targetDigit10;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Target_Exp_10
   * @return  the value of MST_GENERAL.Target_Exp_10
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getTargetExp10() {
    return targetExp10;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Target_Exp_10
   * @param targetExp10  the value for MST_GENERAL.Target_Exp_10
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTargetExp10(String targetExp10) {
    this.targetExp10 = targetExp10;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Category
   * @return  the value of MST_GENERAL.Category
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getCategory() {
    return category;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Category
   * @param category  the value for MST_GENERAL.Category
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setCategory(String category) {
    this.category = category;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Disp_Numeric
   * @return  the value of MST_GENERAL.Disp_Numeric
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public Integer getDispNumeric() {
    return dispNumeric;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Disp_Numeric
   * @param dispNumeric  the value for MST_GENERAL.Disp_Numeric
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setDispNumeric(Integer dispNumeric) {
    this.dispNumeric = dispNumeric;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Ins_Permit_Flg
   * @return  the value of MST_GENERAL.Ins_Permit_Flg
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getInsPermitFlg() {
    return insPermitFlg;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Ins_Permit_Flg
   * @param insPermitFlg  the value for MST_GENERAL.Ins_Permit_Flg
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setInsPermitFlg(String insPermitFlg) {
    this.insPermitFlg = insPermitFlg;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Upd_Permit_Flg
   * @return  the value of MST_GENERAL.Upd_Permit_Flg
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getUpdPermitFlg() {
    return updPermitFlg;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Upd_Permit_Flg
   * @param updPermitFlg  the value for MST_GENERAL.Upd_Permit_Flg
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setUpdPermitFlg(String updPermitFlg) {
    this.updPermitFlg = updPermitFlg;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.Del_Permit_Flg
   * @return  the value of MST_GENERAL.Del_Permit_Flg
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getDelPermitFlg() {
    return delPermitFlg;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.Del_Permit_Flg
   * @param delPermitFlg  the value for MST_GENERAL.Del_Permit_Flg
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setDelPermitFlg(String delPermitFlg) {
    this.delPermitFlg = delPermitFlg;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.INS_USERID
   * @return  the value of MST_GENERAL.INS_USERID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getInsUserid() {
    return insUserid;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.INS_USERID
   * @param insUserid  the value for MST_GENERAL.INS_USERID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setInsUserid(String insUserid) {
    this.insUserid = insUserid;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.INS_PGID
   * @return  the value of MST_GENERAL.INS_PGID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getInsPgid() {
    return insPgid;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.INS_PGID
   * @param insPgid  the value for MST_GENERAL.INS_PGID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setInsPgid(String insPgid) {
    this.insPgid = insPgid;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.INS_YMD
   * @return  the value of MST_GENERAL.INS_YMD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getInsYmd() {
    return insYmd;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.INS_YMD
   * @param insYmd  the value for MST_GENERAL.INS_YMD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setInsYmd(String insYmd) {
    this.insYmd = insYmd;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.INS_TIME
   * @return  the value of MST_GENERAL.INS_TIME
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getInsTime() {
    return insTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.INS_TIME
   * @param insTime  the value for MST_GENERAL.INS_TIME
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setInsTime(String insTime) {
    this.insTime = insTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.UPD_USERID
   * @return  the value of MST_GENERAL.UPD_USERID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getUpdUserid() {
    return updUserid;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.UPD_USERID
   * @param updUserid  the value for MST_GENERAL.UPD_USERID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setUpdUserid(String updUserid) {
    this.updUserid = updUserid;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.UPD_PGID
   * @return  the value of MST_GENERAL.UPD_PGID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getUpdPgid() {
    return updPgid;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.UPD_PGID
   * @param updPgid  the value for MST_GENERAL.UPD_PGID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setUpdPgid(String updPgid) {
    this.updPgid = updPgid;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.UPD_YMD
   * @return  the value of MST_GENERAL.UPD_YMD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getUpdYmd() {
    return updYmd;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.UPD_YMD
   * @param updYmd  the value for MST_GENERAL.UPD_YMD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setUpdYmd(String updYmd) {
    this.updYmd = updYmd;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_GENERAL.UPD_TIME
   * @return  the value of MST_GENERAL.UPD_TIME
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getUpdTime() {
    return updTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_GENERAL.UPD_TIME
   * @param updTime  the value for MST_GENERAL.UPD_TIME
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setUpdTime(String updTime) {
    this.updTime = updTime;
  }
}