package jp.co.daitoku_sh.dfcm.common.db.model;

import java.util.ArrayList;
import java.util.List;

public class MstListDistExample {
    /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table MST_LIST_DIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  protected String orderByClause;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table MST_LIST_DIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  protected boolean distinct;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table MST_LIST_DIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_LIST_DIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public MstListDistExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_LIST_DIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_LIST_DIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_LIST_DIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_LIST_DIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_LIST_DIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_LIST_DIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_LIST_DIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_LIST_DIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_LIST_DIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_LIST_DIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table MST_LIST_DIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  protected abstract static class GeneratedCriteria {

    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value,
        String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2,
        String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property
            + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andListIdIsNull() {
      addCriterion("List_Id is null");
      return (Criteria) this;
    }

    public Criteria andListIdIsNotNull() {
      addCriterion("List_Id is not null");
      return (Criteria) this;
    }

    public Criteria andListIdEqualTo(String value) {
      addCriterion("List_Id =", value, "listId");
      return (Criteria) this;
    }

    public Criteria andListIdNotEqualTo(String value) {
      addCriterion("List_Id <>", value, "listId");
      return (Criteria) this;
    }

    public Criteria andListIdGreaterThan(String value) {
      addCriterion("List_Id >", value, "listId");
      return (Criteria) this;
    }

    public Criteria andListIdGreaterThanOrEqualTo(String value) {
      addCriterion("List_Id >=", value, "listId");
      return (Criteria) this;
    }

    public Criteria andListIdLessThan(String value) {
      addCriterion("List_Id <", value, "listId");
      return (Criteria) this;
    }

    public Criteria andListIdLessThanOrEqualTo(String value) {
      addCriterion("List_Id <=", value, "listId");
      return (Criteria) this;
    }

    public Criteria andListIdLike(String value) {
      addCriterion("List_Id like", value, "listId");
      return (Criteria) this;
    }

    public Criteria andListIdNotLike(String value) {
      addCriterion("List_Id not like", value, "listId");
      return (Criteria) this;
    }

    public Criteria andListIdIn(List<String> values) {
      addCriterion("List_Id in", values, "listId");
      return (Criteria) this;
    }

    public Criteria andListIdNotIn(List<String> values) {
      addCriterion("List_Id not in", values, "listId");
      return (Criteria) this;
    }

    public Criteria andListIdBetween(String value1, String value2) {
      addCriterion("List_Id between", value1, value2, "listId");
      return (Criteria) this;
    }

    public Criteria andListIdNotBetween(String value1, String value2) {
      addCriterion("List_Id not between", value1, value2, "listId");
      return (Criteria) this;
    }

    public Criteria andJigyoCodeIsNull() {
      addCriterion("Jigyo_Code is null");
      return (Criteria) this;
    }

    public Criteria andJigyoCodeIsNotNull() {
      addCriterion("Jigyo_Code is not null");
      return (Criteria) this;
    }

    public Criteria andJigyoCodeEqualTo(String value) {
      addCriterion("Jigyo_Code =", value, "jigyoCode");
      return (Criteria) this;
    }

    public Criteria andJigyoCodeNotEqualTo(String value) {
      addCriterion("Jigyo_Code <>", value, "jigyoCode");
      return (Criteria) this;
    }

    public Criteria andJigyoCodeGreaterThan(String value) {
      addCriterion("Jigyo_Code >", value, "jigyoCode");
      return (Criteria) this;
    }

    public Criteria andJigyoCodeGreaterThanOrEqualTo(String value) {
      addCriterion("Jigyo_Code >=", value, "jigyoCode");
      return (Criteria) this;
    }

    public Criteria andJigyoCodeLessThan(String value) {
      addCriterion("Jigyo_Code <", value, "jigyoCode");
      return (Criteria) this;
    }

    public Criteria andJigyoCodeLessThanOrEqualTo(String value) {
      addCriterion("Jigyo_Code <=", value, "jigyoCode");
      return (Criteria) this;
    }

    public Criteria andJigyoCodeLike(String value) {
      addCriterion("Jigyo_Code like", value, "jigyoCode");
      return (Criteria) this;
    }

    public Criteria andJigyoCodeNotLike(String value) {
      addCriterion("Jigyo_Code not like", value, "jigyoCode");
      return (Criteria) this;
    }

    public Criteria andJigyoCodeIn(List<String> values) {
      addCriterion("Jigyo_Code in", values, "jigyoCode");
      return (Criteria) this;
    }

    public Criteria andJigyoCodeNotIn(List<String> values) {
      addCriterion("Jigyo_Code not in", values, "jigyoCode");
      return (Criteria) this;
    }

    public Criteria andJigyoCodeBetween(String value1, String value2) {
      addCriterion("Jigyo_Code between", value1, value2, "jigyoCode");
      return (Criteria) this;
    }

    public Criteria andJigyoCodeNotBetween(String value1, String value2) {
      addCriterion("Jigyo_Code not between", value1, value2, "jigyoCode");
      return (Criteria) this;
    }

    public Criteria andDenPrintIsNull() {
      addCriterion("Den_Print is null");
      return (Criteria) this;
    }

    public Criteria andDenPrintIsNotNull() {
      addCriterion("Den_Print is not null");
      return (Criteria) this;
    }

    public Criteria andDenPrintEqualTo(String value) {
      addCriterion("Den_Print =", value, "denPrint");
      return (Criteria) this;
    }

    public Criteria andDenPrintNotEqualTo(String value) {
      addCriterion("Den_Print <>", value, "denPrint");
      return (Criteria) this;
    }

    public Criteria andDenPrintGreaterThan(String value) {
      addCriterion("Den_Print >", value, "denPrint");
      return (Criteria) this;
    }

    public Criteria andDenPrintGreaterThanOrEqualTo(String value) {
      addCriterion("Den_Print >=", value, "denPrint");
      return (Criteria) this;
    }

    public Criteria andDenPrintLessThan(String value) {
      addCriterion("Den_Print <", value, "denPrint");
      return (Criteria) this;
    }

    public Criteria andDenPrintLessThanOrEqualTo(String value) {
      addCriterion("Den_Print <=", value, "denPrint");
      return (Criteria) this;
    }

    public Criteria andDenPrintLike(String value) {
      addCriterion("Den_Print like", value, "denPrint");
      return (Criteria) this;
    }

    public Criteria andDenPrintNotLike(String value) {
      addCriterion("Den_Print not like", value, "denPrint");
      return (Criteria) this;
    }

    public Criteria andDenPrintIn(List<String> values) {
      addCriterion("Den_Print in", values, "denPrint");
      return (Criteria) this;
    }

    public Criteria andDenPrintNotIn(List<String> values) {
      addCriterion("Den_Print not in", values, "denPrint");
      return (Criteria) this;
    }

    public Criteria andDenPrintBetween(String value1, String value2) {
      addCriterion("Den_Print between", value1, value2, "denPrint");
      return (Criteria) this;
    }

    public Criteria andDenPrintNotBetween(String value1, String value2) {
      addCriterion("Den_Print not between", value1, value2, "denPrint");
      return (Criteria) this;
    }

    public Criteria andDenClsIsNull() {
      addCriterion("Den_Cls is null");
      return (Criteria) this;
    }

    public Criteria andDenClsIsNotNull() {
      addCriterion("Den_Cls is not null");
      return (Criteria) this;
    }

    public Criteria andDenClsEqualTo(String value) {
      addCriterion("Den_Cls =", value, "denCls");
      return (Criteria) this;
    }

    public Criteria andDenClsNotEqualTo(String value) {
      addCriterion("Den_Cls <>", value, "denCls");
      return (Criteria) this;
    }

    public Criteria andDenClsGreaterThan(String value) {
      addCriterion("Den_Cls >", value, "denCls");
      return (Criteria) this;
    }

    public Criteria andDenClsGreaterThanOrEqualTo(String value) {
      addCriterion("Den_Cls >=", value, "denCls");
      return (Criteria) this;
    }

    public Criteria andDenClsLessThan(String value) {
      addCriterion("Den_Cls <", value, "denCls");
      return (Criteria) this;
    }

    public Criteria andDenClsLessThanOrEqualTo(String value) {
      addCriterion("Den_Cls <=", value, "denCls");
      return (Criteria) this;
    }

    public Criteria andDenClsLike(String value) {
      addCriterion("Den_Cls like", value, "denCls");
      return (Criteria) this;
    }

    public Criteria andDenClsNotLike(String value) {
      addCriterion("Den_Cls not like", value, "denCls");
      return (Criteria) this;
    }

    public Criteria andDenClsIn(List<String> values) {
      addCriterion("Den_Cls in", values, "denCls");
      return (Criteria) this;
    }

    public Criteria andDenClsNotIn(List<String> values) {
      addCriterion("Den_Cls not in", values, "denCls");
      return (Criteria) this;
    }

    public Criteria andDenClsBetween(String value1, String value2) {
      addCriterion("Den_Cls between", value1, value2, "denCls");
      return (Criteria) this;
    }

    public Criteria andDenClsNotBetween(String value1, String value2) {
      addCriterion("Den_Cls not between", value1, value2, "denCls");
      return (Criteria) this;
    }

    public Criteria andDistFolderIdIsNull() {
      addCriterion("Dist_Folder_Id is null");
      return (Criteria) this;
    }

    public Criteria andDistFolderIdIsNotNull() {
      addCriterion("Dist_Folder_Id is not null");
      return (Criteria) this;
    }

    public Criteria andDistFolderIdEqualTo(String value) {
      addCriterion("Dist_Folder_Id =", value, "distFolderId");
      return (Criteria) this;
    }

    public Criteria andDistFolderIdNotEqualTo(String value) {
      addCriterion("Dist_Folder_Id <>", value, "distFolderId");
      return (Criteria) this;
    }

    public Criteria andDistFolderIdGreaterThan(String value) {
      addCriterion("Dist_Folder_Id >", value, "distFolderId");
      return (Criteria) this;
    }

    public Criteria andDistFolderIdGreaterThanOrEqualTo(String value) {
      addCriterion("Dist_Folder_Id >=", value, "distFolderId");
      return (Criteria) this;
    }

    public Criteria andDistFolderIdLessThan(String value) {
      addCriterion("Dist_Folder_Id <", value, "distFolderId");
      return (Criteria) this;
    }

    public Criteria andDistFolderIdLessThanOrEqualTo(String value) {
      addCriterion("Dist_Folder_Id <=", value, "distFolderId");
      return (Criteria) this;
    }

    public Criteria andDistFolderIdLike(String value) {
      addCriterion("Dist_Folder_Id like", value, "distFolderId");
      return (Criteria) this;
    }

    public Criteria andDistFolderIdNotLike(String value) {
      addCriterion("Dist_Folder_Id not like", value, "distFolderId");
      return (Criteria) this;
    }

    public Criteria andDistFolderIdIn(List<String> values) {
      addCriterion("Dist_Folder_Id in", values, "distFolderId");
      return (Criteria) this;
    }

    public Criteria andDistFolderIdNotIn(List<String> values) {
      addCriterion("Dist_Folder_Id not in", values, "distFolderId");
      return (Criteria) this;
    }

    public Criteria andDistFolderIdBetween(String value1, String value2) {
      addCriterion("Dist_Folder_Id between", value1, value2, "distFolderId");
      return (Criteria) this;
    }

    public Criteria andDistFolderIdNotBetween(String value1, String value2) {
      addCriterion("Dist_Folder_Id not between", value1, value2,
          "distFolderId");
      return (Criteria) this;
    }

    public Criteria andDistFolderNmIsNull() {
      addCriterion("Dist_Folder_Nm is null");
      return (Criteria) this;
    }

    public Criteria andDistFolderNmIsNotNull() {
      addCriterion("Dist_Folder_Nm is not null");
      return (Criteria) this;
    }

    public Criteria andDistFolderNmEqualTo(String value) {
      addCriterion("Dist_Folder_Nm =", value, "distFolderNm");
      return (Criteria) this;
    }

    public Criteria andDistFolderNmNotEqualTo(String value) {
      addCriterion("Dist_Folder_Nm <>", value, "distFolderNm");
      return (Criteria) this;
    }

    public Criteria andDistFolderNmGreaterThan(String value) {
      addCriterion("Dist_Folder_Nm >", value, "distFolderNm");
      return (Criteria) this;
    }

    public Criteria andDistFolderNmGreaterThanOrEqualTo(String value) {
      addCriterion("Dist_Folder_Nm >=", value, "distFolderNm");
      return (Criteria) this;
    }

    public Criteria andDistFolderNmLessThan(String value) {
      addCriterion("Dist_Folder_Nm <", value, "distFolderNm");
      return (Criteria) this;
    }

    public Criteria andDistFolderNmLessThanOrEqualTo(String value) {
      addCriterion("Dist_Folder_Nm <=", value, "distFolderNm");
      return (Criteria) this;
    }

    public Criteria andDistFolderNmLike(String value) {
      addCriterion("Dist_Folder_Nm like", value, "distFolderNm");
      return (Criteria) this;
    }

    public Criteria andDistFolderNmNotLike(String value) {
      addCriterion("Dist_Folder_Nm not like", value, "distFolderNm");
      return (Criteria) this;
    }

    public Criteria andDistFolderNmIn(List<String> values) {
      addCriterion("Dist_Folder_Nm in", values, "distFolderNm");
      return (Criteria) this;
    }

    public Criteria andDistFolderNmNotIn(List<String> values) {
      addCriterion("Dist_Folder_Nm not in", values, "distFolderNm");
      return (Criteria) this;
    }

    public Criteria andDistFolderNmBetween(String value1, String value2) {
      addCriterion("Dist_Folder_Nm between", value1, value2, "distFolderNm");
      return (Criteria) this;
    }

    public Criteria andDistFolderNmNotBetween(String value1, String value2) {
      addCriterion("Dist_Folder_Nm not between", value1, value2,
          "distFolderNm");
      return (Criteria) this;
    }

    public Criteria andEleDeviceNmIsNull() {
      addCriterion("Ele_Device_Nm is null");
      return (Criteria) this;
    }

    public Criteria andEleDeviceNmIsNotNull() {
      addCriterion("Ele_Device_Nm is not null");
      return (Criteria) this;
    }

    public Criteria andEleDeviceNmEqualTo(String value) {
      addCriterion("Ele_Device_Nm =", value, "eleDeviceNm");
      return (Criteria) this;
    }

    public Criteria andEleDeviceNmNotEqualTo(String value) {
      addCriterion("Ele_Device_Nm <>", value, "eleDeviceNm");
      return (Criteria) this;
    }

    public Criteria andEleDeviceNmGreaterThan(String value) {
      addCriterion("Ele_Device_Nm >", value, "eleDeviceNm");
      return (Criteria) this;
    }

    public Criteria andEleDeviceNmGreaterThanOrEqualTo(String value) {
      addCriterion("Ele_Device_Nm >=", value, "eleDeviceNm");
      return (Criteria) this;
    }

    public Criteria andEleDeviceNmLessThan(String value) {
      addCriterion("Ele_Device_Nm <", value, "eleDeviceNm");
      return (Criteria) this;
    }

    public Criteria andEleDeviceNmLessThanOrEqualTo(String value) {
      addCriterion("Ele_Device_Nm <=", value, "eleDeviceNm");
      return (Criteria) this;
    }

    public Criteria andEleDeviceNmLike(String value) {
      addCriterion("Ele_Device_Nm like", value, "eleDeviceNm");
      return (Criteria) this;
    }

    public Criteria andEleDeviceNmNotLike(String value) {
      addCriterion("Ele_Device_Nm not like", value, "eleDeviceNm");
      return (Criteria) this;
    }

    public Criteria andEleDeviceNmIn(List<String> values) {
      addCriterion("Ele_Device_Nm in", values, "eleDeviceNm");
      return (Criteria) this;
    }

    public Criteria andEleDeviceNmNotIn(List<String> values) {
      addCriterion("Ele_Device_Nm not in", values, "eleDeviceNm");
      return (Criteria) this;
    }

    public Criteria andEleDeviceNmBetween(String value1, String value2) {
      addCriterion("Ele_Device_Nm between", value1, value2, "eleDeviceNm");
      return (Criteria) this;
    }

    public Criteria andEleDeviceNmNotBetween(String value1, String value2) {
      addCriterion("Ele_Device_Nm not between", value1, value2, "eleDeviceNm");
      return (Criteria) this;
    }

    public Criteria andElePathIsNull() {
      addCriterion("Ele_Path is null");
      return (Criteria) this;
    }

    public Criteria andElePathIsNotNull() {
      addCriterion("Ele_Path is not null");
      return (Criteria) this;
    }

    public Criteria andElePathEqualTo(String value) {
      addCriterion("Ele_Path =", value, "elePath");
      return (Criteria) this;
    }

    public Criteria andElePathNotEqualTo(String value) {
      addCriterion("Ele_Path <>", value, "elePath");
      return (Criteria) this;
    }

    public Criteria andElePathGreaterThan(String value) {
      addCriterion("Ele_Path >", value, "elePath");
      return (Criteria) this;
    }

    public Criteria andElePathGreaterThanOrEqualTo(String value) {
      addCriterion("Ele_Path >=", value, "elePath");
      return (Criteria) this;
    }

    public Criteria andElePathLessThan(String value) {
      addCriterion("Ele_Path <", value, "elePath");
      return (Criteria) this;
    }

    public Criteria andElePathLessThanOrEqualTo(String value) {
      addCriterion("Ele_Path <=", value, "elePath");
      return (Criteria) this;
    }

    public Criteria andElePathLike(String value) {
      addCriterion("Ele_Path like", value, "elePath");
      return (Criteria) this;
    }

    public Criteria andElePathNotLike(String value) {
      addCriterion("Ele_Path not like", value, "elePath");
      return (Criteria) this;
    }

    public Criteria andElePathIn(List<String> values) {
      addCriterion("Ele_Path in", values, "elePath");
      return (Criteria) this;
    }

    public Criteria andElePathNotIn(List<String> values) {
      addCriterion("Ele_Path not in", values, "elePath");
      return (Criteria) this;
    }

    public Criteria andElePathBetween(String value1, String value2) {
      addCriterion("Ele_Path between", value1, value2, "elePath");
      return (Criteria) this;
    }

    public Criteria andElePathNotBetween(String value1, String value2) {
      addCriterion("Ele_Path not between", value1, value2, "elePath");
      return (Criteria) this;
    }

    public Criteria andInsUseridIsNull() {
      addCriterion("INS_USERID is null");
      return (Criteria) this;
    }

    public Criteria andInsUseridIsNotNull() {
      addCriterion("INS_USERID is not null");
      return (Criteria) this;
    }

    public Criteria andInsUseridEqualTo(String value) {
      addCriterion("INS_USERID =", value, "insUserid");
      return (Criteria) this;
    }

    public Criteria andInsUseridNotEqualTo(String value) {
      addCriterion("INS_USERID <>", value, "insUserid");
      return (Criteria) this;
    }

    public Criteria andInsUseridGreaterThan(String value) {
      addCriterion("INS_USERID >", value, "insUserid");
      return (Criteria) this;
    }

    public Criteria andInsUseridGreaterThanOrEqualTo(String value) {
      addCriterion("INS_USERID >=", value, "insUserid");
      return (Criteria) this;
    }

    public Criteria andInsUseridLessThan(String value) {
      addCriterion("INS_USERID <", value, "insUserid");
      return (Criteria) this;
    }

    public Criteria andInsUseridLessThanOrEqualTo(String value) {
      addCriterion("INS_USERID <=", value, "insUserid");
      return (Criteria) this;
    }

    public Criteria andInsUseridLike(String value) {
      addCriterion("INS_USERID like", value, "insUserid");
      return (Criteria) this;
    }

    public Criteria andInsUseridNotLike(String value) {
      addCriterion("INS_USERID not like", value, "insUserid");
      return (Criteria) this;
    }

    public Criteria andInsUseridIn(List<String> values) {
      addCriterion("INS_USERID in", values, "insUserid");
      return (Criteria) this;
    }

    public Criteria andInsUseridNotIn(List<String> values) {
      addCriterion("INS_USERID not in", values, "insUserid");
      return (Criteria) this;
    }

    public Criteria andInsUseridBetween(String value1, String value2) {
      addCriterion("INS_USERID between", value1, value2, "insUserid");
      return (Criteria) this;
    }

    public Criteria andInsUseridNotBetween(String value1, String value2) {
      addCriterion("INS_USERID not between", value1, value2, "insUserid");
      return (Criteria) this;
    }

    public Criteria andInsPgidIsNull() {
      addCriterion("INS_PGID is null");
      return (Criteria) this;
    }

    public Criteria andInsPgidIsNotNull() {
      addCriterion("INS_PGID is not null");
      return (Criteria) this;
    }

    public Criteria andInsPgidEqualTo(String value) {
      addCriterion("INS_PGID =", value, "insPgid");
      return (Criteria) this;
    }

    public Criteria andInsPgidNotEqualTo(String value) {
      addCriterion("INS_PGID <>", value, "insPgid");
      return (Criteria) this;
    }

    public Criteria andInsPgidGreaterThan(String value) {
      addCriterion("INS_PGID >", value, "insPgid");
      return (Criteria) this;
    }

    public Criteria andInsPgidGreaterThanOrEqualTo(String value) {
      addCriterion("INS_PGID >=", value, "insPgid");
      return (Criteria) this;
    }

    public Criteria andInsPgidLessThan(String value) {
      addCriterion("INS_PGID <", value, "insPgid");
      return (Criteria) this;
    }

    public Criteria andInsPgidLessThanOrEqualTo(String value) {
      addCriterion("INS_PGID <=", value, "insPgid");
      return (Criteria) this;
    }

    public Criteria andInsPgidLike(String value) {
      addCriterion("INS_PGID like", value, "insPgid");
      return (Criteria) this;
    }

    public Criteria andInsPgidNotLike(String value) {
      addCriterion("INS_PGID not like", value, "insPgid");
      return (Criteria) this;
    }

    public Criteria andInsPgidIn(List<String> values) {
      addCriterion("INS_PGID in", values, "insPgid");
      return (Criteria) this;
    }

    public Criteria andInsPgidNotIn(List<String> values) {
      addCriterion("INS_PGID not in", values, "insPgid");
      return (Criteria) this;
    }

    public Criteria andInsPgidBetween(String value1, String value2) {
      addCriterion("INS_PGID between", value1, value2, "insPgid");
      return (Criteria) this;
    }

    public Criteria andInsPgidNotBetween(String value1, String value2) {
      addCriterion("INS_PGID not between", value1, value2, "insPgid");
      return (Criteria) this;
    }

    public Criteria andInsYmdIsNull() {
      addCriterion("INS_YMD is null");
      return (Criteria) this;
    }

    public Criteria andInsYmdIsNotNull() {
      addCriterion("INS_YMD is not null");
      return (Criteria) this;
    }

    public Criteria andInsYmdEqualTo(String value) {
      addCriterion("INS_YMD =", value, "insYmd");
      return (Criteria) this;
    }

    public Criteria andInsYmdNotEqualTo(String value) {
      addCriterion("INS_YMD <>", value, "insYmd");
      return (Criteria) this;
    }

    public Criteria andInsYmdGreaterThan(String value) {
      addCriterion("INS_YMD >", value, "insYmd");
      return (Criteria) this;
    }

    public Criteria andInsYmdGreaterThanOrEqualTo(String value) {
      addCriterion("INS_YMD >=", value, "insYmd");
      return (Criteria) this;
    }

    public Criteria andInsYmdLessThan(String value) {
      addCriterion("INS_YMD <", value, "insYmd");
      return (Criteria) this;
    }

    public Criteria andInsYmdLessThanOrEqualTo(String value) {
      addCriterion("INS_YMD <=", value, "insYmd");
      return (Criteria) this;
    }

    public Criteria andInsYmdLike(String value) {
      addCriterion("INS_YMD like", value, "insYmd");
      return (Criteria) this;
    }

    public Criteria andInsYmdNotLike(String value) {
      addCriterion("INS_YMD not like", value, "insYmd");
      return (Criteria) this;
    }

    public Criteria andInsYmdIn(List<String> values) {
      addCriterion("INS_YMD in", values, "insYmd");
      return (Criteria) this;
    }

    public Criteria andInsYmdNotIn(List<String> values) {
      addCriterion("INS_YMD not in", values, "insYmd");
      return (Criteria) this;
    }

    public Criteria andInsYmdBetween(String value1, String value2) {
      addCriterion("INS_YMD between", value1, value2, "insYmd");
      return (Criteria) this;
    }

    public Criteria andInsYmdNotBetween(String value1, String value2) {
      addCriterion("INS_YMD not between", value1, value2, "insYmd");
      return (Criteria) this;
    }

    public Criteria andInsTimeIsNull() {
      addCriterion("INS_TIME is null");
      return (Criteria) this;
    }

    public Criteria andInsTimeIsNotNull() {
      addCriterion("INS_TIME is not null");
      return (Criteria) this;
    }

    public Criteria andInsTimeEqualTo(String value) {
      addCriterion("INS_TIME =", value, "insTime");
      return (Criteria) this;
    }

    public Criteria andInsTimeNotEqualTo(String value) {
      addCriterion("INS_TIME <>", value, "insTime");
      return (Criteria) this;
    }

    public Criteria andInsTimeGreaterThan(String value) {
      addCriterion("INS_TIME >", value, "insTime");
      return (Criteria) this;
    }

    public Criteria andInsTimeGreaterThanOrEqualTo(String value) {
      addCriterion("INS_TIME >=", value, "insTime");
      return (Criteria) this;
    }

    public Criteria andInsTimeLessThan(String value) {
      addCriterion("INS_TIME <", value, "insTime");
      return (Criteria) this;
    }

    public Criteria andInsTimeLessThanOrEqualTo(String value) {
      addCriterion("INS_TIME <=", value, "insTime");
      return (Criteria) this;
    }

    public Criteria andInsTimeLike(String value) {
      addCriterion("INS_TIME like", value, "insTime");
      return (Criteria) this;
    }

    public Criteria andInsTimeNotLike(String value) {
      addCriterion("INS_TIME not like", value, "insTime");
      return (Criteria) this;
    }

    public Criteria andInsTimeIn(List<String> values) {
      addCriterion("INS_TIME in", values, "insTime");
      return (Criteria) this;
    }

    public Criteria andInsTimeNotIn(List<String> values) {
      addCriterion("INS_TIME not in", values, "insTime");
      return (Criteria) this;
    }

    public Criteria andInsTimeBetween(String value1, String value2) {
      addCriterion("INS_TIME between", value1, value2, "insTime");
      return (Criteria) this;
    }

    public Criteria andInsTimeNotBetween(String value1, String value2) {
      addCriterion("INS_TIME not between", value1, value2, "insTime");
      return (Criteria) this;
    }

    public Criteria andUpdUseridIsNull() {
      addCriterion("UPD_USERID is null");
      return (Criteria) this;
    }

    public Criteria andUpdUseridIsNotNull() {
      addCriterion("UPD_USERID is not null");
      return (Criteria) this;
    }

    public Criteria andUpdUseridEqualTo(String value) {
      addCriterion("UPD_USERID =", value, "updUserid");
      return (Criteria) this;
    }

    public Criteria andUpdUseridNotEqualTo(String value) {
      addCriterion("UPD_USERID <>", value, "updUserid");
      return (Criteria) this;
    }

    public Criteria andUpdUseridGreaterThan(String value) {
      addCriterion("UPD_USERID >", value, "updUserid");
      return (Criteria) this;
    }

    public Criteria andUpdUseridGreaterThanOrEqualTo(String value) {
      addCriterion("UPD_USERID >=", value, "updUserid");
      return (Criteria) this;
    }

    public Criteria andUpdUseridLessThan(String value) {
      addCriterion("UPD_USERID <", value, "updUserid");
      return (Criteria) this;
    }

    public Criteria andUpdUseridLessThanOrEqualTo(String value) {
      addCriterion("UPD_USERID <=", value, "updUserid");
      return (Criteria) this;
    }

    public Criteria andUpdUseridLike(String value) {
      addCriterion("UPD_USERID like", value, "updUserid");
      return (Criteria) this;
    }

    public Criteria andUpdUseridNotLike(String value) {
      addCriterion("UPD_USERID not like", value, "updUserid");
      return (Criteria) this;
    }

    public Criteria andUpdUseridIn(List<String> values) {
      addCriterion("UPD_USERID in", values, "updUserid");
      return (Criteria) this;
    }

    public Criteria andUpdUseridNotIn(List<String> values) {
      addCriterion("UPD_USERID not in", values, "updUserid");
      return (Criteria) this;
    }

    public Criteria andUpdUseridBetween(String value1, String value2) {
      addCriterion("UPD_USERID between", value1, value2, "updUserid");
      return (Criteria) this;
    }

    public Criteria andUpdUseridNotBetween(String value1, String value2) {
      addCriterion("UPD_USERID not between", value1, value2, "updUserid");
      return (Criteria) this;
    }

    public Criteria andUpdPgidIsNull() {
      addCriterion("UPD_PGID is null");
      return (Criteria) this;
    }

    public Criteria andUpdPgidIsNotNull() {
      addCriterion("UPD_PGID is not null");
      return (Criteria) this;
    }

    public Criteria andUpdPgidEqualTo(String value) {
      addCriterion("UPD_PGID =", value, "updPgid");
      return (Criteria) this;
    }

    public Criteria andUpdPgidNotEqualTo(String value) {
      addCriterion("UPD_PGID <>", value, "updPgid");
      return (Criteria) this;
    }

    public Criteria andUpdPgidGreaterThan(String value) {
      addCriterion("UPD_PGID >", value, "updPgid");
      return (Criteria) this;
    }

    public Criteria andUpdPgidGreaterThanOrEqualTo(String value) {
      addCriterion("UPD_PGID >=", value, "updPgid");
      return (Criteria) this;
    }

    public Criteria andUpdPgidLessThan(String value) {
      addCriterion("UPD_PGID <", value, "updPgid");
      return (Criteria) this;
    }

    public Criteria andUpdPgidLessThanOrEqualTo(String value) {
      addCriterion("UPD_PGID <=", value, "updPgid");
      return (Criteria) this;
    }

    public Criteria andUpdPgidLike(String value) {
      addCriterion("UPD_PGID like", value, "updPgid");
      return (Criteria) this;
    }

    public Criteria andUpdPgidNotLike(String value) {
      addCriterion("UPD_PGID not like", value, "updPgid");
      return (Criteria) this;
    }

    public Criteria andUpdPgidIn(List<String> values) {
      addCriterion("UPD_PGID in", values, "updPgid");
      return (Criteria) this;
    }

    public Criteria andUpdPgidNotIn(List<String> values) {
      addCriterion("UPD_PGID not in", values, "updPgid");
      return (Criteria) this;
    }

    public Criteria andUpdPgidBetween(String value1, String value2) {
      addCriterion("UPD_PGID between", value1, value2, "updPgid");
      return (Criteria) this;
    }

    public Criteria andUpdPgidNotBetween(String value1, String value2) {
      addCriterion("UPD_PGID not between", value1, value2, "updPgid");
      return (Criteria) this;
    }

    public Criteria andUpdYmdIsNull() {
      addCriterion("UPD_YMD is null");
      return (Criteria) this;
    }

    public Criteria andUpdYmdIsNotNull() {
      addCriterion("UPD_YMD is not null");
      return (Criteria) this;
    }

    public Criteria andUpdYmdEqualTo(String value) {
      addCriterion("UPD_YMD =", value, "updYmd");
      return (Criteria) this;
    }

    public Criteria andUpdYmdNotEqualTo(String value) {
      addCriterion("UPD_YMD <>", value, "updYmd");
      return (Criteria) this;
    }

    public Criteria andUpdYmdGreaterThan(String value) {
      addCriterion("UPD_YMD >", value, "updYmd");
      return (Criteria) this;
    }

    public Criteria andUpdYmdGreaterThanOrEqualTo(String value) {
      addCriterion("UPD_YMD >=", value, "updYmd");
      return (Criteria) this;
    }

    public Criteria andUpdYmdLessThan(String value) {
      addCriterion("UPD_YMD <", value, "updYmd");
      return (Criteria) this;
    }

    public Criteria andUpdYmdLessThanOrEqualTo(String value) {
      addCriterion("UPD_YMD <=", value, "updYmd");
      return (Criteria) this;
    }

    public Criteria andUpdYmdLike(String value) {
      addCriterion("UPD_YMD like", value, "updYmd");
      return (Criteria) this;
    }

    public Criteria andUpdYmdNotLike(String value) {
      addCriterion("UPD_YMD not like", value, "updYmd");
      return (Criteria) this;
    }

    public Criteria andUpdYmdIn(List<String> values) {
      addCriterion("UPD_YMD in", values, "updYmd");
      return (Criteria) this;
    }

    public Criteria andUpdYmdNotIn(List<String> values) {
      addCriterion("UPD_YMD not in", values, "updYmd");
      return (Criteria) this;
    }

    public Criteria andUpdYmdBetween(String value1, String value2) {
      addCriterion("UPD_YMD between", value1, value2, "updYmd");
      return (Criteria) this;
    }

    public Criteria andUpdYmdNotBetween(String value1, String value2) {
      addCriterion("UPD_YMD not between", value1, value2, "updYmd");
      return (Criteria) this;
    }

    public Criteria andUpdTimeIsNull() {
      addCriterion("UPD_TIME is null");
      return (Criteria) this;
    }

    public Criteria andUpdTimeIsNotNull() {
      addCriterion("UPD_TIME is not null");
      return (Criteria) this;
    }

    public Criteria andUpdTimeEqualTo(String value) {
      addCriterion("UPD_TIME =", value, "updTime");
      return (Criteria) this;
    }

    public Criteria andUpdTimeNotEqualTo(String value) {
      addCriterion("UPD_TIME <>", value, "updTime");
      return (Criteria) this;
    }

    public Criteria andUpdTimeGreaterThan(String value) {
      addCriterion("UPD_TIME >", value, "updTime");
      return (Criteria) this;
    }

    public Criteria andUpdTimeGreaterThanOrEqualTo(String value) {
      addCriterion("UPD_TIME >=", value, "updTime");
      return (Criteria) this;
    }

    public Criteria andUpdTimeLessThan(String value) {
      addCriterion("UPD_TIME <", value, "updTime");
      return (Criteria) this;
    }

    public Criteria andUpdTimeLessThanOrEqualTo(String value) {
      addCriterion("UPD_TIME <=", value, "updTime");
      return (Criteria) this;
    }

    public Criteria andUpdTimeLike(String value) {
      addCriterion("UPD_TIME like", value, "updTime");
      return (Criteria) this;
    }

    public Criteria andUpdTimeNotLike(String value) {
      addCriterion("UPD_TIME not like", value, "updTime");
      return (Criteria) this;
    }

    public Criteria andUpdTimeIn(List<String> values) {
      addCriterion("UPD_TIME in", values, "updTime");
      return (Criteria) this;
    }

    public Criteria andUpdTimeNotIn(List<String> values) {
      addCriterion("UPD_TIME not in", values, "updTime");
      return (Criteria) this;
    }

    public Criteria andUpdTimeBetween(String value1, String value2) {
      addCriterion("UPD_TIME between", value1, value2, "updTime");
      return (Criteria) this;
    }

    public Criteria andUpdTimeNotBetween(String value1, String value2) {
      addCriterion("UPD_TIME not between", value1, value2, "updTime");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table MST_LIST_DIST
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public static class Criterion {

    private String condition;
    private Object value;
    private Object secondValue;
    private boolean noValue;
    private boolean singleValue;
    private boolean betweenValue;
    private boolean listValue;
    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue,
        String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MST_LIST_DIST
     *
     * @mbggenerated do_not_delete_during_merge Thu Sep 17 21:03:29 JST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}