package jp.co.daitoku_sh.dfcm.common.db.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class MstSSeihnExample {
    /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table MST_S_SEIHN
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  protected String orderByClause;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table MST_S_SEIHN
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  protected boolean distinct;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table MST_S_SEIHN
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_S_SEIHN
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public MstSSeihnExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_S_SEIHN
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_S_SEIHN
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_S_SEIHN
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_S_SEIHN
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_S_SEIHN
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_S_SEIHN
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_S_SEIHN
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_S_SEIHN
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_S_SEIHN
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table MST_S_SEIHN
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table MST_S_SEIHN
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  protected abstract static class GeneratedCriteria {

    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value,
        String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2,
        String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property
            + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andEndymdIsNull() {
      addCriterion("ENDYMD is null");
      return (Criteria) this;
    }

    public Criteria andEndymdIsNotNull() {
      addCriterion("ENDYMD is not null");
      return (Criteria) this;
    }

    public Criteria andEndymdEqualTo(Integer value) {
      addCriterion("ENDYMD =", value, "endymd");
      return (Criteria) this;
    }

    public Criteria andEndymdNotEqualTo(Integer value) {
      addCriterion("ENDYMD <>", value, "endymd");
      return (Criteria) this;
    }

    public Criteria andEndymdGreaterThan(Integer value) {
      addCriterion("ENDYMD >", value, "endymd");
      return (Criteria) this;
    }

    public Criteria andEndymdGreaterThanOrEqualTo(Integer value) {
      addCriterion("ENDYMD >=", value, "endymd");
      return (Criteria) this;
    }

    public Criteria andEndymdLessThan(Integer value) {
      addCriterion("ENDYMD <", value, "endymd");
      return (Criteria) this;
    }

    public Criteria andEndymdLessThanOrEqualTo(Integer value) {
      addCriterion("ENDYMD <=", value, "endymd");
      return (Criteria) this;
    }

    public Criteria andEndymdIn(List<Integer> values) {
      addCriterion("ENDYMD in", values, "endymd");
      return (Criteria) this;
    }

    public Criteria andEndymdNotIn(List<Integer> values) {
      addCriterion("ENDYMD not in", values, "endymd");
      return (Criteria) this;
    }

    public Criteria andEndymdBetween(Integer value1, Integer value2) {
      addCriterion("ENDYMD between", value1, value2, "endymd");
      return (Criteria) this;
    }

    public Criteria andEndymdNotBetween(Integer value1, Integer value2) {
      addCriterion("ENDYMD not between", value1, value2, "endymd");
      return (Criteria) this;
    }

    public Criteria andEndbinIsNull() {
      addCriterion("ENDBIN is null");
      return (Criteria) this;
    }

    public Criteria andEndbinIsNotNull() {
      addCriterion("ENDBIN is not null");
      return (Criteria) this;
    }

    public Criteria andEndbinEqualTo(Short value) {
      addCriterion("ENDBIN =", value, "endbin");
      return (Criteria) this;
    }

    public Criteria andEndbinNotEqualTo(Short value) {
      addCriterion("ENDBIN <>", value, "endbin");
      return (Criteria) this;
    }

    public Criteria andEndbinGreaterThan(Short value) {
      addCriterion("ENDBIN >", value, "endbin");
      return (Criteria) this;
    }

    public Criteria andEndbinGreaterThanOrEqualTo(Short value) {
      addCriterion("ENDBIN >=", value, "endbin");
      return (Criteria) this;
    }

    public Criteria andEndbinLessThan(Short value) {
      addCriterion("ENDBIN <", value, "endbin");
      return (Criteria) this;
    }

    public Criteria andEndbinLessThanOrEqualTo(Short value) {
      addCriterion("ENDBIN <=", value, "endbin");
      return (Criteria) this;
    }

    public Criteria andEndbinIn(List<Short> values) {
      addCriterion("ENDBIN in", values, "endbin");
      return (Criteria) this;
    }

    public Criteria andEndbinNotIn(List<Short> values) {
      addCriterion("ENDBIN not in", values, "endbin");
      return (Criteria) this;
    }

    public Criteria andEndbinBetween(Short value1, Short value2) {
      addCriterion("ENDBIN between", value1, value2, "endbin");
      return (Criteria) this;
    }

    public Criteria andEndbinNotBetween(Short value1, Short value2) {
      addCriterion("ENDBIN not between", value1, value2, "endbin");
      return (Criteria) this;
    }

    public Criteria andHincdIsNull() {
      addCriterion("HINCD is null");
      return (Criteria) this;
    }

    public Criteria andHincdIsNotNull() {
      addCriterion("HINCD is not null");
      return (Criteria) this;
    }

    public Criteria andHincdEqualTo(String value) {
      addCriterion("HINCD =", value, "hincd");
      return (Criteria) this;
    }

    public Criteria andHincdNotEqualTo(String value) {
      addCriterion("HINCD <>", value, "hincd");
      return (Criteria) this;
    }

    public Criteria andHincdGreaterThan(String value) {
      addCriterion("HINCD >", value, "hincd");
      return (Criteria) this;
    }

    public Criteria andHincdGreaterThanOrEqualTo(String value) {
      addCriterion("HINCD >=", value, "hincd");
      return (Criteria) this;
    }

    public Criteria andHincdLessThan(String value) {
      addCriterion("HINCD <", value, "hincd");
      return (Criteria) this;
    }

    public Criteria andHincdLessThanOrEqualTo(String value) {
      addCriterion("HINCD <=", value, "hincd");
      return (Criteria) this;
    }

    public Criteria andHincdLike(String value) {
      addCriterion("HINCD like", value, "hincd");
      return (Criteria) this;
    }

    public Criteria andHincdNotLike(String value) {
      addCriterion("HINCD not like", value, "hincd");
      return (Criteria) this;
    }

    public Criteria andHincdIn(List<String> values) {
      addCriterion("HINCD in", values, "hincd");
      return (Criteria) this;
    }

    public Criteria andHincdNotIn(List<String> values) {
      addCriterion("HINCD not in", values, "hincd");
      return (Criteria) this;
    }

    public Criteria andHincdBetween(String value1, String value2) {
      addCriterion("HINCD between", value1, value2, "hincd");
      return (Criteria) this;
    }

    public Criteria andHincdNotBetween(String value1, String value2) {
      addCriterion("HINCD not between", value1, value2, "hincd");
      return (Criteria) this;
    }

    public Criteria andChncdIsNull() {
      addCriterion("CHNCD is null");
      return (Criteria) this;
    }

    public Criteria andChncdIsNotNull() {
      addCriterion("CHNCD is not null");
      return (Criteria) this;
    }

    public Criteria andChncdEqualTo(Short value) {
      addCriterion("CHNCD =", value, "chncd");
      return (Criteria) this;
    }

    public Criteria andChncdNotEqualTo(Short value) {
      addCriterion("CHNCD <>", value, "chncd");
      return (Criteria) this;
    }

    public Criteria andChncdGreaterThan(Short value) {
      addCriterion("CHNCD >", value, "chncd");
      return (Criteria) this;
    }

    public Criteria andChncdGreaterThanOrEqualTo(Short value) {
      addCriterion("CHNCD >=", value, "chncd");
      return (Criteria) this;
    }

    public Criteria andChncdLessThan(Short value) {
      addCriterion("CHNCD <", value, "chncd");
      return (Criteria) this;
    }

    public Criteria andChncdLessThanOrEqualTo(Short value) {
      addCriterion("CHNCD <=", value, "chncd");
      return (Criteria) this;
    }

    public Criteria andChncdIn(List<Short> values) {
      addCriterion("CHNCD in", values, "chncd");
      return (Criteria) this;
    }

    public Criteria andChncdNotIn(List<Short> values) {
      addCriterion("CHNCD not in", values, "chncd");
      return (Criteria) this;
    }

    public Criteria andChncdBetween(Short value1, Short value2) {
      addCriterion("CHNCD between", value1, value2, "chncd");
      return (Criteria) this;
    }

    public Criteria andChncdNotBetween(Short value1, Short value2) {
      addCriterion("CHNCD not between", value1, value2, "chncd");
      return (Criteria) this;
    }

    public Criteria andChnedaIsNull() {
      addCriterion("CHNEDA is null");
      return (Criteria) this;
    }

    public Criteria andChnedaIsNotNull() {
      addCriterion("CHNEDA is not null");
      return (Criteria) this;
    }

    public Criteria andChnedaEqualTo(Short value) {
      addCriterion("CHNEDA =", value, "chneda");
      return (Criteria) this;
    }

    public Criteria andChnedaNotEqualTo(Short value) {
      addCriterion("CHNEDA <>", value, "chneda");
      return (Criteria) this;
    }

    public Criteria andChnedaGreaterThan(Short value) {
      addCriterion("CHNEDA >", value, "chneda");
      return (Criteria) this;
    }

    public Criteria andChnedaGreaterThanOrEqualTo(Short value) {
      addCriterion("CHNEDA >=", value, "chneda");
      return (Criteria) this;
    }

    public Criteria andChnedaLessThan(Short value) {
      addCriterion("CHNEDA <", value, "chneda");
      return (Criteria) this;
    }

    public Criteria andChnedaLessThanOrEqualTo(Short value) {
      addCriterion("CHNEDA <=", value, "chneda");
      return (Criteria) this;
    }

    public Criteria andChnedaIn(List<Short> values) {
      addCriterion("CHNEDA in", values, "chneda");
      return (Criteria) this;
    }

    public Criteria andChnedaNotIn(List<Short> values) {
      addCriterion("CHNEDA not in", values, "chneda");
      return (Criteria) this;
    }

    public Criteria andChnedaBetween(Short value1, Short value2) {
      addCriterion("CHNEDA between", value1, value2, "chneda");
      return (Criteria) this;
    }

    public Criteria andChnedaNotBetween(Short value1, Short value2) {
      addCriterion("CHNEDA not between", value1, value2, "chneda");
      return (Criteria) this;
    }

    public Criteria andInpymdIsNull() {
      addCriterion("INPYMD is null");
      return (Criteria) this;
    }

    public Criteria andInpymdIsNotNull() {
      addCriterion("INPYMD is not null");
      return (Criteria) this;
    }

    public Criteria andInpymdEqualTo(Integer value) {
      addCriterion("INPYMD =", value, "inpymd");
      return (Criteria) this;
    }

    public Criteria andInpymdNotEqualTo(Integer value) {
      addCriterion("INPYMD <>", value, "inpymd");
      return (Criteria) this;
    }

    public Criteria andInpymdGreaterThan(Integer value) {
      addCriterion("INPYMD >", value, "inpymd");
      return (Criteria) this;
    }

    public Criteria andInpymdGreaterThanOrEqualTo(Integer value) {
      addCriterion("INPYMD >=", value, "inpymd");
      return (Criteria) this;
    }

    public Criteria andInpymdLessThan(Integer value) {
      addCriterion("INPYMD <", value, "inpymd");
      return (Criteria) this;
    }

    public Criteria andInpymdLessThanOrEqualTo(Integer value) {
      addCriterion("INPYMD <=", value, "inpymd");
      return (Criteria) this;
    }

    public Criteria andInpymdIn(List<Integer> values) {
      addCriterion("INPYMD in", values, "inpymd");
      return (Criteria) this;
    }

    public Criteria andInpymdNotIn(List<Integer> values) {
      addCriterion("INPYMD not in", values, "inpymd");
      return (Criteria) this;
    }

    public Criteria andInpymdBetween(Integer value1, Integer value2) {
      addCriterion("INPYMD between", value1, value2, "inpymd");
      return (Criteria) this;
    }

    public Criteria andInpymdNotBetween(Integer value1, Integer value2) {
      addCriterion("INPYMD not between", value1, value2, "inpymd");
      return (Criteria) this;
    }

    public Criteria andInptimIsNull() {
      addCriterion("INPTIM is null");
      return (Criteria) this;
    }

    public Criteria andInptimIsNotNull() {
      addCriterion("INPTIM is not null");
      return (Criteria) this;
    }

    public Criteria andInptimEqualTo(Integer value) {
      addCriterion("INPTIM =", value, "inptim");
      return (Criteria) this;
    }

    public Criteria andInptimNotEqualTo(Integer value) {
      addCriterion("INPTIM <>", value, "inptim");
      return (Criteria) this;
    }

    public Criteria andInptimGreaterThan(Integer value) {
      addCriterion("INPTIM >", value, "inptim");
      return (Criteria) this;
    }

    public Criteria andInptimGreaterThanOrEqualTo(Integer value) {
      addCriterion("INPTIM >=", value, "inptim");
      return (Criteria) this;
    }

    public Criteria andInptimLessThan(Integer value) {
      addCriterion("INPTIM <", value, "inptim");
      return (Criteria) this;
    }

    public Criteria andInptimLessThanOrEqualTo(Integer value) {
      addCriterion("INPTIM <=", value, "inptim");
      return (Criteria) this;
    }

    public Criteria andInptimIn(List<Integer> values) {
      addCriterion("INPTIM in", values, "inptim");
      return (Criteria) this;
    }

    public Criteria andInptimNotIn(List<Integer> values) {
      addCriterion("INPTIM not in", values, "inptim");
      return (Criteria) this;
    }

    public Criteria andInptimBetween(Integer value1, Integer value2) {
      addCriterion("INPTIM between", value1, value2, "inptim");
      return (Criteria) this;
    }

    public Criteria andInptimNotBetween(Integer value1, Integer value2) {
      addCriterion("INPTIM not between", value1, value2, "inptim");
      return (Criteria) this;
    }

    public Criteria andInpusrIsNull() {
      addCriterion("INPUSR is null");
      return (Criteria) this;
    }

    public Criteria andInpusrIsNotNull() {
      addCriterion("INPUSR is not null");
      return (Criteria) this;
    }

    public Criteria andInpusrEqualTo(String value) {
      addCriterion("INPUSR =", value, "inpusr");
      return (Criteria) this;
    }

    public Criteria andInpusrNotEqualTo(String value) {
      addCriterion("INPUSR <>", value, "inpusr");
      return (Criteria) this;
    }

    public Criteria andInpusrGreaterThan(String value) {
      addCriterion("INPUSR >", value, "inpusr");
      return (Criteria) this;
    }

    public Criteria andInpusrGreaterThanOrEqualTo(String value) {
      addCriterion("INPUSR >=", value, "inpusr");
      return (Criteria) this;
    }

    public Criteria andInpusrLessThan(String value) {
      addCriterion("INPUSR <", value, "inpusr");
      return (Criteria) this;
    }

    public Criteria andInpusrLessThanOrEqualTo(String value) {
      addCriterion("INPUSR <=", value, "inpusr");
      return (Criteria) this;
    }

    public Criteria andInpusrLike(String value) {
      addCriterion("INPUSR like", value, "inpusr");
      return (Criteria) this;
    }

    public Criteria andInpusrNotLike(String value) {
      addCriterion("INPUSR not like", value, "inpusr");
      return (Criteria) this;
    }

    public Criteria andInpusrIn(List<String> values) {
      addCriterion("INPUSR in", values, "inpusr");
      return (Criteria) this;
    }

    public Criteria andInpusrNotIn(List<String> values) {
      addCriterion("INPUSR not in", values, "inpusr");
      return (Criteria) this;
    }

    public Criteria andInpusrBetween(String value1, String value2) {
      addCriterion("INPUSR between", value1, value2, "inpusr");
      return (Criteria) this;
    }

    public Criteria andInpusrNotBetween(String value1, String value2) {
      addCriterion("INPUSR not between", value1, value2, "inpusr");
      return (Criteria) this;
    }

    public Criteria andUpdymdIsNull() {
      addCriterion("UPDYMD is null");
      return (Criteria) this;
    }

    public Criteria andUpdymdIsNotNull() {
      addCriterion("UPDYMD is not null");
      return (Criteria) this;
    }

    public Criteria andUpdymdEqualTo(Integer value) {
      addCriterion("UPDYMD =", value, "updymd");
      return (Criteria) this;
    }

    public Criteria andUpdymdNotEqualTo(Integer value) {
      addCriterion("UPDYMD <>", value, "updymd");
      return (Criteria) this;
    }

    public Criteria andUpdymdGreaterThan(Integer value) {
      addCriterion("UPDYMD >", value, "updymd");
      return (Criteria) this;
    }

    public Criteria andUpdymdGreaterThanOrEqualTo(Integer value) {
      addCriterion("UPDYMD >=", value, "updymd");
      return (Criteria) this;
    }

    public Criteria andUpdymdLessThan(Integer value) {
      addCriterion("UPDYMD <", value, "updymd");
      return (Criteria) this;
    }

    public Criteria andUpdymdLessThanOrEqualTo(Integer value) {
      addCriterion("UPDYMD <=", value, "updymd");
      return (Criteria) this;
    }

    public Criteria andUpdymdIn(List<Integer> values) {
      addCriterion("UPDYMD in", values, "updymd");
      return (Criteria) this;
    }

    public Criteria andUpdymdNotIn(List<Integer> values) {
      addCriterion("UPDYMD not in", values, "updymd");
      return (Criteria) this;
    }

    public Criteria andUpdymdBetween(Integer value1, Integer value2) {
      addCriterion("UPDYMD between", value1, value2, "updymd");
      return (Criteria) this;
    }

    public Criteria andUpdymdNotBetween(Integer value1, Integer value2) {
      addCriterion("UPDYMD not between", value1, value2, "updymd");
      return (Criteria) this;
    }

    public Criteria andUpdtimIsNull() {
      addCriterion("UPDTIM is null");
      return (Criteria) this;
    }

    public Criteria andUpdtimIsNotNull() {
      addCriterion("UPDTIM is not null");
      return (Criteria) this;
    }

    public Criteria andUpdtimEqualTo(Integer value) {
      addCriterion("UPDTIM =", value, "updtim");
      return (Criteria) this;
    }

    public Criteria andUpdtimNotEqualTo(Integer value) {
      addCriterion("UPDTIM <>", value, "updtim");
      return (Criteria) this;
    }

    public Criteria andUpdtimGreaterThan(Integer value) {
      addCriterion("UPDTIM >", value, "updtim");
      return (Criteria) this;
    }

    public Criteria andUpdtimGreaterThanOrEqualTo(Integer value) {
      addCriterion("UPDTIM >=", value, "updtim");
      return (Criteria) this;
    }

    public Criteria andUpdtimLessThan(Integer value) {
      addCriterion("UPDTIM <", value, "updtim");
      return (Criteria) this;
    }

    public Criteria andUpdtimLessThanOrEqualTo(Integer value) {
      addCriterion("UPDTIM <=", value, "updtim");
      return (Criteria) this;
    }

    public Criteria andUpdtimIn(List<Integer> values) {
      addCriterion("UPDTIM in", values, "updtim");
      return (Criteria) this;
    }

    public Criteria andUpdtimNotIn(List<Integer> values) {
      addCriterion("UPDTIM not in", values, "updtim");
      return (Criteria) this;
    }

    public Criteria andUpdtimBetween(Integer value1, Integer value2) {
      addCriterion("UPDTIM between", value1, value2, "updtim");
      return (Criteria) this;
    }

    public Criteria andUpdtimNotBetween(Integer value1, Integer value2) {
      addCriterion("UPDTIM not between", value1, value2, "updtim");
      return (Criteria) this;
    }

    public Criteria andUpdusrIsNull() {
      addCriterion("UPDUSR is null");
      return (Criteria) this;
    }

    public Criteria andUpdusrIsNotNull() {
      addCriterion("UPDUSR is not null");
      return (Criteria) this;
    }

    public Criteria andUpdusrEqualTo(String value) {
      addCriterion("UPDUSR =", value, "updusr");
      return (Criteria) this;
    }

    public Criteria andUpdusrNotEqualTo(String value) {
      addCriterion("UPDUSR <>", value, "updusr");
      return (Criteria) this;
    }

    public Criteria andUpdusrGreaterThan(String value) {
      addCriterion("UPDUSR >", value, "updusr");
      return (Criteria) this;
    }

    public Criteria andUpdusrGreaterThanOrEqualTo(String value) {
      addCriterion("UPDUSR >=", value, "updusr");
      return (Criteria) this;
    }

    public Criteria andUpdusrLessThan(String value) {
      addCriterion("UPDUSR <", value, "updusr");
      return (Criteria) this;
    }

    public Criteria andUpdusrLessThanOrEqualTo(String value) {
      addCriterion("UPDUSR <=", value, "updusr");
      return (Criteria) this;
    }

    public Criteria andUpdusrLike(String value) {
      addCriterion("UPDUSR like", value, "updusr");
      return (Criteria) this;
    }

    public Criteria andUpdusrNotLike(String value) {
      addCriterion("UPDUSR not like", value, "updusr");
      return (Criteria) this;
    }

    public Criteria andUpdusrIn(List<String> values) {
      addCriterion("UPDUSR in", values, "updusr");
      return (Criteria) this;
    }

    public Criteria andUpdusrNotIn(List<String> values) {
      addCriterion("UPDUSR not in", values, "updusr");
      return (Criteria) this;
    }

    public Criteria andUpdusrBetween(String value1, String value2) {
      addCriterion("UPDUSR between", value1, value2, "updusr");
      return (Criteria) this;
    }

    public Criteria andUpdusrNotBetween(String value1, String value2) {
      addCriterion("UPDUSR not between", value1, value2, "updusr");
      return (Criteria) this;
    }

    public Criteria andDelflgIsNull() {
      addCriterion("DELFLG is null");
      return (Criteria) this;
    }

    public Criteria andDelflgIsNotNull() {
      addCriterion("DELFLG is not null");
      return (Criteria) this;
    }

    public Criteria andDelflgEqualTo(Short value) {
      addCriterion("DELFLG =", value, "delflg");
      return (Criteria) this;
    }

    public Criteria andDelflgNotEqualTo(Short value) {
      addCriterion("DELFLG <>", value, "delflg");
      return (Criteria) this;
    }

    public Criteria andDelflgGreaterThan(Short value) {
      addCriterion("DELFLG >", value, "delflg");
      return (Criteria) this;
    }

    public Criteria andDelflgGreaterThanOrEqualTo(Short value) {
      addCriterion("DELFLG >=", value, "delflg");
      return (Criteria) this;
    }

    public Criteria andDelflgLessThan(Short value) {
      addCriterion("DELFLG <", value, "delflg");
      return (Criteria) this;
    }

    public Criteria andDelflgLessThanOrEqualTo(Short value) {
      addCriterion("DELFLG <=", value, "delflg");
      return (Criteria) this;
    }

    public Criteria andDelflgIn(List<Short> values) {
      addCriterion("DELFLG in", values, "delflg");
      return (Criteria) this;
    }

    public Criteria andDelflgNotIn(List<Short> values) {
      addCriterion("DELFLG not in", values, "delflg");
      return (Criteria) this;
    }

    public Criteria andDelflgBetween(Short value1, Short value2) {
      addCriterion("DELFLG between", value1, value2, "delflg");
      return (Criteria) this;
    }

    public Criteria andDelflgNotBetween(Short value1, Short value2) {
      addCriterion("DELFLG not between", value1, value2, "delflg");
      return (Criteria) this;
    }

    public Criteria andStrymdIsNull() {
      addCriterion("STRYMD is null");
      return (Criteria) this;
    }

    public Criteria andStrymdIsNotNull() {
      addCriterion("STRYMD is not null");
      return (Criteria) this;
    }

    public Criteria andStrymdEqualTo(Integer value) {
      addCriterion("STRYMD =", value, "strymd");
      return (Criteria) this;
    }

    public Criteria andStrymdNotEqualTo(Integer value) {
      addCriterion("STRYMD <>", value, "strymd");
      return (Criteria) this;
    }

    public Criteria andStrymdGreaterThan(Integer value) {
      addCriterion("STRYMD >", value, "strymd");
      return (Criteria) this;
    }

    public Criteria andStrymdGreaterThanOrEqualTo(Integer value) {
      addCriterion("STRYMD >=", value, "strymd");
      return (Criteria) this;
    }

    public Criteria andStrymdLessThan(Integer value) {
      addCriterion("STRYMD <", value, "strymd");
      return (Criteria) this;
    }

    public Criteria andStrymdLessThanOrEqualTo(Integer value) {
      addCriterion("STRYMD <=", value, "strymd");
      return (Criteria) this;
    }

    public Criteria andStrymdIn(List<Integer> values) {
      addCriterion("STRYMD in", values, "strymd");
      return (Criteria) this;
    }

    public Criteria andStrymdNotIn(List<Integer> values) {
      addCriterion("STRYMD not in", values, "strymd");
      return (Criteria) this;
    }

    public Criteria andStrymdBetween(Integer value1, Integer value2) {
      addCriterion("STRYMD between", value1, value2, "strymd");
      return (Criteria) this;
    }

    public Criteria andStrymdNotBetween(Integer value1, Integer value2) {
      addCriterion("STRYMD not between", value1, value2, "strymd");
      return (Criteria) this;
    }

    public Criteria andStrbinIsNull() {
      addCriterion("STRBIN is null");
      return (Criteria) this;
    }

    public Criteria andStrbinIsNotNull() {
      addCriterion("STRBIN is not null");
      return (Criteria) this;
    }

    public Criteria andStrbinEqualTo(Short value) {
      addCriterion("STRBIN =", value, "strbin");
      return (Criteria) this;
    }

    public Criteria andStrbinNotEqualTo(Short value) {
      addCriterion("STRBIN <>", value, "strbin");
      return (Criteria) this;
    }

    public Criteria andStrbinGreaterThan(Short value) {
      addCriterion("STRBIN >", value, "strbin");
      return (Criteria) this;
    }

    public Criteria andStrbinGreaterThanOrEqualTo(Short value) {
      addCriterion("STRBIN >=", value, "strbin");
      return (Criteria) this;
    }

    public Criteria andStrbinLessThan(Short value) {
      addCriterion("STRBIN <", value, "strbin");
      return (Criteria) this;
    }

    public Criteria andStrbinLessThanOrEqualTo(Short value) {
      addCriterion("STRBIN <=", value, "strbin");
      return (Criteria) this;
    }

    public Criteria andStrbinIn(List<Short> values) {
      addCriterion("STRBIN in", values, "strbin");
      return (Criteria) this;
    }

    public Criteria andStrbinNotIn(List<Short> values) {
      addCriterion("STRBIN not in", values, "strbin");
      return (Criteria) this;
    }

    public Criteria andStrbinBetween(Short value1, Short value2) {
      addCriterion("STRBIN between", value1, value2, "strbin");
      return (Criteria) this;
    }

    public Criteria andStrbinNotBetween(Short value1, Short value2) {
      addCriterion("STRBIN not between", value1, value2, "strbin");
      return (Criteria) this;
    }

    public Criteria andHinmeiIsNull() {
      addCriterion("HINMEI is null");
      return (Criteria) this;
    }

    public Criteria andHinmeiIsNotNull() {
      addCriterion("HINMEI is not null");
      return (Criteria) this;
    }

    public Criteria andHinmeiEqualTo(String value) {
      addCriterion("HINMEI =", value, "hinmei");
      return (Criteria) this;
    }

    public Criteria andHinmeiNotEqualTo(String value) {
      addCriterion("HINMEI <>", value, "hinmei");
      return (Criteria) this;
    }

    public Criteria andHinmeiGreaterThan(String value) {
      addCriterion("HINMEI >", value, "hinmei");
      return (Criteria) this;
    }

    public Criteria andHinmeiGreaterThanOrEqualTo(String value) {
      addCriterion("HINMEI >=", value, "hinmei");
      return (Criteria) this;
    }

    public Criteria andHinmeiLessThan(String value) {
      addCriterion("HINMEI <", value, "hinmei");
      return (Criteria) this;
    }

    public Criteria andHinmeiLessThanOrEqualTo(String value) {
      addCriterion("HINMEI <=", value, "hinmei");
      return (Criteria) this;
    }

    public Criteria andHinmeiLike(String value) {
      addCriterion("HINMEI like", value, "hinmei");
      return (Criteria) this;
    }

    public Criteria andHinmeiNotLike(String value) {
      addCriterion("HINMEI not like", value, "hinmei");
      return (Criteria) this;
    }

    public Criteria andHinmeiIn(List<String> values) {
      addCriterion("HINMEI in", values, "hinmei");
      return (Criteria) this;
    }

    public Criteria andHinmeiNotIn(List<String> values) {
      addCriterion("HINMEI not in", values, "hinmei");
      return (Criteria) this;
    }

    public Criteria andHinmeiBetween(String value1, String value2) {
      addCriterion("HINMEI between", value1, value2, "hinmei");
      return (Criteria) this;
    }

    public Criteria andHinmeiNotBetween(String value1, String value2) {
      addCriterion("HINMEI not between", value1, value2, "hinmei");
      return (Criteria) this;
    }

    public Criteria andHinkanaIsNull() {
      addCriterion("HINKANA is null");
      return (Criteria) this;
    }

    public Criteria andHinkanaIsNotNull() {
      addCriterion("HINKANA is not null");
      return (Criteria) this;
    }

    public Criteria andHinkanaEqualTo(String value) {
      addCriterion("HINKANA =", value, "hinkana");
      return (Criteria) this;
    }

    public Criteria andHinkanaNotEqualTo(String value) {
      addCriterion("HINKANA <>", value, "hinkana");
      return (Criteria) this;
    }

    public Criteria andHinkanaGreaterThan(String value) {
      addCriterion("HINKANA >", value, "hinkana");
      return (Criteria) this;
    }

    public Criteria andHinkanaGreaterThanOrEqualTo(String value) {
      addCriterion("HINKANA >=", value, "hinkana");
      return (Criteria) this;
    }

    public Criteria andHinkanaLessThan(String value) {
      addCriterion("HINKANA <", value, "hinkana");
      return (Criteria) this;
    }

    public Criteria andHinkanaLessThanOrEqualTo(String value) {
      addCriterion("HINKANA <=", value, "hinkana");
      return (Criteria) this;
    }

    public Criteria andHinkanaLike(String value) {
      addCriterion("HINKANA like", value, "hinkana");
      return (Criteria) this;
    }

    public Criteria andHinkanaNotLike(String value) {
      addCriterion("HINKANA not like", value, "hinkana");
      return (Criteria) this;
    }

    public Criteria andHinkanaIn(List<String> values) {
      addCriterion("HINKANA in", values, "hinkana");
      return (Criteria) this;
    }

    public Criteria andHinkanaNotIn(List<String> values) {
      addCriterion("HINKANA not in", values, "hinkana");
      return (Criteria) this;
    }

    public Criteria andHinkanaBetween(String value1, String value2) {
      addCriterion("HINKANA between", value1, value2, "hinkana");
      return (Criteria) this;
    }

    public Criteria andHinkanaNotBetween(String value1, String value2) {
      addCriterion("HINKANA not between", value1, value2, "hinkana");
      return (Criteria) this;
    }

    public Criteria andHinryakuIsNull() {
      addCriterion("HINRYAKU is null");
      return (Criteria) this;
    }

    public Criteria andHinryakuIsNotNull() {
      addCriterion("HINRYAKU is not null");
      return (Criteria) this;
    }

    public Criteria andHinryakuEqualTo(String value) {
      addCriterion("HINRYAKU =", value, "hinryaku");
      return (Criteria) this;
    }

    public Criteria andHinryakuNotEqualTo(String value) {
      addCriterion("HINRYAKU <>", value, "hinryaku");
      return (Criteria) this;
    }

    public Criteria andHinryakuGreaterThan(String value) {
      addCriterion("HINRYAKU >", value, "hinryaku");
      return (Criteria) this;
    }

    public Criteria andHinryakuGreaterThanOrEqualTo(String value) {
      addCriterion("HINRYAKU >=", value, "hinryaku");
      return (Criteria) this;
    }

    public Criteria andHinryakuLessThan(String value) {
      addCriterion("HINRYAKU <", value, "hinryaku");
      return (Criteria) this;
    }

    public Criteria andHinryakuLessThanOrEqualTo(String value) {
      addCriterion("HINRYAKU <=", value, "hinryaku");
      return (Criteria) this;
    }

    public Criteria andHinryakuLike(String value) {
      addCriterion("HINRYAKU like", value, "hinryaku");
      return (Criteria) this;
    }

    public Criteria andHinryakuNotLike(String value) {
      addCriterion("HINRYAKU not like", value, "hinryaku");
      return (Criteria) this;
    }

    public Criteria andHinryakuIn(List<String> values) {
      addCriterion("HINRYAKU in", values, "hinryaku");
      return (Criteria) this;
    }

    public Criteria andHinryakuNotIn(List<String> values) {
      addCriterion("HINRYAKU not in", values, "hinryaku");
      return (Criteria) this;
    }

    public Criteria andHinryakuBetween(String value1, String value2) {
      addCriterion("HINRYAKU between", value1, value2, "hinryaku");
      return (Criteria) this;
    }

    public Criteria andHinryakuNotBetween(String value1, String value2) {
      addCriterion("HINRYAKU not between", value1, value2, "hinryaku");
      return (Criteria) this;
    }

    public Criteria andBmncdIsNull() {
      addCriterion("BMNCD is null");
      return (Criteria) this;
    }

    public Criteria andBmncdIsNotNull() {
      addCriterion("BMNCD is not null");
      return (Criteria) this;
    }

    public Criteria andBmncdEqualTo(Short value) {
      addCriterion("BMNCD =", value, "bmncd");
      return (Criteria) this;
    }

    public Criteria andBmncdNotEqualTo(Short value) {
      addCriterion("BMNCD <>", value, "bmncd");
      return (Criteria) this;
    }

    public Criteria andBmncdGreaterThan(Short value) {
      addCriterion("BMNCD >", value, "bmncd");
      return (Criteria) this;
    }

    public Criteria andBmncdGreaterThanOrEqualTo(Short value) {
      addCriterion("BMNCD >=", value, "bmncd");
      return (Criteria) this;
    }

    public Criteria andBmncdLessThan(Short value) {
      addCriterion("BMNCD <", value, "bmncd");
      return (Criteria) this;
    }

    public Criteria andBmncdLessThanOrEqualTo(Short value) {
      addCriterion("BMNCD <=", value, "bmncd");
      return (Criteria) this;
    }

    public Criteria andBmncdIn(List<Short> values) {
      addCriterion("BMNCD in", values, "bmncd");
      return (Criteria) this;
    }

    public Criteria andBmncdNotIn(List<Short> values) {
      addCriterion("BMNCD not in", values, "bmncd");
      return (Criteria) this;
    }

    public Criteria andBmncdBetween(Short value1, Short value2) {
      addCriterion("BMNCD between", value1, value2, "bmncd");
      return (Criteria) this;
    }

    public Criteria andBmncdNotBetween(Short value1, Short value2) {
      addCriterion("BMNCD not between", value1, value2, "bmncd");
      return (Criteria) this;
    }

    public Criteria andSeikeicdIsNull() {
      addCriterion("SEIKEICD is null");
      return (Criteria) this;
    }

    public Criteria andSeikeicdIsNotNull() {
      addCriterion("SEIKEICD is not null");
      return (Criteria) this;
    }

    public Criteria andSeikeicdEqualTo(Short value) {
      addCriterion("SEIKEICD =", value, "seikeicd");
      return (Criteria) this;
    }

    public Criteria andSeikeicdNotEqualTo(Short value) {
      addCriterion("SEIKEICD <>", value, "seikeicd");
      return (Criteria) this;
    }

    public Criteria andSeikeicdGreaterThan(Short value) {
      addCriterion("SEIKEICD >", value, "seikeicd");
      return (Criteria) this;
    }

    public Criteria andSeikeicdGreaterThanOrEqualTo(Short value) {
      addCriterion("SEIKEICD >=", value, "seikeicd");
      return (Criteria) this;
    }

    public Criteria andSeikeicdLessThan(Short value) {
      addCriterion("SEIKEICD <", value, "seikeicd");
      return (Criteria) this;
    }

    public Criteria andSeikeicdLessThanOrEqualTo(Short value) {
      addCriterion("SEIKEICD <=", value, "seikeicd");
      return (Criteria) this;
    }

    public Criteria andSeikeicdIn(List<Short> values) {
      addCriterion("SEIKEICD in", values, "seikeicd");
      return (Criteria) this;
    }

    public Criteria andSeikeicdNotIn(List<Short> values) {
      addCriterion("SEIKEICD not in", values, "seikeicd");
      return (Criteria) this;
    }

    public Criteria andSeikeicdBetween(Short value1, Short value2) {
      addCriterion("SEIKEICD between", value1, value2, "seikeicd");
      return (Criteria) this;
    }

    public Criteria andSeikeicdNotBetween(Short value1, Short value2) {
      addCriterion("SEIKEICD not between", value1, value2, "seikeicd");
      return (Criteria) this;
    }

    public Criteria andOndocdIsNull() {
      addCriterion("ONDOCD is null");
      return (Criteria) this;
    }

    public Criteria andOndocdIsNotNull() {
      addCriterion("ONDOCD is not null");
      return (Criteria) this;
    }

    public Criteria andOndocdEqualTo(Short value) {
      addCriterion("ONDOCD =", value, "ondocd");
      return (Criteria) this;
    }

    public Criteria andOndocdNotEqualTo(Short value) {
      addCriterion("ONDOCD <>", value, "ondocd");
      return (Criteria) this;
    }

    public Criteria andOndocdGreaterThan(Short value) {
      addCriterion("ONDOCD >", value, "ondocd");
      return (Criteria) this;
    }

    public Criteria andOndocdGreaterThanOrEqualTo(Short value) {
      addCriterion("ONDOCD >=", value, "ondocd");
      return (Criteria) this;
    }

    public Criteria andOndocdLessThan(Short value) {
      addCriterion("ONDOCD <", value, "ondocd");
      return (Criteria) this;
    }

    public Criteria andOndocdLessThanOrEqualTo(Short value) {
      addCriterion("ONDOCD <=", value, "ondocd");
      return (Criteria) this;
    }

    public Criteria andOndocdIn(List<Short> values) {
      addCriterion("ONDOCD in", values, "ondocd");
      return (Criteria) this;
    }

    public Criteria andOndocdNotIn(List<Short> values) {
      addCriterion("ONDOCD not in", values, "ondocd");
      return (Criteria) this;
    }

    public Criteria andOndocdBetween(Short value1, Short value2) {
      addCriterion("ONDOCD between", value1, value2, "ondocd");
      return (Criteria) this;
    }

    public Criteria andOndocdNotBetween(Short value1, Short value2) {
      addCriterion("ONDOCD not between", value1, value2, "ondocd");
      return (Criteria) this;
    }

    public Criteria andBaikaIsNull() {
      addCriterion("BAIKA is null");
      return (Criteria) this;
    }

    public Criteria andBaikaIsNotNull() {
      addCriterion("BAIKA is not null");
      return (Criteria) this;
    }

    public Criteria andBaikaEqualTo(Integer value) {
      addCriterion("BAIKA =", value, "baika");
      return (Criteria) this;
    }

    public Criteria andBaikaNotEqualTo(Integer value) {
      addCriterion("BAIKA <>", value, "baika");
      return (Criteria) this;
    }

    public Criteria andBaikaGreaterThan(Integer value) {
      addCriterion("BAIKA >", value, "baika");
      return (Criteria) this;
    }

    public Criteria andBaikaGreaterThanOrEqualTo(Integer value) {
      addCriterion("BAIKA >=", value, "baika");
      return (Criteria) this;
    }

    public Criteria andBaikaLessThan(Integer value) {
      addCriterion("BAIKA <", value, "baika");
      return (Criteria) this;
    }

    public Criteria andBaikaLessThanOrEqualTo(Integer value) {
      addCriterion("BAIKA <=", value, "baika");
      return (Criteria) this;
    }

    public Criteria andBaikaIn(List<Integer> values) {
      addCriterion("BAIKA in", values, "baika");
      return (Criteria) this;
    }

    public Criteria andBaikaNotIn(List<Integer> values) {
      addCriterion("BAIKA not in", values, "baika");
      return (Criteria) this;
    }

    public Criteria andBaikaBetween(Integer value1, Integer value2) {
      addCriterion("BAIKA between", value1, value2, "baika");
      return (Criteria) this;
    }

    public Criteria andBaikaNotBetween(Integer value1, Integer value2) {
      addCriterion("BAIKA not between", value1, value2, "baika");
      return (Criteria) this;
    }

    public Criteria andOrosikaIsNull() {
      addCriterion("OROSIKA is null");
      return (Criteria) this;
    }

    public Criteria andOrosikaIsNotNull() {
      addCriterion("OROSIKA is not null");
      return (Criteria) this;
    }

    public Criteria andOrosikaEqualTo(BigDecimal value) {
      addCriterion("OROSIKA =", value, "orosika");
      return (Criteria) this;
    }

    public Criteria andOrosikaNotEqualTo(BigDecimal value) {
      addCriterion("OROSIKA <>", value, "orosika");
      return (Criteria) this;
    }

    public Criteria andOrosikaGreaterThan(BigDecimal value) {
      addCriterion("OROSIKA >", value, "orosika");
      return (Criteria) this;
    }

    public Criteria andOrosikaGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("OROSIKA >=", value, "orosika");
      return (Criteria) this;
    }

    public Criteria andOrosikaLessThan(BigDecimal value) {
      addCriterion("OROSIKA <", value, "orosika");
      return (Criteria) this;
    }

    public Criteria andOrosikaLessThanOrEqualTo(BigDecimal value) {
      addCriterion("OROSIKA <=", value, "orosika");
      return (Criteria) this;
    }

    public Criteria andOrosikaIn(List<BigDecimal> values) {
      addCriterion("OROSIKA in", values, "orosika");
      return (Criteria) this;
    }

    public Criteria andOrosikaNotIn(List<BigDecimal> values) {
      addCriterion("OROSIKA not in", values, "orosika");
      return (Criteria) this;
    }

    public Criteria andOrosikaBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("OROSIKA between", value1, value2, "orosika");
      return (Criteria) this;
    }

    public Criteria andOrosikaNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("OROSIKA not between", value1, value2, "orosika");
      return (Criteria) this;
    }

    public Criteria andSikirikaIsNull() {
      addCriterion("SIKIRIKA is null");
      return (Criteria) this;
    }

    public Criteria andSikirikaIsNotNull() {
      addCriterion("SIKIRIKA is not null");
      return (Criteria) this;
    }

    public Criteria andSikirikaEqualTo(BigDecimal value) {
      addCriterion("SIKIRIKA =", value, "sikirika");
      return (Criteria) this;
    }

    public Criteria andSikirikaNotEqualTo(BigDecimal value) {
      addCriterion("SIKIRIKA <>", value, "sikirika");
      return (Criteria) this;
    }

    public Criteria andSikirikaGreaterThan(BigDecimal value) {
      addCriterion("SIKIRIKA >", value, "sikirika");
      return (Criteria) this;
    }

    public Criteria andSikirikaGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("SIKIRIKA >=", value, "sikirika");
      return (Criteria) this;
    }

    public Criteria andSikirikaLessThan(BigDecimal value) {
      addCriterion("SIKIRIKA <", value, "sikirika");
      return (Criteria) this;
    }

    public Criteria andSikirikaLessThanOrEqualTo(BigDecimal value) {
      addCriterion("SIKIRIKA <=", value, "sikirika");
      return (Criteria) this;
    }

    public Criteria andSikirikaIn(List<BigDecimal> values) {
      addCriterion("SIKIRIKA in", values, "sikirika");
      return (Criteria) this;
    }

    public Criteria andSikirikaNotIn(List<BigDecimal> values) {
      addCriterion("SIKIRIKA not in", values, "sikirika");
      return (Criteria) this;
    }

    public Criteria andSikirikaBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("SIKIRIKA between", value1, value2, "sikirika");
      return (Criteria) this;
    }

    public Criteria andSikirikaNotBetween(BigDecimal value1,
        BigDecimal value2) {
      addCriterion("SIKIRIKA not between", value1, value2, "sikirika");
      return (Criteria) this;
    }

    public Criteria andSikiritokkaIsNull() {
      addCriterion("SIKIRITOKKA is null");
      return (Criteria) this;
    }

    public Criteria andSikiritokkaIsNotNull() {
      addCriterion("SIKIRITOKKA is not null");
      return (Criteria) this;
    }

    public Criteria andSikiritokkaEqualTo(BigDecimal value) {
      addCriterion("SIKIRITOKKA =", value, "sikiritokka");
      return (Criteria) this;
    }

    public Criteria andSikiritokkaNotEqualTo(BigDecimal value) {
      addCriterion("SIKIRITOKKA <>", value, "sikiritokka");
      return (Criteria) this;
    }

    public Criteria andSikiritokkaGreaterThan(BigDecimal value) {
      addCriterion("SIKIRITOKKA >", value, "sikiritokka");
      return (Criteria) this;
    }

    public Criteria andSikiritokkaGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("SIKIRITOKKA >=", value, "sikiritokka");
      return (Criteria) this;
    }

    public Criteria andSikiritokkaLessThan(BigDecimal value) {
      addCriterion("SIKIRITOKKA <", value, "sikiritokka");
      return (Criteria) this;
    }

    public Criteria andSikiritokkaLessThanOrEqualTo(BigDecimal value) {
      addCriterion("SIKIRITOKKA <=", value, "sikiritokka");
      return (Criteria) this;
    }

    public Criteria andSikiritokkaIn(List<BigDecimal> values) {
      addCriterion("SIKIRITOKKA in", values, "sikiritokka");
      return (Criteria) this;
    }

    public Criteria andSikiritokkaNotIn(List<BigDecimal> values) {
      addCriterion("SIKIRITOKKA not in", values, "sikiritokka");
      return (Criteria) this;
    }

    public Criteria andSikiritokkaBetween(BigDecimal value1,
        BigDecimal value2) {
      addCriterion("SIKIRITOKKA between", value1, value2, "sikiritokka");
      return (Criteria) this;
    }

    public Criteria andSikiritokkaNotBetween(BigDecimal value1,
        BigDecimal value2) {
      addCriterion("SIKIRITOKKA not between", value1, value2, "sikiritokka");
      return (Criteria) this;
    }

    public Criteria andHasispnkbnIsNull() {
      addCriterion("HASISPNKBN is null");
      return (Criteria) this;
    }

    public Criteria andHasispnkbnIsNotNull() {
      addCriterion("HASISPNKBN is not null");
      return (Criteria) this;
    }

    public Criteria andHasispnkbnEqualTo(Short value) {
      addCriterion("HASISPNKBN =", value, "hasispnkbn");
      return (Criteria) this;
    }

    public Criteria andHasispnkbnNotEqualTo(Short value) {
      addCriterion("HASISPNKBN <>", value, "hasispnkbn");
      return (Criteria) this;
    }

    public Criteria andHasispnkbnGreaterThan(Short value) {
      addCriterion("HASISPNKBN >", value, "hasispnkbn");
      return (Criteria) this;
    }

    public Criteria andHasispnkbnGreaterThanOrEqualTo(Short value) {
      addCriterion("HASISPNKBN >=", value, "hasispnkbn");
      return (Criteria) this;
    }

    public Criteria andHasispnkbnLessThan(Short value) {
      addCriterion("HASISPNKBN <", value, "hasispnkbn");
      return (Criteria) this;
    }

    public Criteria andHasispnkbnLessThanOrEqualTo(Short value) {
      addCriterion("HASISPNKBN <=", value, "hasispnkbn");
      return (Criteria) this;
    }

    public Criteria andHasispnkbnIn(List<Short> values) {
      addCriterion("HASISPNKBN in", values, "hasispnkbn");
      return (Criteria) this;
    }

    public Criteria andHasispnkbnNotIn(List<Short> values) {
      addCriterion("HASISPNKBN not in", values, "hasispnkbn");
      return (Criteria) this;
    }

    public Criteria andHasispnkbnBetween(Short value1, Short value2) {
      addCriterion("HASISPNKBN between", value1, value2, "hasispnkbn");
      return (Criteria) this;
    }

    public Criteria andHasispnkbnNotBetween(Short value1, Short value2) {
      addCriterion("HASISPNKBN not between", value1, value2, "hasispnkbn");
      return (Criteria) this;
    }

    public Criteria andWeekflgIsNull() {
      addCriterion("WEEKFLG is null");
      return (Criteria) this;
    }

    public Criteria andWeekflgIsNotNull() {
      addCriterion("WEEKFLG is not null");
      return (Criteria) this;
    }

    public Criteria andWeekflgEqualTo(Short value) {
      addCriterion("WEEKFLG =", value, "weekflg");
      return (Criteria) this;
    }

    public Criteria andWeekflgNotEqualTo(Short value) {
      addCriterion("WEEKFLG <>", value, "weekflg");
      return (Criteria) this;
    }

    public Criteria andWeekflgGreaterThan(Short value) {
      addCriterion("WEEKFLG >", value, "weekflg");
      return (Criteria) this;
    }

    public Criteria andWeekflgGreaterThanOrEqualTo(Short value) {
      addCriterion("WEEKFLG >=", value, "weekflg");
      return (Criteria) this;
    }

    public Criteria andWeekflgLessThan(Short value) {
      addCriterion("WEEKFLG <", value, "weekflg");
      return (Criteria) this;
    }

    public Criteria andWeekflgLessThanOrEqualTo(Short value) {
      addCriterion("WEEKFLG <=", value, "weekflg");
      return (Criteria) this;
    }

    public Criteria andWeekflgIn(List<Short> values) {
      addCriterion("WEEKFLG in", values, "weekflg");
      return (Criteria) this;
    }

    public Criteria andWeekflgNotIn(List<Short> values) {
      addCriterion("WEEKFLG not in", values, "weekflg");
      return (Criteria) this;
    }

    public Criteria andWeekflgBetween(Short value1, Short value2) {
      addCriterion("WEEKFLG between", value1, value2, "weekflg");
      return (Criteria) this;
    }

    public Criteria andWeekflgNotBetween(Short value1, Short value2) {
      addCriterion("WEEKFLG not between", value1, value2, "weekflg");
      return (Criteria) this;
    }

    public Criteria andBarcd1IsNull() {
      addCriterion("BARCD1 is null");
      return (Criteria) this;
    }

    public Criteria andBarcd1IsNotNull() {
      addCriterion("BARCD1 is not null");
      return (Criteria) this;
    }

    public Criteria andBarcd1EqualTo(Long value) {
      addCriterion("BARCD1 =", value, "barcd1");
      return (Criteria) this;
    }

    public Criteria andBarcd1NotEqualTo(Long value) {
      addCriterion("BARCD1 <>", value, "barcd1");
      return (Criteria) this;
    }

    public Criteria andBarcd1GreaterThan(Long value) {
      addCriterion("BARCD1 >", value, "barcd1");
      return (Criteria) this;
    }

    public Criteria andBarcd1GreaterThanOrEqualTo(Long value) {
      addCriterion("BARCD1 >=", value, "barcd1");
      return (Criteria) this;
    }

    public Criteria andBarcd1LessThan(Long value) {
      addCriterion("BARCD1 <", value, "barcd1");
      return (Criteria) this;
    }

    public Criteria andBarcd1LessThanOrEqualTo(Long value) {
      addCriterion("BARCD1 <=", value, "barcd1");
      return (Criteria) this;
    }

    public Criteria andBarcd1In(List<Long> values) {
      addCriterion("BARCD1 in", values, "barcd1");
      return (Criteria) this;
    }

    public Criteria andBarcd1NotIn(List<Long> values) {
      addCriterion("BARCD1 not in", values, "barcd1");
      return (Criteria) this;
    }

    public Criteria andBarcd1Between(Long value1, Long value2) {
      addCriterion("BARCD1 between", value1, value2, "barcd1");
      return (Criteria) this;
    }

    public Criteria andBarcd1NotBetween(Long value1, Long value2) {
      addCriterion("BARCD1 not between", value1, value2, "barcd1");
      return (Criteria) this;
    }

    public Criteria andBarcd2IsNull() {
      addCriterion("BARCD2 is null");
      return (Criteria) this;
    }

    public Criteria andBarcd2IsNotNull() {
      addCriterion("BARCD2 is not null");
      return (Criteria) this;
    }

    public Criteria andBarcd2EqualTo(Long value) {
      addCriterion("BARCD2 =", value, "barcd2");
      return (Criteria) this;
    }

    public Criteria andBarcd2NotEqualTo(Long value) {
      addCriterion("BARCD2 <>", value, "barcd2");
      return (Criteria) this;
    }

    public Criteria andBarcd2GreaterThan(Long value) {
      addCriterion("BARCD2 >", value, "barcd2");
      return (Criteria) this;
    }

    public Criteria andBarcd2GreaterThanOrEqualTo(Long value) {
      addCriterion("BARCD2 >=", value, "barcd2");
      return (Criteria) this;
    }

    public Criteria andBarcd2LessThan(Long value) {
      addCriterion("BARCD2 <", value, "barcd2");
      return (Criteria) this;
    }

    public Criteria andBarcd2LessThanOrEqualTo(Long value) {
      addCriterion("BARCD2 <=", value, "barcd2");
      return (Criteria) this;
    }

    public Criteria andBarcd2In(List<Long> values) {
      addCriterion("BARCD2 in", values, "barcd2");
      return (Criteria) this;
    }

    public Criteria andBarcd2NotIn(List<Long> values) {
      addCriterion("BARCD2 not in", values, "barcd2");
      return (Criteria) this;
    }

    public Criteria andBarcd2Between(Long value1, Long value2) {
      addCriterion("BARCD2 between", value1, value2, "barcd2");
      return (Criteria) this;
    }

    public Criteria andBarcd2NotBetween(Long value1, Long value2) {
      addCriterion("BARCD2 not between", value1, value2, "barcd2");
      return (Criteria) this;
    }

    public Criteria andBarcd3IsNull() {
      addCriterion("BARCD3 is null");
      return (Criteria) this;
    }

    public Criteria andBarcd3IsNotNull() {
      addCriterion("BARCD3 is not null");
      return (Criteria) this;
    }

    public Criteria andBarcd3EqualTo(Long value) {
      addCriterion("BARCD3 =", value, "barcd3");
      return (Criteria) this;
    }

    public Criteria andBarcd3NotEqualTo(Long value) {
      addCriterion("BARCD3 <>", value, "barcd3");
      return (Criteria) this;
    }

    public Criteria andBarcd3GreaterThan(Long value) {
      addCriterion("BARCD3 >", value, "barcd3");
      return (Criteria) this;
    }

    public Criteria andBarcd3GreaterThanOrEqualTo(Long value) {
      addCriterion("BARCD3 >=", value, "barcd3");
      return (Criteria) this;
    }

    public Criteria andBarcd3LessThan(Long value) {
      addCriterion("BARCD3 <", value, "barcd3");
      return (Criteria) this;
    }

    public Criteria andBarcd3LessThanOrEqualTo(Long value) {
      addCriterion("BARCD3 <=", value, "barcd3");
      return (Criteria) this;
    }

    public Criteria andBarcd3In(List<Long> values) {
      addCriterion("BARCD3 in", values, "barcd3");
      return (Criteria) this;
    }

    public Criteria andBarcd3NotIn(List<Long> values) {
      addCriterion("BARCD3 not in", values, "barcd3");
      return (Criteria) this;
    }

    public Criteria andBarcd3Between(Long value1, Long value2) {
      addCriterion("BARCD3 between", value1, value2, "barcd3");
      return (Criteria) this;
    }

    public Criteria andBarcd3NotBetween(Long value1, Long value2) {
      addCriterion("BARCD3 not between", value1, value2, "barcd3");
      return (Criteria) this;
    }

    public Criteria andSaleymdIsNull() {
      addCriterion("SALEYMD is null");
      return (Criteria) this;
    }

    public Criteria andSaleymdIsNotNull() {
      addCriterion("SALEYMD is not null");
      return (Criteria) this;
    }

    public Criteria andSaleymdEqualTo(Integer value) {
      addCriterion("SALEYMD =", value, "saleymd");
      return (Criteria) this;
    }

    public Criteria andSaleymdNotEqualTo(Integer value) {
      addCriterion("SALEYMD <>", value, "saleymd");
      return (Criteria) this;
    }

    public Criteria andSaleymdGreaterThan(Integer value) {
      addCriterion("SALEYMD >", value, "saleymd");
      return (Criteria) this;
    }

    public Criteria andSaleymdGreaterThanOrEqualTo(Integer value) {
      addCriterion("SALEYMD >=", value, "saleymd");
      return (Criteria) this;
    }

    public Criteria andSaleymdLessThan(Integer value) {
      addCriterion("SALEYMD <", value, "saleymd");
      return (Criteria) this;
    }

    public Criteria andSaleymdLessThanOrEqualTo(Integer value) {
      addCriterion("SALEYMD <=", value, "saleymd");
      return (Criteria) this;
    }

    public Criteria andSaleymdIn(List<Integer> values) {
      addCriterion("SALEYMD in", values, "saleymd");
      return (Criteria) this;
    }

    public Criteria andSaleymdNotIn(List<Integer> values) {
      addCriterion("SALEYMD not in", values, "saleymd");
      return (Criteria) this;
    }

    public Criteria andSaleymdBetween(Integer value1, Integer value2) {
      addCriterion("SALEYMD between", value1, value2, "saleymd");
      return (Criteria) this;
    }

    public Criteria andSaleymdNotBetween(Integer value1, Integer value2) {
      addCriterion("SALEYMD not between", value1, value2, "saleymd");
      return (Criteria) this;
    }

    public Criteria andSunpouIsNull() {
      addCriterion("SUNPOU is null");
      return (Criteria) this;
    }

    public Criteria andSunpouIsNotNull() {
      addCriterion("SUNPOU is not null");
      return (Criteria) this;
    }

    public Criteria andSunpouEqualTo(Short value) {
      addCriterion("SUNPOU =", value, "sunpou");
      return (Criteria) this;
    }

    public Criteria andSunpouNotEqualTo(Short value) {
      addCriterion("SUNPOU <>", value, "sunpou");
      return (Criteria) this;
    }

    public Criteria andSunpouGreaterThan(Short value) {
      addCriterion("SUNPOU >", value, "sunpou");
      return (Criteria) this;
    }

    public Criteria andSunpouGreaterThanOrEqualTo(Short value) {
      addCriterion("SUNPOU >=", value, "sunpou");
      return (Criteria) this;
    }

    public Criteria andSunpouLessThan(Short value) {
      addCriterion("SUNPOU <", value, "sunpou");
      return (Criteria) this;
    }

    public Criteria andSunpouLessThanOrEqualTo(Short value) {
      addCriterion("SUNPOU <=", value, "sunpou");
      return (Criteria) this;
    }

    public Criteria andSunpouIn(List<Short> values) {
      addCriterion("SUNPOU in", values, "sunpou");
      return (Criteria) this;
    }

    public Criteria andSunpouNotIn(List<Short> values) {
      addCriterion("SUNPOU not in", values, "sunpou");
      return (Criteria) this;
    }

    public Criteria andSunpouBetween(Short value1, Short value2) {
      addCriterion("SUNPOU between", value1, value2, "sunpou");
      return (Criteria) this;
    }

    public Criteria andSunpouNotBetween(Short value1, Short value2) {
      addCriterion("SUNPOU not between", value1, value2, "sunpou");
      return (Criteria) this;
    }

    public Criteria andTatesuIsNull() {
      addCriterion("TATESU is null");
      return (Criteria) this;
    }

    public Criteria andTatesuIsNotNull() {
      addCriterion("TATESU is not null");
      return (Criteria) this;
    }

    public Criteria andTatesuEqualTo(Short value) {
      addCriterion("TATESU =", value, "tatesu");
      return (Criteria) this;
    }

    public Criteria andTatesuNotEqualTo(Short value) {
      addCriterion("TATESU <>", value, "tatesu");
      return (Criteria) this;
    }

    public Criteria andTatesuGreaterThan(Short value) {
      addCriterion("TATESU >", value, "tatesu");
      return (Criteria) this;
    }

    public Criteria andTatesuGreaterThanOrEqualTo(Short value) {
      addCriterion("TATESU >=", value, "tatesu");
      return (Criteria) this;
    }

    public Criteria andTatesuLessThan(Short value) {
      addCriterion("TATESU <", value, "tatesu");
      return (Criteria) this;
    }

    public Criteria andTatesuLessThanOrEqualTo(Short value) {
      addCriterion("TATESU <=", value, "tatesu");
      return (Criteria) this;
    }

    public Criteria andTatesuIn(List<Short> values) {
      addCriterion("TATESU in", values, "tatesu");
      return (Criteria) this;
    }

    public Criteria andTatesuNotIn(List<Short> values) {
      addCriterion("TATESU not in", values, "tatesu");
      return (Criteria) this;
    }

    public Criteria andTatesuBetween(Short value1, Short value2) {
      addCriterion("TATESU between", value1, value2, "tatesu");
      return (Criteria) this;
    }

    public Criteria andTatesuNotBetween(Short value1, Short value2) {
      addCriterion("TATESU not between", value1, value2, "tatesu");
      return (Criteria) this;
    }

    public Criteria andIremeIsNull() {
      addCriterion("IREME is null");
      return (Criteria) this;
    }

    public Criteria andIremeIsNotNull() {
      addCriterion("IREME is not null");
      return (Criteria) this;
    }

    public Criteria andIremeEqualTo(Short value) {
      addCriterion("IREME =", value, "ireme");
      return (Criteria) this;
    }

    public Criteria andIremeNotEqualTo(Short value) {
      addCriterion("IREME <>", value, "ireme");
      return (Criteria) this;
    }

    public Criteria andIremeGreaterThan(Short value) {
      addCriterion("IREME >", value, "ireme");
      return (Criteria) this;
    }

    public Criteria andIremeGreaterThanOrEqualTo(Short value) {
      addCriterion("IREME >=", value, "ireme");
      return (Criteria) this;
    }

    public Criteria andIremeLessThan(Short value) {
      addCriterion("IREME <", value, "ireme");
      return (Criteria) this;
    }

    public Criteria andIremeLessThanOrEqualTo(Short value) {
      addCriterion("IREME <=", value, "ireme");
      return (Criteria) this;
    }

    public Criteria andIremeIn(List<Short> values) {
      addCriterion("IREME in", values, "ireme");
      return (Criteria) this;
    }

    public Criteria andIremeNotIn(List<Short> values) {
      addCriterion("IREME not in", values, "ireme");
      return (Criteria) this;
    }

    public Criteria andIremeBetween(Short value1, Short value2) {
      addCriterion("IREME between", value1, value2, "ireme");
      return (Criteria) this;
    }

    public Criteria andIremeNotBetween(Short value1, Short value2) {
      addCriterion("IREME not between", value1, value2, "ireme");
      return (Criteria) this;
    }

    public Criteria andSzokeicdIsNull() {
      addCriterion("SZOKEICD is null");
      return (Criteria) this;
    }

    public Criteria andSzokeicdIsNotNull() {
      addCriterion("SZOKEICD is not null");
      return (Criteria) this;
    }

    public Criteria andSzokeicdEqualTo(Short value) {
      addCriterion("SZOKEICD =", value, "szokeicd");
      return (Criteria) this;
    }

    public Criteria andSzokeicdNotEqualTo(Short value) {
      addCriterion("SZOKEICD <>", value, "szokeicd");
      return (Criteria) this;
    }

    public Criteria andSzokeicdGreaterThan(Short value) {
      addCriterion("SZOKEICD >", value, "szokeicd");
      return (Criteria) this;
    }

    public Criteria andSzokeicdGreaterThanOrEqualTo(Short value) {
      addCriterion("SZOKEICD >=", value, "szokeicd");
      return (Criteria) this;
    }

    public Criteria andSzokeicdLessThan(Short value) {
      addCriterion("SZOKEICD <", value, "szokeicd");
      return (Criteria) this;
    }

    public Criteria andSzokeicdLessThanOrEqualTo(Short value) {
      addCriterion("SZOKEICD <=", value, "szokeicd");
      return (Criteria) this;
    }

    public Criteria andSzokeicdIn(List<Short> values) {
      addCriterion("SZOKEICD in", values, "szokeicd");
      return (Criteria) this;
    }

    public Criteria andSzokeicdNotIn(List<Short> values) {
      addCriterion("SZOKEICD not in", values, "szokeicd");
      return (Criteria) this;
    }

    public Criteria andSzokeicdBetween(Short value1, Short value2) {
      addCriterion("SZOKEICD between", value1, value2, "szokeicd");
      return (Criteria) this;
    }

    public Criteria andSzokeicdNotBetween(Short value1, Short value2) {
      addCriterion("SZOKEICD not between", value1, value2, "szokeicd");
      return (Criteria) this;
    }

    public Criteria andDchncdIsNull() {
      addCriterion("DCHNCD is null");
      return (Criteria) this;
    }

    public Criteria andDchncdIsNotNull() {
      addCriterion("DCHNCD is not null");
      return (Criteria) this;
    }

    public Criteria andDchncdEqualTo(Short value) {
      addCriterion("DCHNCD =", value, "dchncd");
      return (Criteria) this;
    }

    public Criteria andDchncdNotEqualTo(Short value) {
      addCriterion("DCHNCD <>", value, "dchncd");
      return (Criteria) this;
    }

    public Criteria andDchncdGreaterThan(Short value) {
      addCriterion("DCHNCD >", value, "dchncd");
      return (Criteria) this;
    }

    public Criteria andDchncdGreaterThanOrEqualTo(Short value) {
      addCriterion("DCHNCD >=", value, "dchncd");
      return (Criteria) this;
    }

    public Criteria andDchncdLessThan(Short value) {
      addCriterion("DCHNCD <", value, "dchncd");
      return (Criteria) this;
    }

    public Criteria andDchncdLessThanOrEqualTo(Short value) {
      addCriterion("DCHNCD <=", value, "dchncd");
      return (Criteria) this;
    }

    public Criteria andDchncdIn(List<Short> values) {
      addCriterion("DCHNCD in", values, "dchncd");
      return (Criteria) this;
    }

    public Criteria andDchncdNotIn(List<Short> values) {
      addCriterion("DCHNCD not in", values, "dchncd");
      return (Criteria) this;
    }

    public Criteria andDchncdBetween(Short value1, Short value2) {
      addCriterion("DCHNCD between", value1, value2, "dchncd");
      return (Criteria) this;
    }

    public Criteria andDchncdNotBetween(Short value1, Short value2) {
      addCriterion("DCHNCD not between", value1, value2, "dchncd");
      return (Criteria) this;
    }

    public Criteria andDchnedaIsNull() {
      addCriterion("DCHNEDA is null");
      return (Criteria) this;
    }

    public Criteria andDchnedaIsNotNull() {
      addCriterion("DCHNEDA is not null");
      return (Criteria) this;
    }

    public Criteria andDchnedaEqualTo(Short value) {
      addCriterion("DCHNEDA =", value, "dchneda");
      return (Criteria) this;
    }

    public Criteria andDchnedaNotEqualTo(Short value) {
      addCriterion("DCHNEDA <>", value, "dchneda");
      return (Criteria) this;
    }

    public Criteria andDchnedaGreaterThan(Short value) {
      addCriterion("DCHNEDA >", value, "dchneda");
      return (Criteria) this;
    }

    public Criteria andDchnedaGreaterThanOrEqualTo(Short value) {
      addCriterion("DCHNEDA >=", value, "dchneda");
      return (Criteria) this;
    }

    public Criteria andDchnedaLessThan(Short value) {
      addCriterion("DCHNEDA <", value, "dchneda");
      return (Criteria) this;
    }

    public Criteria andDchnedaLessThanOrEqualTo(Short value) {
      addCriterion("DCHNEDA <=", value, "dchneda");
      return (Criteria) this;
    }

    public Criteria andDchnedaIn(List<Short> values) {
      addCriterion("DCHNEDA in", values, "dchneda");
      return (Criteria) this;
    }

    public Criteria andDchnedaNotIn(List<Short> values) {
      addCriterion("DCHNEDA not in", values, "dchneda");
      return (Criteria) this;
    }

    public Criteria andDchnedaBetween(Short value1, Short value2) {
      addCriterion("DCHNEDA between", value1, value2, "dchneda");
      return (Criteria) this;
    }

    public Criteria andDchnedaNotBetween(Short value1, Short value2) {
      addCriterion("DCHNEDA not between", value1, value2, "dchneda");
      return (Criteria) this;
    }

    public Criteria andDhincdIsNull() {
      addCriterion("DHINCD is null");
      return (Criteria) this;
    }

    public Criteria andDhincdIsNotNull() {
      addCriterion("DHINCD is not null");
      return (Criteria) this;
    }

    public Criteria andDhincdEqualTo(String value) {
      addCriterion("DHINCD =", value, "dhincd");
      return (Criteria) this;
    }

    public Criteria andDhincdNotEqualTo(String value) {
      addCriterion("DHINCD <>", value, "dhincd");
      return (Criteria) this;
    }

    public Criteria andDhincdGreaterThan(String value) {
      addCriterion("DHINCD >", value, "dhincd");
      return (Criteria) this;
    }

    public Criteria andDhincdGreaterThanOrEqualTo(String value) {
      addCriterion("DHINCD >=", value, "dhincd");
      return (Criteria) this;
    }

    public Criteria andDhincdLessThan(String value) {
      addCriterion("DHINCD <", value, "dhincd");
      return (Criteria) this;
    }

    public Criteria andDhincdLessThanOrEqualTo(String value) {
      addCriterion("DHINCD <=", value, "dhincd");
      return (Criteria) this;
    }

    public Criteria andDhincdLike(String value) {
      addCriterion("DHINCD like", value, "dhincd");
      return (Criteria) this;
    }

    public Criteria andDhincdNotLike(String value) {
      addCriterion("DHINCD not like", value, "dhincd");
      return (Criteria) this;
    }

    public Criteria andDhincdIn(List<String> values) {
      addCriterion("DHINCD in", values, "dhincd");
      return (Criteria) this;
    }

    public Criteria andDhincdNotIn(List<String> values) {
      addCriterion("DHINCD not in", values, "dhincd");
      return (Criteria) this;
    }

    public Criteria andDhincdBetween(String value1, String value2) {
      addCriterion("DHINCD between", value1, value2, "dhincd");
      return (Criteria) this;
    }

    public Criteria andDhincdNotBetween(String value1, String value2) {
      addCriterion("DHINCD not between", value1, value2, "dhincd");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table MST_S_SEIHN
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public static class Criterion {

    private String condition;
    private Object value;
    private Object secondValue;
    private boolean noValue;
    private boolean singleValue;
    private boolean betweenValue;
    private boolean listValue;
    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue,
        String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MST_S_SEIHN
     *
     * @mbggenerated do_not_delete_during_merge Thu Sep 17 21:03:29 JST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}