package jp.co.daitoku_sh.dfcm.common.db.model;

public class MstSShocv extends MstSShocvKey {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_S_SHOCV.INPYMD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private Integer inpymd;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_S_SHOCV.INPTIM
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private Integer inptim;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_S_SHOCV.INPUSR
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String inpusr;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_S_SHOCV.UPDYMD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private Integer updymd;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_S_SHOCV.UPDTIM
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private Integer updtim;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_S_SHOCV.TKSCD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String tkscd;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_S_SHOCV.YOBI
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String yobi;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_S_SHOCV.DELFLG
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private Short delflg;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_S_SHOCV.STRYMD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private Integer strymd;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_S_SHOCV.STRBIN
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private Short strbin;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_S_SHOCV.HINCD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String hincd;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_S_SHOCV.BIN
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String bin;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column MST_S_SHOCV.AITEBUNRUI
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String aitebunrui;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_S_SHOCV.INPYMD
   * @return  the value of MST_S_SHOCV.INPYMD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public Integer getInpymd() {
    return inpymd;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_S_SHOCV.INPYMD
   * @param inpymd  the value for MST_S_SHOCV.INPYMD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setInpymd(Integer inpymd) {
    this.inpymd = inpymd;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_S_SHOCV.INPTIM
   * @return  the value of MST_S_SHOCV.INPTIM
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public Integer getInptim() {
    return inptim;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_S_SHOCV.INPTIM
   * @param inptim  the value for MST_S_SHOCV.INPTIM
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setInptim(Integer inptim) {
    this.inptim = inptim;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_S_SHOCV.INPUSR
   * @return  the value of MST_S_SHOCV.INPUSR
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getInpusr() {
    return inpusr;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_S_SHOCV.INPUSR
   * @param inpusr  the value for MST_S_SHOCV.INPUSR
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setInpusr(String inpusr) {
    this.inpusr = inpusr;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_S_SHOCV.UPDYMD
   * @return  the value of MST_S_SHOCV.UPDYMD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public Integer getUpdymd() {
    return updymd;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_S_SHOCV.UPDYMD
   * @param updymd  the value for MST_S_SHOCV.UPDYMD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setUpdymd(Integer updymd) {
    this.updymd = updymd;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_S_SHOCV.UPDTIM
   * @return  the value of MST_S_SHOCV.UPDTIM
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public Integer getUpdtim() {
    return updtim;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_S_SHOCV.UPDTIM
   * @param updtim  the value for MST_S_SHOCV.UPDTIM
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setUpdtim(Integer updtim) {
    this.updtim = updtim;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_S_SHOCV.TKSCD
   * @return  the value of MST_S_SHOCV.TKSCD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getTkscd() {
    return tkscd;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_S_SHOCV.TKSCD
   * @param tkscd  the value for MST_S_SHOCV.TKSCD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTkscd(String tkscd) {
    this.tkscd = tkscd;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_S_SHOCV.YOBI
   * @return  the value of MST_S_SHOCV.YOBI
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getYobi() {
    return yobi;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_S_SHOCV.YOBI
   * @param yobi  the value for MST_S_SHOCV.YOBI
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setYobi(String yobi) {
    this.yobi = yobi;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_S_SHOCV.DELFLG
   * @return  the value of MST_S_SHOCV.DELFLG
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public Short getDelflg() {
    return delflg;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_S_SHOCV.DELFLG
   * @param delflg  the value for MST_S_SHOCV.DELFLG
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setDelflg(Short delflg) {
    this.delflg = delflg;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_S_SHOCV.STRYMD
   * @return  the value of MST_S_SHOCV.STRYMD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public Integer getStrymd() {
    return strymd;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_S_SHOCV.STRYMD
   * @param strymd  the value for MST_S_SHOCV.STRYMD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setStrymd(Integer strymd) {
    this.strymd = strymd;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_S_SHOCV.STRBIN
   * @return  the value of MST_S_SHOCV.STRBIN
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public Short getStrbin() {
    return strbin;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_S_SHOCV.STRBIN
   * @param strbin  the value for MST_S_SHOCV.STRBIN
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setStrbin(Short strbin) {
    this.strbin = strbin;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_S_SHOCV.HINCD
   * @return  the value of MST_S_SHOCV.HINCD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getHincd() {
    return hincd;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_S_SHOCV.HINCD
   * @param hincd  the value for MST_S_SHOCV.HINCD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setHincd(String hincd) {
    this.hincd = hincd;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_S_SHOCV.BIN
   * @return  the value of MST_S_SHOCV.BIN
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getBin() {
    return bin;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_S_SHOCV.BIN
   * @param bin  the value for MST_S_SHOCV.BIN
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setBin(String bin) {
    this.bin = bin;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column MST_S_SHOCV.AITEBUNRUI
   * @return  the value of MST_S_SHOCV.AITEBUNRUI
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getAitebunrui() {
    return aitebunrui;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column MST_S_SHOCV.AITEBUNRUI
   * @param aitebunrui  the value for MST_S_SHOCV.AITEBUNRUI
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setAitebunrui(String aitebunrui) {
    this.aitebunrui = aitebunrui;
  }
}