package jp.co.daitoku_sh.dfcm.common.db.model;

public class TblNyu01ZdkReasonKey {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_NYU01_ZDK_REASON.Nyu_Den_No
   * @mbggenerated  Mon Nov 16 15:43:29 ICT 2015
   */
  private Long nyuDenNo;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_NYU01_ZDK_REASON.Zr_Code
   * @mbggenerated  Mon Nov 16 15:43:29 ICT 2015
   */
  private String zrCode;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_NYU01_ZDK_REASON.Nyu_Den_No
   * @return  the value of TBL_NYU01_ZDK_REASON.Nyu_Den_No
   * @mbggenerated  Mon Nov 16 15:43:29 ICT 2015
   */
  public Long getNyuDenNo() {
    return nyuDenNo;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_NYU01_ZDK_REASON.Nyu_Den_No
   * @param nyuDenNo  the value for TBL_NYU01_ZDK_REASON.Nyu_Den_No
   * @mbggenerated  Mon Nov 16 15:43:29 ICT 2015
   */
  public void setNyuDenNo(Long nyuDenNo) {
    this.nyuDenNo = nyuDenNo;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_NYU01_ZDK_REASON.Zr_Code
   * @return  the value of TBL_NYU01_ZDK_REASON.Zr_Code
   * @mbggenerated  Mon Nov 16 15:43:29 ICT 2015
   */
  public String getZrCode() {
    return zrCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_NYU01_ZDK_REASON.Zr_Code
   * @param zrCode  the value for TBL_NYU01_ZDK_REASON.Zr_Code
   * @mbggenerated  Mon Nov 16 15:43:29 ICT 2015
   */
  public void setZrCode(String zrCode) {
    this.zrCode = zrCode;
  }
}