package jp.co.daitoku_sh.dfcm.common.db.model;

public class TblSei01Head {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.Bild_Id
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private Long bildId;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.Chain_Code
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private Short chainCode;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.Chain_Idx
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private Short chainIdx;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.Cust_Code
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private String custCode;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.Jigyo_Code
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private String jigyoCode;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.Prev_Bild_Date
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private String prevBildDate;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.Bild_Date
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private String bildDate;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.Bild_sime_Kb
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private String bildSimeKb;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.Nyu_Flag
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private String nyuFlag;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.Nyu_Date
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private String nyuDate;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.Sime_DateTime
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private String simeDatetime;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.Prev_UAmt
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private Integer prevUamt;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.Prev_MAmt
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private Integer prevMamt;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.Cur_UNyu
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private Integer curUnyu;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.Cur_MNyu
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private Integer curMnyu;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.Cur_USou
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private Integer curUsou;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.Cur_MSou
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private Integer curMsou;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.Cur_UCho
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private Integer curUcho;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.Cur_MCho
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private Integer curMcho;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.Cur_UKur
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private Integer curUkur;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.Cur_MKur
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private Integer curMkur;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.Cur_UUri
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private Integer curUuri;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.Cur_Muri
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private Integer curMuri;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.Cur_Tax
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private Integer curTax;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.Cur_UTax
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private Integer curUtax;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.Cur_MTax
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private Integer curMtax;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.Cur_UAmt
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private Integer curUamt;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.Cur_MAmt
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private Integer curMamt;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.Uri_Zan
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private Integer uriZan;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.Mis_Zan
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private Integer misZan;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.Bild_Dat_Flg
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private String bildDatFlg;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.Prev_Bild_Id
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private Long prevBildId;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.Cust_Cls
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private String custCls;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.Bild_New_Flg
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private String bildNewFlg;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.Sts_Code
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private String stsCode;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.INS_USERID
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private String insUserid;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.INS_PGID
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private String insPgid;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.INS_YMD
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private String insYmd;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.INS_TIME
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private String insTime;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.UPD_USERID
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private String updUserid;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.UPD_PGID
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private String updPgid;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.UPD_YMD
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private String updYmd;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column TBL_SEI01_HEAD.UPD_TIME
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  private String updTime;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.Bild_Id
   * @return  the value of TBL_SEI01_HEAD.Bild_Id
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public Long getBildId() {
    return bildId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.Bild_Id
   * @param bildId  the value for TBL_SEI01_HEAD.Bild_Id
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setBildId(Long bildId) {
    this.bildId = bildId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.Chain_Code
   * @return  the value of TBL_SEI01_HEAD.Chain_Code
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public Short getChainCode() {
    return chainCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.Chain_Code
   * @param chainCode  the value for TBL_SEI01_HEAD.Chain_Code
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setChainCode(Short chainCode) {
    this.chainCode = chainCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.Chain_Idx
   * @return  the value of TBL_SEI01_HEAD.Chain_Idx
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public Short getChainIdx() {
    return chainIdx;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.Chain_Idx
   * @param chainIdx  the value for TBL_SEI01_HEAD.Chain_Idx
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setChainIdx(Short chainIdx) {
    this.chainIdx = chainIdx;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.Cust_Code
   * @return  the value of TBL_SEI01_HEAD.Cust_Code
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public String getCustCode() {
    return custCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.Cust_Code
   * @param custCode  the value for TBL_SEI01_HEAD.Cust_Code
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setCustCode(String custCode) {
    this.custCode = custCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.Jigyo_Code
   * @return  the value of TBL_SEI01_HEAD.Jigyo_Code
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public String getJigyoCode() {
    return jigyoCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.Jigyo_Code
   * @param jigyoCode  the value for TBL_SEI01_HEAD.Jigyo_Code
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setJigyoCode(String jigyoCode) {
    this.jigyoCode = jigyoCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.Prev_Bild_Date
   * @return  the value of TBL_SEI01_HEAD.Prev_Bild_Date
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public String getPrevBildDate() {
    return prevBildDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.Prev_Bild_Date
   * @param prevBildDate  the value for TBL_SEI01_HEAD.Prev_Bild_Date
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setPrevBildDate(String prevBildDate) {
    this.prevBildDate = prevBildDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.Bild_Date
   * @return  the value of TBL_SEI01_HEAD.Bild_Date
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public String getBildDate() {
    return bildDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.Bild_Date
   * @param bildDate  the value for TBL_SEI01_HEAD.Bild_Date
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setBildDate(String bildDate) {
    this.bildDate = bildDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.Bild_sime_Kb
   * @return  the value of TBL_SEI01_HEAD.Bild_sime_Kb
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public String getBildSimeKb() {
    return bildSimeKb;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.Bild_sime_Kb
   * @param bildSimeKb  the value for TBL_SEI01_HEAD.Bild_sime_Kb
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setBildSimeKb(String bildSimeKb) {
    this.bildSimeKb = bildSimeKb;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.Nyu_Flag
   * @return  the value of TBL_SEI01_HEAD.Nyu_Flag
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public String getNyuFlag() {
    return nyuFlag;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.Nyu_Flag
   * @param nyuFlag  the value for TBL_SEI01_HEAD.Nyu_Flag
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setNyuFlag(String nyuFlag) {
    this.nyuFlag = nyuFlag;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.Nyu_Date
   * @return  the value of TBL_SEI01_HEAD.Nyu_Date
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public String getNyuDate() {
    return nyuDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.Nyu_Date
   * @param nyuDate  the value for TBL_SEI01_HEAD.Nyu_Date
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setNyuDate(String nyuDate) {
    this.nyuDate = nyuDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.Sime_DateTime
   * @return  the value of TBL_SEI01_HEAD.Sime_DateTime
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public String getSimeDatetime() {
    return simeDatetime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.Sime_DateTime
   * @param simeDatetime  the value for TBL_SEI01_HEAD.Sime_DateTime
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setSimeDatetime(String simeDatetime) {
    this.simeDatetime = simeDatetime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.Prev_UAmt
   * @return  the value of TBL_SEI01_HEAD.Prev_UAmt
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public Integer getPrevUamt() {
    return prevUamt;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.Prev_UAmt
   * @param prevUamt  the value for TBL_SEI01_HEAD.Prev_UAmt
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setPrevUamt(Integer prevUamt) {
    this.prevUamt = prevUamt;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.Prev_MAmt
   * @return  the value of TBL_SEI01_HEAD.Prev_MAmt
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public Integer getPrevMamt() {
    return prevMamt;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.Prev_MAmt
   * @param prevMamt  the value for TBL_SEI01_HEAD.Prev_MAmt
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setPrevMamt(Integer prevMamt) {
    this.prevMamt = prevMamt;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.Cur_UNyu
   * @return  the value of TBL_SEI01_HEAD.Cur_UNyu
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public Integer getCurUnyu() {
    return curUnyu;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.Cur_UNyu
   * @param curUnyu  the value for TBL_SEI01_HEAD.Cur_UNyu
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setCurUnyu(Integer curUnyu) {
    this.curUnyu = curUnyu;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.Cur_MNyu
   * @return  the value of TBL_SEI01_HEAD.Cur_MNyu
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public Integer getCurMnyu() {
    return curMnyu;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.Cur_MNyu
   * @param curMnyu  the value for TBL_SEI01_HEAD.Cur_MNyu
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setCurMnyu(Integer curMnyu) {
    this.curMnyu = curMnyu;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.Cur_USou
   * @return  the value of TBL_SEI01_HEAD.Cur_USou
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public Integer getCurUsou() {
    return curUsou;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.Cur_USou
   * @param curUsou  the value for TBL_SEI01_HEAD.Cur_USou
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setCurUsou(Integer curUsou) {
    this.curUsou = curUsou;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.Cur_MSou
   * @return  the value of TBL_SEI01_HEAD.Cur_MSou
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public Integer getCurMsou() {
    return curMsou;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.Cur_MSou
   * @param curMsou  the value for TBL_SEI01_HEAD.Cur_MSou
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setCurMsou(Integer curMsou) {
    this.curMsou = curMsou;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.Cur_UCho
   * @return  the value of TBL_SEI01_HEAD.Cur_UCho
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public Integer getCurUcho() {
    return curUcho;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.Cur_UCho
   * @param curUcho  the value for TBL_SEI01_HEAD.Cur_UCho
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setCurUcho(Integer curUcho) {
    this.curUcho = curUcho;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.Cur_MCho
   * @return  the value of TBL_SEI01_HEAD.Cur_MCho
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public Integer getCurMcho() {
    return curMcho;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.Cur_MCho
   * @param curMcho  the value for TBL_SEI01_HEAD.Cur_MCho
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setCurMcho(Integer curMcho) {
    this.curMcho = curMcho;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.Cur_UKur
   * @return  the value of TBL_SEI01_HEAD.Cur_UKur
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public Integer getCurUkur() {
    return curUkur;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.Cur_UKur
   * @param curUkur  the value for TBL_SEI01_HEAD.Cur_UKur
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setCurUkur(Integer curUkur) {
    this.curUkur = curUkur;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.Cur_MKur
   * @return  the value of TBL_SEI01_HEAD.Cur_MKur
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public Integer getCurMkur() {
    return curMkur;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.Cur_MKur
   * @param curMkur  the value for TBL_SEI01_HEAD.Cur_MKur
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setCurMkur(Integer curMkur) {
    this.curMkur = curMkur;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.Cur_UUri
   * @return  the value of TBL_SEI01_HEAD.Cur_UUri
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public Integer getCurUuri() {
    return curUuri;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.Cur_UUri
   * @param curUuri  the value for TBL_SEI01_HEAD.Cur_UUri
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setCurUuri(Integer curUuri) {
    this.curUuri = curUuri;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.Cur_Muri
   * @return  the value of TBL_SEI01_HEAD.Cur_Muri
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public Integer getCurMuri() {
    return curMuri;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.Cur_Muri
   * @param curMuri  the value for TBL_SEI01_HEAD.Cur_Muri
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setCurMuri(Integer curMuri) {
    this.curMuri = curMuri;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.Cur_Tax
   * @return  the value of TBL_SEI01_HEAD.Cur_Tax
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public Integer getCurTax() {
    return curTax;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.Cur_Tax
   * @param curTax  the value for TBL_SEI01_HEAD.Cur_Tax
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setCurTax(Integer curTax) {
    this.curTax = curTax;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.Cur_UTax
   * @return  the value of TBL_SEI01_HEAD.Cur_UTax
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public Integer getCurUtax() {
    return curUtax;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.Cur_UTax
   * @param curUtax  the value for TBL_SEI01_HEAD.Cur_UTax
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setCurUtax(Integer curUtax) {
    this.curUtax = curUtax;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.Cur_MTax
   * @return  the value of TBL_SEI01_HEAD.Cur_MTax
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public Integer getCurMtax() {
    return curMtax;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.Cur_MTax
   * @param curMtax  the value for TBL_SEI01_HEAD.Cur_MTax
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setCurMtax(Integer curMtax) {
    this.curMtax = curMtax;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.Cur_UAmt
   * @return  the value of TBL_SEI01_HEAD.Cur_UAmt
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public Integer getCurUamt() {
    return curUamt;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.Cur_UAmt
   * @param curUamt  the value for TBL_SEI01_HEAD.Cur_UAmt
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setCurUamt(Integer curUamt) {
    this.curUamt = curUamt;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.Cur_MAmt
   * @return  the value of TBL_SEI01_HEAD.Cur_MAmt
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public Integer getCurMamt() {
    return curMamt;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.Cur_MAmt
   * @param curMamt  the value for TBL_SEI01_HEAD.Cur_MAmt
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setCurMamt(Integer curMamt) {
    this.curMamt = curMamt;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.Uri_Zan
   * @return  the value of TBL_SEI01_HEAD.Uri_Zan
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public Integer getUriZan() {
    return uriZan;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.Uri_Zan
   * @param uriZan  the value for TBL_SEI01_HEAD.Uri_Zan
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setUriZan(Integer uriZan) {
    this.uriZan = uriZan;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.Mis_Zan
   * @return  the value of TBL_SEI01_HEAD.Mis_Zan
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public Integer getMisZan() {
    return misZan;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.Mis_Zan
   * @param misZan  the value for TBL_SEI01_HEAD.Mis_Zan
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setMisZan(Integer misZan) {
    this.misZan = misZan;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.Bild_Dat_Flg
   * @return  the value of TBL_SEI01_HEAD.Bild_Dat_Flg
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public String getBildDatFlg() {
    return bildDatFlg;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.Bild_Dat_Flg
   * @param bildDatFlg  the value for TBL_SEI01_HEAD.Bild_Dat_Flg
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setBildDatFlg(String bildDatFlg) {
    this.bildDatFlg = bildDatFlg;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.Prev_Bild_Id
   * @return  the value of TBL_SEI01_HEAD.Prev_Bild_Id
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public Long getPrevBildId() {
    return prevBildId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.Prev_Bild_Id
   * @param prevBildId  the value for TBL_SEI01_HEAD.Prev_Bild_Id
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setPrevBildId(Long prevBildId) {
    this.prevBildId = prevBildId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.Cust_Cls
   * @return  the value of TBL_SEI01_HEAD.Cust_Cls
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public String getCustCls() {
    return custCls;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.Cust_Cls
   * @param custCls  the value for TBL_SEI01_HEAD.Cust_Cls
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setCustCls(String custCls) {
    this.custCls = custCls;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.Bild_New_Flg
   * @return  the value of TBL_SEI01_HEAD.Bild_New_Flg
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public String getBildNewFlg() {
    return bildNewFlg;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.Bild_New_Flg
   * @param bildNewFlg  the value for TBL_SEI01_HEAD.Bild_New_Flg
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setBildNewFlg(String bildNewFlg) {
    this.bildNewFlg = bildNewFlg;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.Sts_Code
   * @return  the value of TBL_SEI01_HEAD.Sts_Code
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public String getStsCode() {
    return stsCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.Sts_Code
   * @param stsCode  the value for TBL_SEI01_HEAD.Sts_Code
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setStsCode(String stsCode) {
    this.stsCode = stsCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.INS_USERID
   * @return  the value of TBL_SEI01_HEAD.INS_USERID
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public String getInsUserid() {
    return insUserid;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.INS_USERID
   * @param insUserid  the value for TBL_SEI01_HEAD.INS_USERID
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setInsUserid(String insUserid) {
    this.insUserid = insUserid;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.INS_PGID
   * @return  the value of TBL_SEI01_HEAD.INS_PGID
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public String getInsPgid() {
    return insPgid;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.INS_PGID
   * @param insPgid  the value for TBL_SEI01_HEAD.INS_PGID
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setInsPgid(String insPgid) {
    this.insPgid = insPgid;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.INS_YMD
   * @return  the value of TBL_SEI01_HEAD.INS_YMD
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public String getInsYmd() {
    return insYmd;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.INS_YMD
   * @param insYmd  the value for TBL_SEI01_HEAD.INS_YMD
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setInsYmd(String insYmd) {
    this.insYmd = insYmd;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.INS_TIME
   * @return  the value of TBL_SEI01_HEAD.INS_TIME
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public String getInsTime() {
    return insTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.INS_TIME
   * @param insTime  the value for TBL_SEI01_HEAD.INS_TIME
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setInsTime(String insTime) {
    this.insTime = insTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.UPD_USERID
   * @return  the value of TBL_SEI01_HEAD.UPD_USERID
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public String getUpdUserid() {
    return updUserid;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.UPD_USERID
   * @param updUserid  the value for TBL_SEI01_HEAD.UPD_USERID
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setUpdUserid(String updUserid) {
    this.updUserid = updUserid;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.UPD_PGID
   * @return  the value of TBL_SEI01_HEAD.UPD_PGID
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public String getUpdPgid() {
    return updPgid;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.UPD_PGID
   * @param updPgid  the value for TBL_SEI01_HEAD.UPD_PGID
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setUpdPgid(String updPgid) {
    this.updPgid = updPgid;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.UPD_YMD
   * @return  the value of TBL_SEI01_HEAD.UPD_YMD
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public String getUpdYmd() {
    return updYmd;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.UPD_YMD
   * @param updYmd  the value for TBL_SEI01_HEAD.UPD_YMD
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setUpdYmd(String updYmd) {
    this.updYmd = updYmd;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column TBL_SEI01_HEAD.UPD_TIME
   * @return  the value of TBL_SEI01_HEAD.UPD_TIME
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public String getUpdTime() {
    return updTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column TBL_SEI01_HEAD.UPD_TIME
   * @param updTime  the value for TBL_SEI01_HEAD.UPD_TIME
   * @mbggenerated  Mon Nov 23 20:19:06 ICT 2015
   */
  public void setUpdTime(String updTime) {
    this.updTime = updTime;
  }
}