package jp.co.daitoku_sh.dfcm.common.db.model;

import java.math.BigDecimal;

public class WrkJuc01Olrcv extends WrkJuc01OlrcvKey {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Data_Syb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String dataSyb;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Ordr_Date
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String ordrDate;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Den_No
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String denNo;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Den_Row
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private Short denRow;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Deli_Date
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String deliDate;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Bin
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String bin;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Adup_Date
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String adupDate;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Jigyo_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String jigyoCode;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Chain_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String chainCode;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Chain_Idx
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String chainIdx;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Chain_Nm
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String chainNm;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.C_Sale_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String cSaleKb;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Cust_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String custCode;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Cust_Nm
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String custNm;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Cust_Nm_R
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String custNmR;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Cust_Nm_Kana
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String custNmKana;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Deli_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String deliCode;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Deli_Nm
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String deliNm;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Shop_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String shopCode;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Shop_Nm
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String shopNm;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Shn_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String shnCode;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Shn_Nm
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String shnNm;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Item_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String itemCode;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Item_Nm
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String itemNm;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Ryomoku
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private BigDecimal ryomoku;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Ireme
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private Short ireme;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Jch_Su
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private Integer jchSu;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Depart_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private Short departCode;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Item_Frm_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private Short itemFrmCode;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Temp_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private Short tempCode;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Amt_Rnd_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String amtRndKb;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Deli_Price
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private BigDecimal deliPrice;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Deli_Amt
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private Integer deliAmt;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Deli_Price_H
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private BigDecimal deliPriceH;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Deli_Amt_H
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private Integer deliAmtH;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Deli_Tax
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private Integer deliTax;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Snp_Skri_Price
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private BigDecimal snpSkriPrice;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Snp_Skri_Amt
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private Integer snpSkriAmt;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Snp_Skri_Price_H
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private BigDecimal snpSkriPriceH;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Snp_Skri_Amt_H
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private Integer snpSkriAmtH;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Snp_Skri_Tax
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private Integer snpSkriTax;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Sale_Price
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private Integer salePrice;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Sale_Amt
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private Integer saleAmt;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Skri_Price
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private BigDecimal skriPrice;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Skr_Amt
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private Integer skrAmt;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Collect_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String collectKb;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Cancel_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String cancelKb;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Product_Date
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String productDate;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Fwd_Deli_Date
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String fwdDeliDate;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Skr_Rnd_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String skrRndKb;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Skr_Rnd_Keta
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String skrRndKeta;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Deli_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String deliKb;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Sale_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String saleKb;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Tax_Inc_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String taxIncKb;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Tax_Inc_Frc_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String taxIncFrcKb;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Ships_rud_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String shipsRudKb;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Shop_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String shopKb;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Ships_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String shipsKb;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Ships_Typ
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String shipsTyp;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Item_Ctgr
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String itemCtgr;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.Acc_Due_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String accDueKb;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.INS_USERID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String insUserid;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.INS_PGID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String insPgid;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.INS_YMD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String insYmd;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.INS_TIME
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String insTime;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.UPD_USERID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String updUserid;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.UPD_PGID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String updPgid;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.UPD_YMD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String updYmd;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column WRK_JUC01_OLRCV.UPD_TIME
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  private String updTime;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Data_Syb
   * @return  the value of WRK_JUC01_OLRCV.Data_Syb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getDataSyb() {
    return dataSyb;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Data_Syb
   * @param dataSyb  the value for WRK_JUC01_OLRCV.Data_Syb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setDataSyb(String dataSyb) {
    this.dataSyb = dataSyb;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Ordr_Date
   * @return  the value of WRK_JUC01_OLRCV.Ordr_Date
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getOrdrDate() {
    return ordrDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Ordr_Date
   * @param ordrDate  the value for WRK_JUC01_OLRCV.Ordr_Date
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setOrdrDate(String ordrDate) {
    this.ordrDate = ordrDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Den_No
   * @return  the value of WRK_JUC01_OLRCV.Den_No
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getDenNo() {
    return denNo;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Den_No
   * @param denNo  the value for WRK_JUC01_OLRCV.Den_No
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setDenNo(String denNo) {
    this.denNo = denNo;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Den_Row
   * @return  the value of WRK_JUC01_OLRCV.Den_Row
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public Short getDenRow() {
    return denRow;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Den_Row
   * @param denRow  the value for WRK_JUC01_OLRCV.Den_Row
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setDenRow(Short denRow) {
    this.denRow = denRow;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Deli_Date
   * @return  the value of WRK_JUC01_OLRCV.Deli_Date
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getDeliDate() {
    return deliDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Deli_Date
   * @param deliDate  the value for WRK_JUC01_OLRCV.Deli_Date
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setDeliDate(String deliDate) {
    this.deliDate = deliDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Bin
   * @return  the value of WRK_JUC01_OLRCV.Bin
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getBin() {
    return bin;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Bin
   * @param bin  the value for WRK_JUC01_OLRCV.Bin
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setBin(String bin) {
    this.bin = bin;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Adup_Date
   * @return  the value of WRK_JUC01_OLRCV.Adup_Date
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getAdupDate() {
    return adupDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Adup_Date
   * @param adupDate  the value for WRK_JUC01_OLRCV.Adup_Date
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setAdupDate(String adupDate) {
    this.adupDate = adupDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Jigyo_Code
   * @return  the value of WRK_JUC01_OLRCV.Jigyo_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getJigyoCode() {
    return jigyoCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Jigyo_Code
   * @param jigyoCode  the value for WRK_JUC01_OLRCV.Jigyo_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setJigyoCode(String jigyoCode) {
    this.jigyoCode = jigyoCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Chain_Code
   * @return  the value of WRK_JUC01_OLRCV.Chain_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getChainCode() {
    return chainCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Chain_Code
   * @param chainCode  the value for WRK_JUC01_OLRCV.Chain_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setChainCode(String chainCode) {
    this.chainCode = chainCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Chain_Idx
   * @return  the value of WRK_JUC01_OLRCV.Chain_Idx
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getChainIdx() {
    return chainIdx;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Chain_Idx
   * @param chainIdx  the value for WRK_JUC01_OLRCV.Chain_Idx
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setChainIdx(String chainIdx) {
    this.chainIdx = chainIdx;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Chain_Nm
   * @return  the value of WRK_JUC01_OLRCV.Chain_Nm
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getChainNm() {
    return chainNm;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Chain_Nm
   * @param chainNm  the value for WRK_JUC01_OLRCV.Chain_Nm
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setChainNm(String chainNm) {
    this.chainNm = chainNm;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.C_Sale_Kb
   * @return  the value of WRK_JUC01_OLRCV.C_Sale_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getcSaleKb() {
    return cSaleKb;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.C_Sale_Kb
   * @param cSaleKb  the value for WRK_JUC01_OLRCV.C_Sale_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setcSaleKb(String cSaleKb) {
    this.cSaleKb = cSaleKb;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Cust_Code
   * @return  the value of WRK_JUC01_OLRCV.Cust_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getCustCode() {
    return custCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Cust_Code
   * @param custCode  the value for WRK_JUC01_OLRCV.Cust_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setCustCode(String custCode) {
    this.custCode = custCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Cust_Nm
   * @return  the value of WRK_JUC01_OLRCV.Cust_Nm
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getCustNm() {
    return custNm;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Cust_Nm
   * @param custNm  the value for WRK_JUC01_OLRCV.Cust_Nm
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setCustNm(String custNm) {
    this.custNm = custNm;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Cust_Nm_R
   * @return  the value of WRK_JUC01_OLRCV.Cust_Nm_R
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getCustNmR() {
    return custNmR;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Cust_Nm_R
   * @param custNmR  the value for WRK_JUC01_OLRCV.Cust_Nm_R
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setCustNmR(String custNmR) {
    this.custNmR = custNmR;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Cust_Nm_Kana
   * @return  the value of WRK_JUC01_OLRCV.Cust_Nm_Kana
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getCustNmKana() {
    return custNmKana;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Cust_Nm_Kana
   * @param custNmKana  the value for WRK_JUC01_OLRCV.Cust_Nm_Kana
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setCustNmKana(String custNmKana) {
    this.custNmKana = custNmKana;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Deli_Code
   * @return  the value of WRK_JUC01_OLRCV.Deli_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getDeliCode() {
    return deliCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Deli_Code
   * @param deliCode  the value for WRK_JUC01_OLRCV.Deli_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setDeliCode(String deliCode) {
    this.deliCode = deliCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Deli_Nm
   * @return  the value of WRK_JUC01_OLRCV.Deli_Nm
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getDeliNm() {
    return deliNm;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Deli_Nm
   * @param deliNm  the value for WRK_JUC01_OLRCV.Deli_Nm
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setDeliNm(String deliNm) {
    this.deliNm = deliNm;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Shop_Code
   * @return  the value of WRK_JUC01_OLRCV.Shop_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getShopCode() {
    return shopCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Shop_Code
   * @param shopCode  the value for WRK_JUC01_OLRCV.Shop_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setShopCode(String shopCode) {
    this.shopCode = shopCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Shop_Nm
   * @return  the value of WRK_JUC01_OLRCV.Shop_Nm
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getShopNm() {
    return shopNm;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Shop_Nm
   * @param shopNm  the value for WRK_JUC01_OLRCV.Shop_Nm
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setShopNm(String shopNm) {
    this.shopNm = shopNm;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Shn_Code
   * @return  the value of WRK_JUC01_OLRCV.Shn_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getShnCode() {
    return shnCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Shn_Code
   * @param shnCode  the value for WRK_JUC01_OLRCV.Shn_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setShnCode(String shnCode) {
    this.shnCode = shnCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Shn_Nm
   * @return  the value of WRK_JUC01_OLRCV.Shn_Nm
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getShnNm() {
    return shnNm;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Shn_Nm
   * @param shnNm  the value for WRK_JUC01_OLRCV.Shn_Nm
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setShnNm(String shnNm) {
    this.shnNm = shnNm;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Item_Code
   * @return  the value of WRK_JUC01_OLRCV.Item_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getItemCode() {
    return itemCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Item_Code
   * @param itemCode  the value for WRK_JUC01_OLRCV.Item_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setItemCode(String itemCode) {
    this.itemCode = itemCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Item_Nm
   * @return  the value of WRK_JUC01_OLRCV.Item_Nm
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getItemNm() {
    return itemNm;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Item_Nm
   * @param itemNm  the value for WRK_JUC01_OLRCV.Item_Nm
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setItemNm(String itemNm) {
    this.itemNm = itemNm;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Ryomoku
   * @return  the value of WRK_JUC01_OLRCV.Ryomoku
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public BigDecimal getRyomoku() {
    return ryomoku;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Ryomoku
   * @param ryomoku  the value for WRK_JUC01_OLRCV.Ryomoku
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setRyomoku(BigDecimal ryomoku) {
    this.ryomoku = ryomoku;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Ireme
   * @return  the value of WRK_JUC01_OLRCV.Ireme
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public Short getIreme() {
    return ireme;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Ireme
   * @param ireme  the value for WRK_JUC01_OLRCV.Ireme
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setIreme(Short ireme) {
    this.ireme = ireme;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Jch_Su
   * @return  the value of WRK_JUC01_OLRCV.Jch_Su
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public Integer getJchSu() {
    return jchSu;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Jch_Su
   * @param jchSu  the value for WRK_JUC01_OLRCV.Jch_Su
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setJchSu(Integer jchSu) {
    this.jchSu = jchSu;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Depart_Code
   * @return  the value of WRK_JUC01_OLRCV.Depart_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public Short getDepartCode() {
    return departCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Depart_Code
   * @param departCode  the value for WRK_JUC01_OLRCV.Depart_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setDepartCode(Short departCode) {
    this.departCode = departCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Item_Frm_Code
   * @return  the value of WRK_JUC01_OLRCV.Item_Frm_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public Short getItemFrmCode() {
    return itemFrmCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Item_Frm_Code
   * @param itemFrmCode  the value for WRK_JUC01_OLRCV.Item_Frm_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setItemFrmCode(Short itemFrmCode) {
    this.itemFrmCode = itemFrmCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Temp_Code
   * @return  the value of WRK_JUC01_OLRCV.Temp_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public Short getTempCode() {
    return tempCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Temp_Code
   * @param tempCode  the value for WRK_JUC01_OLRCV.Temp_Code
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTempCode(Short tempCode) {
    this.tempCode = tempCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Amt_Rnd_Kb
   * @return  the value of WRK_JUC01_OLRCV.Amt_Rnd_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getAmtRndKb() {
    return amtRndKb;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Amt_Rnd_Kb
   * @param amtRndKb  the value for WRK_JUC01_OLRCV.Amt_Rnd_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setAmtRndKb(String amtRndKb) {
    this.amtRndKb = amtRndKb;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Deli_Price
   * @return  the value of WRK_JUC01_OLRCV.Deli_Price
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public BigDecimal getDeliPrice() {
    return deliPrice;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Deli_Price
   * @param deliPrice  the value for WRK_JUC01_OLRCV.Deli_Price
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setDeliPrice(BigDecimal deliPrice) {
    this.deliPrice = deliPrice;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Deli_Amt
   * @return  the value of WRK_JUC01_OLRCV.Deli_Amt
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public Integer getDeliAmt() {
    return deliAmt;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Deli_Amt
   * @param deliAmt  the value for WRK_JUC01_OLRCV.Deli_Amt
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setDeliAmt(Integer deliAmt) {
    this.deliAmt = deliAmt;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Deli_Price_H
   * @return  the value of WRK_JUC01_OLRCV.Deli_Price_H
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public BigDecimal getDeliPriceH() {
    return deliPriceH;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Deli_Price_H
   * @param deliPriceH  the value for WRK_JUC01_OLRCV.Deli_Price_H
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setDeliPriceH(BigDecimal deliPriceH) {
    this.deliPriceH = deliPriceH;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Deli_Amt_H
   * @return  the value of WRK_JUC01_OLRCV.Deli_Amt_H
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public Integer getDeliAmtH() {
    return deliAmtH;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Deli_Amt_H
   * @param deliAmtH  the value for WRK_JUC01_OLRCV.Deli_Amt_H
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setDeliAmtH(Integer deliAmtH) {
    this.deliAmtH = deliAmtH;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Deli_Tax
   * @return  the value of WRK_JUC01_OLRCV.Deli_Tax
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public Integer getDeliTax() {
    return deliTax;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Deli_Tax
   * @param deliTax  the value for WRK_JUC01_OLRCV.Deli_Tax
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setDeliTax(Integer deliTax) {
    this.deliTax = deliTax;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Snp_Skri_Price
   * @return  the value of WRK_JUC01_OLRCV.Snp_Skri_Price
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public BigDecimal getSnpSkriPrice() {
    return snpSkriPrice;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Snp_Skri_Price
   * @param snpSkriPrice  the value for WRK_JUC01_OLRCV.Snp_Skri_Price
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setSnpSkriPrice(BigDecimal snpSkriPrice) {
    this.snpSkriPrice = snpSkriPrice;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Snp_Skri_Amt
   * @return  the value of WRK_JUC01_OLRCV.Snp_Skri_Amt
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public Integer getSnpSkriAmt() {
    return snpSkriAmt;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Snp_Skri_Amt
   * @param snpSkriAmt  the value for WRK_JUC01_OLRCV.Snp_Skri_Amt
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setSnpSkriAmt(Integer snpSkriAmt) {
    this.snpSkriAmt = snpSkriAmt;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Snp_Skri_Price_H
   * @return  the value of WRK_JUC01_OLRCV.Snp_Skri_Price_H
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public BigDecimal getSnpSkriPriceH() {
    return snpSkriPriceH;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Snp_Skri_Price_H
   * @param snpSkriPriceH  the value for WRK_JUC01_OLRCV.Snp_Skri_Price_H
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setSnpSkriPriceH(BigDecimal snpSkriPriceH) {
    this.snpSkriPriceH = snpSkriPriceH;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Snp_Skri_Amt_H
   * @return  the value of WRK_JUC01_OLRCV.Snp_Skri_Amt_H
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public Integer getSnpSkriAmtH() {
    return snpSkriAmtH;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Snp_Skri_Amt_H
   * @param snpSkriAmtH  the value for WRK_JUC01_OLRCV.Snp_Skri_Amt_H
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setSnpSkriAmtH(Integer snpSkriAmtH) {
    this.snpSkriAmtH = snpSkriAmtH;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Snp_Skri_Tax
   * @return  the value of WRK_JUC01_OLRCV.Snp_Skri_Tax
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public Integer getSnpSkriTax() {
    return snpSkriTax;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Snp_Skri_Tax
   * @param snpSkriTax  the value for WRK_JUC01_OLRCV.Snp_Skri_Tax
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setSnpSkriTax(Integer snpSkriTax) {
    this.snpSkriTax = snpSkriTax;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Sale_Price
   * @return  the value of WRK_JUC01_OLRCV.Sale_Price
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public Integer getSalePrice() {
    return salePrice;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Sale_Price
   * @param salePrice  the value for WRK_JUC01_OLRCV.Sale_Price
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setSalePrice(Integer salePrice) {
    this.salePrice = salePrice;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Sale_Amt
   * @return  the value of WRK_JUC01_OLRCV.Sale_Amt
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public Integer getSaleAmt() {
    return saleAmt;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Sale_Amt
   * @param saleAmt  the value for WRK_JUC01_OLRCV.Sale_Amt
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setSaleAmt(Integer saleAmt) {
    this.saleAmt = saleAmt;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Skri_Price
   * @return  the value of WRK_JUC01_OLRCV.Skri_Price
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public BigDecimal getSkriPrice() {
    return skriPrice;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Skri_Price
   * @param skriPrice  the value for WRK_JUC01_OLRCV.Skri_Price
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setSkriPrice(BigDecimal skriPrice) {
    this.skriPrice = skriPrice;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Skr_Amt
   * @return  the value of WRK_JUC01_OLRCV.Skr_Amt
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public Integer getSkrAmt() {
    return skrAmt;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Skr_Amt
   * @param skrAmt  the value for WRK_JUC01_OLRCV.Skr_Amt
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setSkrAmt(Integer skrAmt) {
    this.skrAmt = skrAmt;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Collect_Kb
   * @return  the value of WRK_JUC01_OLRCV.Collect_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getCollectKb() {
    return collectKb;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Collect_Kb
   * @param collectKb  the value for WRK_JUC01_OLRCV.Collect_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setCollectKb(String collectKb) {
    this.collectKb = collectKb;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Cancel_Kb
   * @return  the value of WRK_JUC01_OLRCV.Cancel_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getCancelKb() {
    return cancelKb;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Cancel_Kb
   * @param cancelKb  the value for WRK_JUC01_OLRCV.Cancel_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setCancelKb(String cancelKb) {
    this.cancelKb = cancelKb;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Product_Date
   * @return  the value of WRK_JUC01_OLRCV.Product_Date
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getProductDate() {
    return productDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Product_Date
   * @param productDate  the value for WRK_JUC01_OLRCV.Product_Date
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setProductDate(String productDate) {
    this.productDate = productDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Fwd_Deli_Date
   * @return  the value of WRK_JUC01_OLRCV.Fwd_Deli_Date
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getFwdDeliDate() {
    return fwdDeliDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Fwd_Deli_Date
   * @param fwdDeliDate  the value for WRK_JUC01_OLRCV.Fwd_Deli_Date
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setFwdDeliDate(String fwdDeliDate) {
    this.fwdDeliDate = fwdDeliDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Skr_Rnd_Kb
   * @return  the value of WRK_JUC01_OLRCV.Skr_Rnd_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getSkrRndKb() {
    return skrRndKb;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Skr_Rnd_Kb
   * @param skrRndKb  the value for WRK_JUC01_OLRCV.Skr_Rnd_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setSkrRndKb(String skrRndKb) {
    this.skrRndKb = skrRndKb;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Skr_Rnd_Keta
   * @return  the value of WRK_JUC01_OLRCV.Skr_Rnd_Keta
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getSkrRndKeta() {
    return skrRndKeta;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Skr_Rnd_Keta
   * @param skrRndKeta  the value for WRK_JUC01_OLRCV.Skr_Rnd_Keta
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setSkrRndKeta(String skrRndKeta) {
    this.skrRndKeta = skrRndKeta;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Deli_Kb
   * @return  the value of WRK_JUC01_OLRCV.Deli_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getDeliKb() {
    return deliKb;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Deli_Kb
   * @param deliKb  the value for WRK_JUC01_OLRCV.Deli_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setDeliKb(String deliKb) {
    this.deliKb = deliKb;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Sale_Kb
   * @return  the value of WRK_JUC01_OLRCV.Sale_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getSaleKb() {
    return saleKb;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Sale_Kb
   * @param saleKb  the value for WRK_JUC01_OLRCV.Sale_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setSaleKb(String saleKb) {
    this.saleKb = saleKb;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Tax_Inc_Kb
   * @return  the value of WRK_JUC01_OLRCV.Tax_Inc_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getTaxIncKb() {
    return taxIncKb;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Tax_Inc_Kb
   * @param taxIncKb  the value for WRK_JUC01_OLRCV.Tax_Inc_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTaxIncKb(String taxIncKb) {
    this.taxIncKb = taxIncKb;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Tax_Inc_Frc_Kb
   * @return  the value of WRK_JUC01_OLRCV.Tax_Inc_Frc_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getTaxIncFrcKb() {
    return taxIncFrcKb;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Tax_Inc_Frc_Kb
   * @param taxIncFrcKb  the value for WRK_JUC01_OLRCV.Tax_Inc_Frc_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setTaxIncFrcKb(String taxIncFrcKb) {
    this.taxIncFrcKb = taxIncFrcKb;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Ships_rud_Kb
   * @return  the value of WRK_JUC01_OLRCV.Ships_rud_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getShipsRudKb() {
    return shipsRudKb;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Ships_rud_Kb
   * @param shipsRudKb  the value for WRK_JUC01_OLRCV.Ships_rud_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setShipsRudKb(String shipsRudKb) {
    this.shipsRudKb = shipsRudKb;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Shop_Kb
   * @return  the value of WRK_JUC01_OLRCV.Shop_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getShopKb() {
    return shopKb;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Shop_Kb
   * @param shopKb  the value for WRK_JUC01_OLRCV.Shop_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setShopKb(String shopKb) {
    this.shopKb = shopKb;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Ships_Kb
   * @return  the value of WRK_JUC01_OLRCV.Ships_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getShipsKb() {
    return shipsKb;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Ships_Kb
   * @param shipsKb  the value for WRK_JUC01_OLRCV.Ships_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setShipsKb(String shipsKb) {
    this.shipsKb = shipsKb;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Ships_Typ
   * @return  the value of WRK_JUC01_OLRCV.Ships_Typ
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getShipsTyp() {
    return shipsTyp;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Ships_Typ
   * @param shipsTyp  the value for WRK_JUC01_OLRCV.Ships_Typ
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setShipsTyp(String shipsTyp) {
    this.shipsTyp = shipsTyp;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Item_Ctgr
   * @return  the value of WRK_JUC01_OLRCV.Item_Ctgr
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getItemCtgr() {
    return itemCtgr;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Item_Ctgr
   * @param itemCtgr  the value for WRK_JUC01_OLRCV.Item_Ctgr
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setItemCtgr(String itemCtgr) {
    this.itemCtgr = itemCtgr;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.Acc_Due_Kb
   * @return  the value of WRK_JUC01_OLRCV.Acc_Due_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getAccDueKb() {
    return accDueKb;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.Acc_Due_Kb
   * @param accDueKb  the value for WRK_JUC01_OLRCV.Acc_Due_Kb
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setAccDueKb(String accDueKb) {
    this.accDueKb = accDueKb;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.INS_USERID
   * @return  the value of WRK_JUC01_OLRCV.INS_USERID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getInsUserid() {
    return insUserid;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.INS_USERID
   * @param insUserid  the value for WRK_JUC01_OLRCV.INS_USERID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setInsUserid(String insUserid) {
    this.insUserid = insUserid;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.INS_PGID
   * @return  the value of WRK_JUC01_OLRCV.INS_PGID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getInsPgid() {
    return insPgid;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.INS_PGID
   * @param insPgid  the value for WRK_JUC01_OLRCV.INS_PGID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setInsPgid(String insPgid) {
    this.insPgid = insPgid;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.INS_YMD
   * @return  the value of WRK_JUC01_OLRCV.INS_YMD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getInsYmd() {
    return insYmd;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.INS_YMD
   * @param insYmd  the value for WRK_JUC01_OLRCV.INS_YMD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setInsYmd(String insYmd) {
    this.insYmd = insYmd;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.INS_TIME
   * @return  the value of WRK_JUC01_OLRCV.INS_TIME
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getInsTime() {
    return insTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.INS_TIME
   * @param insTime  the value for WRK_JUC01_OLRCV.INS_TIME
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setInsTime(String insTime) {
    this.insTime = insTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.UPD_USERID
   * @return  the value of WRK_JUC01_OLRCV.UPD_USERID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getUpdUserid() {
    return updUserid;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.UPD_USERID
   * @param updUserid  the value for WRK_JUC01_OLRCV.UPD_USERID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setUpdUserid(String updUserid) {
    this.updUserid = updUserid;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.UPD_PGID
   * @return  the value of WRK_JUC01_OLRCV.UPD_PGID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getUpdPgid() {
    return updPgid;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.UPD_PGID
   * @param updPgid  the value for WRK_JUC01_OLRCV.UPD_PGID
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setUpdPgid(String updPgid) {
    this.updPgid = updPgid;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.UPD_YMD
   * @return  the value of WRK_JUC01_OLRCV.UPD_YMD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getUpdYmd() {
    return updYmd;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.UPD_YMD
   * @param updYmd  the value for WRK_JUC01_OLRCV.UPD_YMD
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setUpdYmd(String updYmd) {
    this.updYmd = updYmd;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column WRK_JUC01_OLRCV.UPD_TIME
   * @return  the value of WRK_JUC01_OLRCV.UPD_TIME
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public String getUpdTime() {
    return updTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column WRK_JUC01_OLRCV.UPD_TIME
   * @param updTime  the value for WRK_JUC01_OLRCV.UPD_TIME
   * @mbggenerated  Sat Oct 24 16:19:36 ICT 2015
   */
  public void setUpdTime(String updTime) {
    this.updTime = updTime;
  }
}